# Cloud Build configuration for automated deployment
# This file is used when you connect your GitHub repo to Cloud Build

steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: npm
    args: ['ci']
    
  # Run tests (optional - uncomment when tests are ready)
  # - name: 'node:18-alpine'
  #   entrypoint: npm
  #   args: ['test']
  
  # Build TypeScript
  - name: 'node:18-alpine'
    entrypoint: npm
    args: ['run', 'build']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fortune-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fortune-api:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--set-env-vars'
      - 'NODE_ENV=production,API_VERSION=v1'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

# Substitutions can be defined in Cloud Build trigger
substitutions:
  _SERVICE_NAME: fortune-api
  _REGION: asia-northeast3