-- 유명인사 사주 데이터 삽입 SQL
-- 총 10명의 데이터

INSERT INTO celebrities (
  name, name_en, birth_date, birth_time, gender,
  birth_place, category, agency,
  year_pillar, month_pillar, day_pillar, hour_pillar,
  saju_string,
  wood_count, fire_count, earth_count, metal_count, water_count,
  full_saju_data, data_source, created_at, updated_at
) VALUES
  ('이효리', 'Lee Hyo-ri', '1979-05-10', '12:00', 'F', '경기도 성남시', '가수', '핀네이션', '기미', '기사', '정미', '병오', '기미 기사 정미 병오', 0, 2, 2, 0, 0, '{"year":{"stem":"기","branch":"미","stemHanja":"己","branchHanja":"未","element":"토"},"month":{"stem":"기","branch":"사","stemHanja":"己","branchHanja":"巳","element":"토"},"day":{"stem":"정","branch":"미","stemHanja":"丁","branchHanja":"未","element":"화"},"hour":{"stem":"병","branch":"오","stemHanja":"丙","branchHanja":"午","element":"화"},"elementBalance":{"목":0,"화":4,"토":4,"금":0,"수":0},"tenGods":{"year":["식신"],"month":["식신"],"hour":["정인"]},"daeunInfo":{"currentAge":46,"startAge":40,"endAge":49,"stem":"계","branch":"유","stemHanja":"癸","branchHanja":"酉"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.558328', '2025-08-27T20:56:25.558346'),
  ('박진영', 'Park Jin-young', '1972-12-13', '12:00', 'M', '서울특별시 강서구', '가수', 'JYP엔터테인먼트', '임자', '임자', '무신', '무오', '임자 임자 무신 무오', 0, 0, 2, 0, 2, '{"year":{"stem":"임","branch":"자","stemHanja":"壬","branchHanja":"子","element":"수"},"month":{"stem":"임","branch":"자","stemHanja":"壬","branchHanja":"子","element":"수"},"day":{"stem":"무","branch":"신","stemHanja":"戊","branchHanja":"申","element":"토"},"hour":{"stem":"무","branch":"오","stemHanja":"戊","branchHanja":"午","element":"토"},"elementBalance":{"목":0,"화":1,"토":2,"금":1,"수":4},"tenGods":{"year":["편재"],"month":["편재"],"hour":["비견"]},"daeunInfo":{"currentAge":53,"startAge":50,"endAge":59,"stem":"정","branch":"사","stemHanja":"丁","branchHanja":"巳"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.558727', '2025-08-27T20:56:25.558733'),
  ('방탄소년단 RM', '방탄소년단 RM', '1994-09-12', '12:00', 'M', '경기도 고양시', '가수', '빅히트뮤직', '갑술', '계유', '신미', '갑오', '갑술 계유 신미 갑오', 2, 0, 0, 1, 1, '{"year":{"stem":"갑","branch":"술","stemHanja":"甲","branchHanja":"戌","element":"목"},"month":{"stem":"계","branch":"유","stemHanja":"癸","branchHanja":"酉","element":"수"},"day":{"stem":"신","branch":"미","stemHanja":"辛","branchHanja":"未","element":"금"},"hour":{"stem":"갑","branch":"오","stemHanja":"甲","branchHanja":"午","element":"목"},"elementBalance":{"목":2,"화":1,"토":2,"금":2,"수":1},"tenGods":{"year":["상관"],"month":["식신"],"hour":["상관"]},"daeunInfo":{"currentAge":31,"startAge":30,"endAge":39,"stem":"병","branch":"자","stemHanja":"丙","branchHanja":"子"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.558815', '2025-08-27T20:56:25.558824'),
  ('송혜교', 'Song Hye-kyo', '1981-11-22', '12:00', 'F', '대구광역시', '배우', 'UAA', '신유', '기해', '갑술', '경오', '신유 기해 갑술 경오', 1, 0, 1, 2, 0, '{"year":{"stem":"신","branch":"유","stemHanja":"辛","branchHanja":"酉","element":"금"},"month":{"stem":"기","branch":"해","stemHanja":"己","branchHanja":"亥","element":"토"},"day":{"stem":"갑","branch":"술","stemHanja":"甲","branchHanja":"戌","element":"목"},"hour":{"stem":"경","branch":"오","stemHanja":"庚","branchHanja":"午","element":"금"},"elementBalance":{"목":1,"화":1,"토":2,"금":3,"수":1},"tenGods":{"year":["정관"],"month":["정재"],"hour":["편관"]},"daeunInfo":{"currentAge":44,"startAge":40,"endAge":49,"stem":"계","branch":"묘","stemHanja":"癸","branchHanja":"卯"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.558884', '2025-08-27T20:56:25.558889'),
  ('현빈', 'Hyun Bin', '1982-09-25', '12:00', 'M', '서울특별시', '배우', 'VAST엔터테인먼트', '임술', '기유', '신사', '갑오', '임술 기유 신사 갑오', 1, 0, 1, 1, 1, '{"year":{"stem":"임","branch":"술","stemHanja":"壬","branchHanja":"戌","element":"수"},"month":{"stem":"기","branch":"유","stemHanja":"己","branchHanja":"酉","element":"토"},"day":{"stem":"신","branch":"사","stemHanja":"辛","branchHanja":"巳","element":"금"},"hour":{"stem":"갑","branch":"오","stemHanja":"甲","branchHanja":"午","element":"목"},"elementBalance":{"목":1,"화":2,"토":2,"금":2,"수":1},"tenGods":{"year":["겁재"],"month":["편인"],"hour":["상관"]},"daeunInfo":{"currentAge":43,"startAge":40,"endAge":49,"stem":"계","branch":"축","stemHanja":"癸","branchHanja":"丑"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.558945', '2025-08-27T20:56:25.558949'),
  ('최태원', 'Choi Tae-won', '1960-12-03', '12:00', 'M', '서울특별시', '기업인', 'SK그룹', '경자', '정해', '을미', '임오', '경자 정해 을미 임오', 1, 1, 0, 1, 1, '{"year":{"stem":"경","branch":"자","stemHanja":"庚","branchHanja":"子","element":"금"},"month":{"stem":"정","branch":"해","stemHanja":"丁","branchHanja":"亥","element":"화"},"day":{"stem":"을","branch":"미","stemHanja":"乙","branchHanja":"未","element":"목"},"hour":{"stem":"임","branch":"오","stemHanja":"壬","branchHanja":"午","element":"수"},"elementBalance":{"목":1,"화":2,"토":1,"금":1,"수":3},"tenGods":{"year":["정재"],"month":["식신"],"hour":["정관"]},"daeunInfo":{"currentAge":65,"startAge":60,"endAge":69,"stem":"계","branch":"사","stemHanja":"癸","branchHanja":"巳"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.559069', '2025-08-27T20:56:25.559074'),
  ('구광모', 'Koo Kwang-mo', '1969-07-06', '12:00', 'M', '서울특별시', '기업인', 'LG그룹', '기유', '경오', '임자', '병오', '기유 경오 임자 병오', 0, 1, 1, 1, 1, '{"year":{"stem":"기","branch":"유","stemHanja":"己","branchHanja":"酉","element":"토"},"month":{"stem":"경","branch":"오","stemHanja":"庚","branchHanja":"午","element":"금"},"day":{"stem":"임","branch":"자","stemHanja":"壬","branchHanja":"子","element":"수"},"hour":{"stem":"병","branch":"오","stemHanja":"丙","branchHanja":"午","element":"화"},"elementBalance":{"목":0,"화":3,"토":1,"금":2,"수":2},"tenGods":{"year":["정관"],"month":["편인"],"hour":["편재"]},"daeunInfo":{"currentAge":56,"startAge":50,"endAge":59,"stem":"을","branch":"해","stemHanja":"乙","branchHanja":"亥"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.559128', '2025-08-27T20:56:25.559132'),
  ('이재명', 'Lee Jae-myung', '1964-12-22', '12:00', 'M', '경기도 안동시', '정치인', '더불어민주당', '갑진', '병자', '을해', '임오', '갑진 병자 을해 임오', 2, 1, 0, 0, 1, '{"year":{"stem":"갑","branch":"진","stemHanja":"甲","branchHanja":"辰","element":"목"},"month":{"stem":"병","branch":"자","stemHanja":"丙","branchHanja":"子","element":"화"},"day":{"stem":"을","branch":"해","stemHanja":"乙","branchHanja":"亥","element":"목"},"hour":{"stem":"임","branch":"오","stemHanja":"壬","branchHanja":"午","element":"수"},"elementBalance":{"목":2,"화":2,"토":1,"금":0,"수":3},"tenGods":{"year":["정인"],"month":["겁재"],"hour":["정관"]},"daeunInfo":{"currentAge":61,"startAge":60,"endAge":69,"stem":"임","branch":"오","stemHanja":"壬","branchHanja":"午"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.559187', '2025-08-27T20:56:25.559191'),
  ('침착맨', 'ChimChakMan', '1995-04-15', '12:00', 'M', '경기도 안산시', '스트리머/유튜버', '샌드박스 네트워크', '을해', '경진', '병오', '갑오', '을해 경진 병오 갑오', 2, 1, 0, 1, 0, '{"year":{"stem":"을","branch":"해","stemHanja":"乙","branchHanja":"亥","element":"목"},"month":{"stem":"경","branch":"진","stemHanja":"庚","branchHanja":"辰","element":"금"},"day":{"stem":"병","branch":"오","stemHanja":"丙","branchHanja":"午","element":"화"},"hour":{"stem":"갑","branch":"오","stemHanja":"甲","branchHanja":"午","element":"목"},"elementBalance":{"목":2,"화":3,"토":1,"금":1,"수":1},"tenGods":{"year":["정인"],"month":["편재"],"hour":["편인"]},"daeunInfo":{"currentAge":30,"startAge":30,"endAge":39,"stem":"계","branch":"미","stemHanja":"癸","branchHanja":"未"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.559245', '2025-08-27T20:56:25.559250'),
  ('손흥민', 'Son Heung-min', '1992-07-08', '12:00', 'M', '강원도 춘천시', '운동선수', '토트넘 홋스퍼', '임신', '정미', '을묘', '임오', '임신 정미 을묘 임오', 1, 1, 0, 0, 2, '{"year":{"stem":"임","branch":"신","stemHanja":"壬","branchHanja":"申","element":"수"},"month":{"stem":"정","branch":"미","stemHanja":"丁","branchHanja":"未","element":"화"},"day":{"stem":"을","branch":"묘","stemHanja":"乙","branchHanja":"卯","element":"목"},"hour":{"stem":"임","branch":"오","stemHanja":"壬","branchHanja":"午","element":"수"},"elementBalance":{"목":2,"화":2,"토":1,"금":1,"수":2},"tenGods":{"year":["정관"],"month":["식신"],"hour":["정관"]},"daeunInfo":{"currentAge":33,"startAge":30,"endAge":39,"stem":"경","branch":"술","stemHanja":"庚","branchHanja":"戌"}}'::jsonb, 'namuwiki_extraction', '2025-08-27T20:56:25.559305', '2025-08-27T20:56:25.559308');
