import '../tarot_metadata.dart';

// Cups (물의 원소 - 감정, 관계, 직관)
class TarotCups {
  static const Map<String, TarotCardInfo> cards = {
    'cups_ace': TarotCardInfo(
      id: 37,
      name: '컵의 에이스 (Ace of Cups)',
      keywords: ['새로운 사랑', '감정적 시작', '직관', '창의성'],
      uprightMeaning: '새로운 관계, 사랑, 정서적 각성, 창의성, 직관',
      reversedMeaning: '감정 억압, 공허함, 실연, 창의성 차단',
      element: '물',
      astrology: '물의 원소',
      numerology: 1,
      imagery: '구름에서 나온 손이 넘치는 성배를 들고 있음',
      advice: '마음을 열고 새로운 감정적 경험을 받아들이세요',
      questions: [
        '어떤 새로운 감정이 당신을 기다리고 있나요?',
        '마음을 어디에 열어야 하나요?']),
    'cups_2': TarotCardInfo(
      id: 38,
      name: '컵의 2 (Two of Cups)',
      keywords: ['파트너십', '연합', '사랑', '조화'],
      uprightMeaning: '통합, 파트너십, 상호 매력, 균형잡힌 관계',
      reversedMeaning: '불균형, 이별, 신뢰 부족, 의사소통 문제',
      element: '물',
      astrology: '게자리의 금성',
      numerology: 2,
      imagery: '두 사람이 컵을 교환하며 서약하는 모습',
      advice: '진정한 파트너십은 상호 존중에서 시작됩니다',
      questions: [
        '어떤 관계가 당신에게 중요한가요?',
        '어떻게 더 깊은 연결을 만들 수 있나요?']),
    'cups_3': TarotCardInfo(
      id: 39,
      name: '컵의 3 (Three of Cups)',
      keywords: ['축하', '우정', '창의성', '공동체'],
      uprightMeaning: '축하, 우정, 창의성, 공동체, 행복한 재회',
      reversedMeaning: '과잉, 험담, 고립, 과도한 파티',
      element: '물',
      astrology: '게자리의 수성',
      numerology: 3,
      imagery: '세 여인이 컵을 들고 축하하는 모습',
      advice: '친구들과 성공을 축하하고 기쁨을 나누세요',
      questions: [
        '누구와 기쁨을 나누고 싶나요?',
        '어떤 성취를 축하해야 하나요?']),
    'cups_4': TarotCardInfo(
      id: 40,
      name: '컵의 4 (Four of Cups)',
      keywords: ['명상', '숙고', '무관심', '재평가'],
      uprightMeaning: '명상, 숙고, 무관심, 놓친 기회',
      reversedMeaning: '새로운 가능성, 동기 부여, 각성, 수용',
      element: '물',
      astrology: '게자리의 달',
      numerology: 4,
      imagery: '나무 아래 앉아 제공된 컵을 거절하는 인물',
      advice: '내면을 들여다보되 새로운 기회도 놓치지 마세요',
      questions: [
        '어떤 기회를 놓치고 있나요?',
        '무엇이 당신을 만족시킬 수 있나요?']),
    'cups_5': TarotCardInfo(
      id: 41,
      name: '컵의 5 (Five of Cups)',
      keywords: ['상실', '슬픔', '실망', '후회'],
      uprightMeaning: '상실, 슬픔, 실망, 후회, 비탄',
      reversedMeaning: '수용, 용서, 회복, 앞으로 나아감',
      element: '물',
      astrology: '전갈자리의 화성',
      numerology: 5,
      imagery: '쏟아진 세 개의 컵을 바라보는 검은 망토의 인물',
      advice: '상실을 애도하되 남은 것에도 감사하세요',
      questions: [
        '무엇을 놓아주어야 하나요?',
        '어떻게 상실을 성장의 기회로 만들 수 있나요?']),
    'cups_6': TarotCardInfo(
      id: 42,
      name: '컵의 6 (Six of Cups)',
      keywords: ['향수', '어린 시절', '순수함', '기쁨'],
      uprightMeaning: '향수, 어린 시절의 기억, 순수함, 기쁨, 과거',
      reversedMeaning: '과거에 갇힘, 미래로 나아감, 성장, 독립',
      element: '물',
      astrology: '전갈자리의 태양',
      numerology: 6,
      imagery: '어린이에게 꽃이 든 컵을 주는 아이',
      advice: '과거의 아름다운 기억을 소중히 하되 현재를 살아가세요',
      questions: [
        '어떤 어린 시절의 기쁨을 되찾을 수 있나요?',
        '과거가 현재에 어떤 영향을 미치고 있나요?']),
    'cups_7': TarotCardInfo(
      id: 43,
      name: '컵의 7 (Seven of Cups)',
      keywords: ['환상', '선택', '일루전', '소망'],
      uprightMeaning: '선택, 환상, 일루전, 소망, 상상력',
      reversedMeaning: '명확성, 선택, 현실 직시, 결단력',
      element: '물',
      astrology: '전갈자리의 금성',
      numerology: 7,
      imagery: '구름 위에 떠 있는 일곱 개의 컵과 다양한 상징물',
      advice: '모든 선택지를 신중히 검토하고 현실적으로 판단하세요',
      questions: [
        '어떤 환상이 당신을 현혹하고 있나요?',
        '진정으로 원하는 것은 무엇인가요?']),
    'cups_8': TarotCardInfo(
      id: 44,
      name: '컵의 8 (Eight of Cups)',
      keywords: ['포기', '탐색', '떠남', '환멸'],
      uprightMeaning: '포기, 실망, 떠남, 더 깊은 의미 탐색',
      reversedMeaning: '방황, 목적 없음, 회피, 포기하기 두려움',
      element: '물',
      astrology: '물고기자리의 토성',
      numerology: 8,
      imagery: '여덟 개의 컵을 뒤로하고 떠나는 인물',
      advice: '때로는 떠나는 것이 성장을 위한 최선의 선택입니다',
      questions: [
        '무엇을 뒤로하고 떠나야 하나요?',
        '더 깊은 의미를 어디서 찾을 수 있나요?']),
    'cups_9': TarotCardInfo(
      id: 45,
      name: '컵의 9 (Nine of Cups)',
      keywords: ['만족', '정서적 충족', '소원 성취', '행복'],
      uprightMeaning: '만족, 정서적 충족, 소원 성취, 행복, 만족감',
      reversedMeaning: '내적 행복, 물질주의, 불만족, 탐욕',
      element: '물',
      astrology: '물고기자리의 목성',
      numerology: 9,
      imagery: '아홉 개의 컵 앞에 만족스럽게 앉아 있는 인물',
      advice: '당신의 소원이 이루어질 때입니다. 감사하세요',
      questions: [
        '무엇이 당신을 진정으로 행복하게 하나요?',
        '어떤 소원이 이루어졌나요?']),
    'cups_10': TarotCardInfo(
      id: 46,
      name: '컵의 10 (Ten of Cups)',
      keywords: ['행복', '가족', '조화', '정서적 충족'],
      uprightMeaning: '행복한 가정, 조화, 정서적 충족, 사랑의 완성',
      reversedMeaning: '가정 불화, 가치관 충돌, 비현실적 기대',
      element: '물',
      astrology: '물고기자리의 화성',
      numerology: 10,
      imagery: '무지개 아래 행복한 가족',
      advice: '사랑하는 사람들과의 관계를 소중히 여기세요',
      questions: [
        '진정한 행복은 어디에서 오나요?',
        '어떻게 더 조화로운 관계를 만들 수 있나요?']),
    'cups_page': TarotCardInfo(
      id: 47,
      name: '컵의 페이지 (Page of Cups)',
      keywords: ['창의적 시작', '직관', '감수성', '새로운 감정'],
      uprightMeaning: '창의적 기회, 직관적 메시지, 새로운 감정, 예술적 영감',
      reversedMeaning: '감정적 미성숙, 현실 도피, 창의성 차단',
      element: '물',
      astrology: '물의 땅',
      numerology: 11,
      imagery: '컵에서 나온 물고기를 바라보는 젊은이',
      advice: '직관을 신뢰하고 창의적인 영감을 따르세요',
      questions: [
        '어떤 창의적 메시지가 당신에게 오고 있나요?',
        '직관이 무엇을 말하고 있나요?']),
    'cups_knight': TarotCardInfo(
      id: 48,
      name: '컵의 기사 (Knight of Cups)',
      keywords: ['로맨스', '매력', '상상력', '예술'],
      uprightMeaning: '로맨틱한 제안, 창의성, 매력, 예술적 추구',
      reversedMeaning: '감정적 조작, 비현실적, 질투, 변덕스러움',
      element: '물',
      astrology: '물의 불',
      numerology: 12,
      imagery: '컵을 들고 천천히 전진하는 기사',
      advice: '마음의 소리를 따르되 현실도 잊지 마세요',
      questions: [
        '어떤 로맨틱한 기회가 다가오고 있나요?',
        '감정과 행동의 균형을 어떻게 맞출 수 있나요?']),
    'cups_queen': TarotCardInfo(
      id: 49,
      name: '컵의 여왕 (Queen of Cups)',
      keywords: ['동정심', '침착함', '직관', '감정적 성숙'],
      uprightMeaning: '동정심, 배려, 감정적 안정, 직관력, 성숙함',
      reversedMeaning: '감정적 불안정, 의존성, 자기 돌봄 부족',
      element: '물',
      astrology: '물의 물',
      numerology: 13,
      imagery: '정교한 컵을 들고 물가의 왕좌에 앉은 여왕',
      advice: '직관을 신뢰하고 타인에게 동정심을 보이세요',
      questions: [
        '어떻게 더 감정적으로 성숙해질 수 있나요?',
        '누가 당신의 동정심을 필요로 하나요?']),
    'cups_king': TarotCardInfo(
      id: 50,
      name: '컵의 왕 (King of Cups)',
      keywords: ['감정적 균형', '외교', '관대함', '가족'],
      uprightMeaning: '감정적 균형, 관대함, 외교술, 가족 중심',
      reversedMeaning: '감정적 조작, 변덕스러움, 냉담함, 억압된 감정',
      element: '물',
      astrology: '물의 공기',
      numerology: 14,
      imagery: '파도 위 왕좌에 앉아 컵과 홀을 든 왕',
      advice: '감정을 현명하게 다스리고 균형을 유지하세요',
      questions: [
        '어떻게 감정과 이성의 균형을 맞출 수 있나요?',
        '당신의 감정적 지혜를 어떻게 활용할 수 있나요?']),
  };

  // Swords (공기의 원소 - 생각, 소통, 갈등)
}
