import '../tarot_metadata.dart';

// Pentacles (땅의 원소 - 물질, 실용성, 안정)
class TarotPentacles {
  static const Map<String, TarotCardInfo> cards = {
    'pentacles_ace': TarotCardInfo(
        id: 65,
        name: '펜타클의 에이스 (Ace of Pentacles)',
        keywords: ['새로운 기회', '번영', '물질적 시작', '잠재력'],
        uprightMeaning: '새로운 재정적 기회, 번영, 안정성, 건강',
        reversedMeaning: '기회 상실, 계획 부족, 탐욕, 물질주의',
        element: '땅',
        astrology: '땅의 원소',
        numerology: 1,
        imagery: '구름에서 나온 손이 황금 동전을 들고 있음',
        advice: '새로운 물질적 기회를 현명하게 활용하세요',
        questions: ['어떤 새로운 기회가 당신을 기다리고 있나요?', '안정성을 어떻게 구축할 수 있나요?']),
    'pentacles_2': TarotCardInfo(
        id: 66,
        name: '펜타클의 2 (Two of Pentacles)',
        keywords: ['균형', '적응력', '시간 관리', '우선순위'],
        uprightMeaning: '균형, 적응력, 시간 관리, 다중 작업',
        reversedMeaning: '압도됨, 조직 부재, 재정 스트레스',
        element: '땅',
        astrology: '염소자리의 목성',
        numerology: 2,
        imagery: '두 개의 동전을 저글링하는 인물',
        advice: '삶의 다양한 요구사항들 사이에서 균형을 찾으세요',
        questions: ['어떻게 더 나은 균형을 찾을 수 있나요?', '우선순위를 어떻게 정해야 하나요?']),
    'pentacles_3': TarotCardInfo(
        id: 67,
        name: '펜타클의 3 (Three of Pentacles)',
        keywords: ['팀워크', '협력', '기술', '계획'],
        uprightMeaning: '팀워크, 협력, 기술 학습, 품질',
        reversedMeaning: '팀워크 부족, 무관심, 품질 저하',
        element: '땅',
        astrology: '염소자리의 화성',
        numerology: 3,
        imagery: '대성당에서 일하는 장인과 건축가들',
        advice: '다른 사람들과 협력하여 더 큰 것을 만드세요',
        questions: ['누구와 협력해야 하나요?', '어떤 기술을 개발해야 하나요?']),
    'pentacles_4': TarotCardInfo(
        id: 68,
        name: '펜타클의 4 (Four of Pentacles)',
        keywords: ['안정성', '보수성', '소유욕', '통제'],
        uprightMeaning: '재정 안정, 보수성, 저축, 통제',
        reversedMeaning: '탐욕, 물질주의, 자기 보호, 인색함',
        element: '땅',
        astrology: '염소자리의 태양',
        numerology: 4,
        imagery: '네 개의 동전을 꽉 쥐고 있는 인물',
        advice: '안정성은 좋지만 너무 경직되지 마세요',
        questions: ['무엇을 놓아주기 두려워하나요?', '안정성과 유연성의 균형을 어떻게 맞출 수 있나요?']),
    'pentacles_5': TarotCardInfo(
        id: 69,
        name: '펜타클의 5 (Five of Pentacles)',
        keywords: ['재정적 손실', '빈곤', '고립', '불안감'],
        uprightMeaning: '재정적 손실, 빈곤, 고립, 건강 문제',
        reversedMeaning: '회복, 영적 부, 극복, 도움 수락',
        element: '땅',
        astrology: '황소자리의 수성',
        numerology: 5,
        imagery: '눈 속에서 교회를 지나가는 두 거지',
        advice: '도움이 필요할 때는 요청하는 것을 두려워하지 마세요',
        questions: ['어떤 도움을 받을 수 있나요?', '물질적 손실에서 무엇을 배울 수 있나요?']),
    'pentacles_6': TarotCardInfo(
        id: 70,
        name: '펜타클의 6 (Six of Pentacles)',
        keywords: ['관대함', '자선', '공유', '공정함'],
        uprightMeaning: '관대함, 자선, 공유, 재정적 균형',
        reversedMeaning: '이기심, 빚, 불공정, 권력 남용',
        element: '땅',
        astrology: '황소자리의 달',
        numerology: 6,
        imagery: '가난한 사람들에게 동전을 나누어주는 상인',
        advice: '나눔은 받는 것만큼 중요합니다',
        questions: ['어떻게 더 관대해질 수 있나요?', '주고받음의 균형이 맞나요?']),
    'pentacles_7': TarotCardInfo(
        id: 71,
        name: '펜타클의 7 (Seven of Pentacles)',
        keywords: ['인내', '투자', '장기적 보상', '평가'],
        uprightMeaning: '인내, 투자, 장기적 보상, 지속 가능한 결과',
        reversedMeaning: '조급함, 투자 부족, 보상 없음, 좌절',
        element: '땅',
        astrology: '황소자리의 토성',
        numerology: 7,
        imagery: '자란 펜타클을 바라보며 쉬는 농부',
        advice: '인내심을 갖고 노력의 결실을 기다리세요',
        questions: ['어떤 투자가 결실을 맺고 있나요?', '장기적 목표를 위해 무엇을 해야 하나요?']),
    'pentacles_8': TarotCardInfo(
        id: 72,
        name: '펜타클의 8 (Eight of Pentacles)',
        keywords: ['기술 연마', '헌신', '세부사항', '장인정신'],
        uprightMeaning: '기술 연마, 헌신, 품질에 대한 집중, 교육',
        reversedMeaning: '완벽주의, 기술 부족, 의미 없는 일',
        element: '땅',
        astrology: '처녀자리의 태양',
        numerology: 8,
        imagery: '펜타클을 조각하는 장인',
        advice: '꾸준한 연습과 헌신이 전문성을 만듭니다',
        questions: ['어떤 기술을 완벽하게 만들고 싶나요?', '세부사항에 충분히 주의를 기울이고 있나요?']),
    'pentacles_9': TarotCardInfo(
        id: 73,
        name: '펜타클의 9 (Nine of Pentacles)',
        keywords: ['풍요', '독립', '자급자족', '성취'],
        uprightMeaning: '재정적 독립, 풍요, 자급자족, 품격',
        reversedMeaning: '과시, 과로, 재정적 후퇴, 외로움',
        element: '땅',
        astrology: '처녀자리의 금성',
        numerology: 9,
        imagery: '포도원에서 매를 든 우아한 여인',
        advice: '당신의 성취와 독립성을 즐기세요',
        questions: ['어떤 성취를 축하해야 하나요?', '독립성을 어떻게 유지할 수 있나요?']),
    'pentacles_10': TarotCardInfo(
        id: 74,
        name: '펜타클의 10 (Ten of Pentacles)',
        keywords: ['유산', '가족 재산', '전통', '장기적 성공'],
        uprightMeaning: '재정적 안정, 가족 유산, 장기적 성공, 전통',
        reversedMeaning: '재정적 실패, 가족 분쟁, 전통 거부',
        element: '땅',
        astrology: '처녀자리의 수성',
        numerology: 10,
        imagery: '가족과 개들이 있는 풍요로운 저택',
        advice: '미래 세대를 위한 유산을 만드세요',
        questions: ['어떤 유산을 남기고 싶나요?', '장기적인 안정을 어떻게 구축할 수 있나요?']),
    'pentacles_page': TarotCardInfo(
        id: 75,
        name: '펜타클의 페이지 (Page of Pentacles)',
        keywords: ['새로운 벤처', '기술 학습', '야망', '실용적 기회'],
        uprightMeaning: '새로운 재정적 기회, 기술 학습, 야망, 목표 설정',
        reversedMeaning: '진전 부족, 미루기, 기회 부족, 재능 낭비',
        element: '땅',
        astrology: '땅의 땅',
        numerology: 11,
        imagery: '펜타클을 들고 서 있는 젊은이',
        advice: '실용적인 목표를 설정하고 꾸준히 노력하세요',
        questions: ['어떤 새로운 기술을 배우고 싶나요?', '실용적인 목표는 무엇인가요?']),
    'pentacles_knight': TarotCardInfo(
        id: 76,
        name: '펜타클의 기사 (Knight of Pentacles)',
        keywords: ['인내', '루틴', '보수성', '노력'],
        uprightMeaning: '노력, 루틴, 보수적 접근, 책임감',
        reversedMeaning: '정체, 완벽주의, 지루함, 리스크 회피',
        element: '땅',
        astrology: '땅의 불',
        numerology: 12,
        imagery: '검은 말을 탄 신중한 기사',
        advice: '느리고 꾸준한 것이 경주에서 이깁니다',
        questions: ['어디에 더 많은 인내가 필요한가요?', '일상을 어떻게 개선할 수 있나요?']),
    'pentacles_queen': TarotCardInfo(
        id: 77,
        name: '펜타클의 여왕 (Queen of Pentacles)',
        keywords: ['양육', '실용적', '풍요로운 어머니', '자연'],
        uprightMeaning: '양육, 실용적 지혜, 재정 안정, 관대함',
        reversedMeaning: '자기 관리 부족, 의존성, 일과 삶의 불균형',
        element: '땅',
        astrology: '땅의 물',
        numerology: 13,
        imagery: '자연 속 왕좌에 앉은 풍요로운 여왕',
        advice: '실용적인 지혜로 자신과 타인을 돌보세요',
        questions: ['어떻게 더 나은 양육자가 될 수 있나요?', '물질적 풍요를 어떻게 나눌 수 있나요?']),
    'pentacles_king': TarotCardInfo(
        id: 78,
        name: '펜타클의 왕 (King of Pentacles)',
        keywords: ['재정적 성공', '사업', '리더십', '안정성'],
        uprightMeaning: '재정적 성공, 사업 감각, 안정성, 관대한 리더',
        reversedMeaning: '탐욕, 물질주의, 경직성, 지위 집착',
        element: '땅',
        astrology: '땅의 공기',
        numerology: 14,
        imagery: '풍요로운 정원의 왕좌에 앉은 왕',
        advice: '물질적 성공을 현명하고 관대하게 사용하세요',
        questions: ['어떻게 더 나은 리더가 될 수 있나요?', '성공을 어떻게 다른 사람들과 나눌 수 있나요?']),
  };

  // 전체 Minor Arcana 카드 목록 생성
}
