import '../tarot_metadata.dart';

// Swords (공기의 원소 - 지성, 소통, 진실)
class TarotSwords {
  static const Map<String, TarotCardInfo> cards = {
    'swords_ace': TarotCardInfo(
        id: 51,
        name: '소드의 에이스 (Ace of Swords)',
        keywords: ['새로운 아이디어', '정신적 명료함', '돌파구', '진실'],
        uprightMeaning: '정신적 명료함, 돌파구, 새로운 아이디어, 진실, 정의',
        reversedMeaning: '혼란, 잘못된 정보, 정신적 차단, 불공정',
        element: '공기',
        astrology: '공기의 원소',
        numerology: 1,
        imagery: '구름에서 나온 손이 왕관을 쓴 검을 들고 있음',
        advice: '명료한 사고로 진실을 추구하세요',
        questions: ['어떤 진실이 드러나고 있나요?', '어디에 정신적 명료함이 필요한가요?']),
    'swords_2': TarotCardInfo(
        id: 52,
        name: '소드의 2 (Two of Swords)',
        keywords: ['어려운 결정', '교착 상태', '회피', '균형'],
        uprightMeaning: '어려운 결정, 교착 상태, 균형 유지, 중립',
        reversedMeaning: '우유부단, 정보 과다, 결정 지연, 혼란',
        element: '공기',
        astrology: '천칭자리의 달',
        numerology: 2,
        imagery: '눈을 가리고 두 검을 교차시킨 여인',
        advice: '직관과 논리를 모두 사용하여 결정하세요',
        questions: ['어떤 결정을 피하고 있나요?', '양쪽 의견을 어떻게 조화시킬 수 있나요?']),
    'swords_3': TarotCardInfo(
        id: 53,
        name: '소드의 3 (Three of Swords)',
        keywords: ['가슴 아픔', '슬픔', '상실', '배신'],
        uprightMeaning: '가슴 아픔, 슬픔, 상실, 배신, 고통스러운 진실',
        reversedMeaning: '회복, 용서, 상처 치유, 낙관주의',
        element: '공기',
        astrology: '천칭자리의 토성',
        numerology: 3,
        imagery: '세 개의 검이 꽂힌 심장과 비구름',
        advice: '고통을 인정하고 치유의 과정을 시작하세요',
        questions: ['어떤 상처가 치유되어야 하나요?', '고통에서 무엇을 배울 수 있나요?']),
    'swords_4': TarotCardInfo(
        id: 54,
        name: '소드의 4 (Four of Swords)',
        keywords: ['휴식', '회복', '명상', '준비'],
        uprightMeaning: '휴식, 회복, 명상, 정신적 준비, 평화',
        reversedMeaning: '불안, 번아웃, 정체, 회복 부족',
        element: '공기',
        astrology: '천칭자리의 목성',
        numerology: 4,
        imagery: '무덤 위에 누워 있는 기사와 걸린 세 개의 검',
        advice: '행동하기 전에 충분한 휴식과 성찰의 시간을 가지세요',
        questions: ['어디에서 휴식을 찾을 수 있나요?', '다음 단계를 위해 어떻게 준비할 수 있나요?']),
    'swords_5': TarotCardInfo(
        id: 55,
        name: '소드의 5 (Five of Swords)',
        keywords: ['갈등', '패배', '굴욕', '이기심'],
        uprightMeaning: '갈등, 불명예스러운 승리, 패배, 굴욕',
        reversedMeaning: '화해, 과거 청산, 용서, 패배 수용',
        element: '공기',
        astrology: '물병자리의 금성',
        numerology: 5,
        imagery: '검을 모으는 인물과 물러나는 패배자들',
        advice: '모든 전투가 싸울 가치가 있는 것은 아닙니다',
        questions: ['이기는 것이 정말 중요한가요?', '어떤 갈등을 놓아주어야 하나요?']),
    'swords_6': TarotCardInfo(
        id: 56,
        name: '소드의 6 (Six of Swords)',
        keywords: ['전환', '이동', '회복', '여행'],
        uprightMeaning: '전환, 이동, 회복의 여정, 평화로운 변화',
        reversedMeaning: '저항, 전환 지연, 미해결 문제, 정체',
        element: '공기',
        astrology: '물병자리의 수성',
        numerology: 6,
        imagery: '배를 타고 잔잔한 물을 건너는 가족',
        advice: '어려운 시기를 뒤로하고 앞으로 나아가세요',
        questions: ['어떤 전환이 필요한가요?', '더 나은 곳으로 어떻게 이동할 수 있나요?']),
    'swords_7': TarotCardInfo(
        id: 57,
        name: '소드의 7 (Seven of Swords)',
        keywords: ['기만', '전략', '은밀함', '고립'],
        uprightMeaning: '기만, 배신, 은밀한 행동, 전략적 사고',
        reversedMeaning: '고백, 진실 드러남, 책임 수용, 반성',
        element: '공기',
        astrology: '물병자리의 달',
        numerology: 7,
        imagery: '다섯 개의 검을 훔쳐 도망가는 인물',
        advice: '정직이 최선의 정책임을 기억하세요',
        questions: ['무엇을 숨기고 있나요?', '어떤 전략이 필요한가요?']),
    'swords_8': TarotCardInfo(
        id: 58,
        name: '소드의 8 (Eight of Swords)',
        keywords: ['제한', '포로', '무력감', '자기 제한'],
        uprightMeaning: '제한, 포로 상태, 무력감, 피해자 의식',
        reversedMeaning: '자유, 새로운 관점, 제한 극복, 권한 부여',
        element: '공기',
        astrology: '쌍둥이자리의 목성',
        numerology: 8,
        imagery: '눈을 가리고 검에 둘러싸여 묶인 여인',
        advice: '제한은 종종 우리 마음속에만 존재합니다',
        questions: ['어떤 제한이 실제이고 어떤 것이 상상인가요?', '어떻게 자유를 찾을 수 있나요?']),
    'swords_9': TarotCardInfo(
        id: 59,
        name: '소드의 9 (Nine of Swords)',
        keywords: ['불안', '악몽', '두려움', '절망'],
        uprightMeaning: '불안, 악몽, 두려움, 정신적 고통, 죄책감',
        reversedMeaning: '희망, 극복, 도움 요청, 회복의 시작',
        element: '공기',
        astrology: '쌍둥이자리의 화성',
        numerology: 9,
        imagery: '침대에서 머리를 감싸고 있는 인물과 벽의 검들',
        advice: '두려움은 종종 현실보다 더 나쁩니다',
        questions: ['무엇이 당신을 밤에 깨우나요?', '두려움을 어떻게 극복할 수 있나요?']),
    'swords_10': TarotCardInfo(
        id: 60,
        name: '소드의 10 (Ten of Swords)',
        keywords: ['배신', '끝', '고통스러운 종료', '바닥'],
        uprightMeaning: '고통스러운 끝, 배신, 바닥, 피할 수 없는 종료',
        reversedMeaning: '회복, 재생, 최악은 지났음, 새로운 시작',
        element: '공기',
        astrology: '쌍둥이자리의 태양',
        numerology: 10,
        imagery: '열 개의 검이 꽂힌 채 쓰러진 인물',
        advice: '끝은 새로운 시작의 전조입니다',
        questions: ['무엇이 끝나야 하나요?', '어떻게 다시 일어설 수 있나요?']),
    'swords_page': TarotCardInfo(
        id: 61,
        name: '소드의 페이지 (Page of Swords)',
        keywords: ['호기심', '새로운 아이디어', '경계', '진실 추구'],
        uprightMeaning: '호기심, 새로운 아이디어, 경계심, 정신적 에너지',
        reversedMeaning: '험담, 모든 말 믿기, 정신 산란, 과도한 경계',
        element: '공기',
        astrology: '공기의 땅',
        numerology: 11,
        imagery: '바람 부는 언덕에서 검을 든 젊은이',
        advice: '호기심을 가지되 신중하게 행동하세요',
        questions: ['무엇을 더 알고 싶나요?', '어떤 새로운 아이디어가 떠오르나요?']),
    'swords_knight': TarotCardInfo(
        id: 62,
        name: '소드의 기사 (Knight of Swords)',
        keywords: ['빠른 행동', '야심', '용기', '충돌'],
        uprightMeaning: '빠른 행동, 야심, 용기, 정직, 권위에 도전',
        reversedMeaning: '무모함, 조급함, 공격적, 무신경함',
        element: '공기',
        astrology: '공기의 불',
        numerology: 12,
        imagery: '질풍처럼 돌진하는 기사',
        advice: '용기는 좋지만 무모함과는 다릅니다',
        questions: ['어디로 돌진하고 있나요?', '속도와 신중함의 균형을 어떻게 맞출 수 있나요?']),
    'swords_queen': TarotCardInfo(
        id: 63,
        name: '소드의 여왕 (Queen of Swords)',
        keywords: ['명확한 소통', '독립성', '지각력', '직설적'],
        uprightMeaning: '명확한 소통, 독립성, 공정함, 지각력, 경계 설정',
        reversedMeaning: '차가움, 잔인함, 비관적, 소통 부족',
        element: '공기',
        astrology: '공기의 물',
        numerology: 13,
        imagery: '구름 속 왕좌에 검을 든 여왕',
        advice: '진실을 말하되 친절함도 잊지 마세요',
        questions: ['어디에 명확한 경계가 필요한가요?', '진실을 어떻게 친절하게 전달할 수 있나요?']),
    'swords_king': TarotCardInfo(
        id: 64,
        name: '소드의 왕 (King of Swords)',
        keywords: ['지적 권력', '진실', '권위', '판단력'],
        uprightMeaning: '지적 권력, 명확한 사고, 진실, 권위, 공정함',
        reversedMeaning: '권력 남용, 조작, 냉담함, 비윤리적',
        element: '공기',
        astrology: '공기의 공기',
        numerology: 14,
        imagery: '검을 든 채 엄격하게 앉아 있는 왕',
        advice: '지혜와 공정함으로 판단하세요',
        questions: ['어디에 명확한 판단이 필요한가요?', '권위를 어떻게 현명하게 사용할 수 있나요?']),
  };

  // Pentacles (땅의 원소 - 물질, 건강, 일)
}
