import '../tarot_metadata.dart';

// Wands (불의 원소 - 열정, 창의성, 행동)
class TarotWands {
  static const Map<String, TarotCardInfo> cards = {
    'wands_ace': TarotCardInfo(
      id: 23,
      name: '완드의 에이스 (Ace of Wands)',
      keywords: ['새로운 시작', '영감', '성장', '잠재력'],
      uprightMeaning: '창의적인 시작, 새로운 기회, 열정의 불꽃, 영감',
      reversedMeaning: '지연된 프로젝트, 창의성 부족, 무기력, 좌절',
      element: '불',
      astrology: '불의 원소',
      numerology: 1,
      imagery: '구름에서 나온 손이 잎이 돋은 지팡이를 들고 있음',
      advice: '새로운 창의적 프로젝트를 시작할 완벽한 시기입니다',
      questions: [
        '어떤 새로운 열정이 당신을 기다리고 있나요?',
        '당신의 창의적 에너지를 어디에 집중할 것인가요?']),
    'wands_2': TarotCardInfo(
      id: 24,
      name: '완드의 2 (Two of Wands)',
      keywords: ['계획', '진전', '결정', '잠재력'],
      uprightMeaning: '미래 계획, 장기적 목표, 개인적 힘, 영향력',
      reversedMeaning: '계획 부족, 두려움, 나쁜 계획, 예상치 못한 일',
      element: '불',
      astrology: '양자리의 화성',
      numerology: 2,
      imagery: '두 개의 지팡이를 들고 세계를 내려다보는 인물',
      advice: '큰 그림을 보고 장기적인 계획을 세우세요',
      questions: [
        '당신의 장기적인 목표는 무엇인가요?',
        '어떤 선택이 더 나은 미래로 이끌까요?']),
    'wands_3': TarotCardInfo(
      id: 25,
      name: '완드의 3 (Three of Wands)',
      keywords: ['확장', '예견', '장기 계획', '진보'],
      uprightMeaning: '확장, 해외 기회, 장기적 성공, 비전의 실현',
      reversedMeaning: '좌절, 지연, 제한된 시야, 실망',
      element: '불',
      astrology: '양자리의 태양',
      numerology: 3,
      imagery: '세 개의 지팡이와 함께 바다를 바라보는 인물',
      advice: '당신의 노력이 결실을 맺기 시작합니다',
      questions: [
        '어떤 기회가 지평선 너머에 있나요?',
        '당신의 비전을 어떻게 확장할 수 있나요?']),
    'wands_4': TarotCardInfo(
      id: 26,
      name: '완드의 4 (Four of Wands)',
      keywords: ['축하', '조화', '결혼', '행복한 가정'],
      uprightMeaning: '축하, 행복한 재회, 안정감, 성취의 기쁨',
      reversedMeaning: '불안정, 전환기, 가정 불화, 축하의 부재',
      element: '불',
      astrology: '양자리의 금성',
      numerology: 4,
      imagery: '꽃으로 장식된 네 개의 지팡이, 축하하는 사람들',
      advice: '성취를 축하하고 사랑하는 사람들과 시간을 보내세요',
      questions: [
        '무엇을 축하해야 하나요?',
        '어떻게 더 안정적인 기반을 만들 수 있나요?']),
    'wands_5': TarotCardInfo(
      id: 27,
      name: '완드의 5 (Five of Wands)',
      keywords: ['갈등', '경쟁', '긴장', '의견 충돌'],
      uprightMeaning: '갈등, 경쟁, 의견 차이, 도전적인 상황',
      reversedMeaning: '갈등 해결, 내적 갈등, 긴장 완화, 타협',
      element: '불',
      astrology: '사자자리의 토성',
      numerology: 5,
      imagery: '다섯 명이 지팡이를 들고 싸우는 모습',
      advice: '건설적인 방법으로 갈등을 해결하세요',
      questions: [
        '어떤 갈등이 성장의 기회가 될 수 있나요?',
        '경쟁이 당신을 어떻게 발전시키고 있나요?']),
    'wands_6': TarotCardInfo(
      id: 28,
      name: '완드의 6 (Six of Wands)',
      keywords: ['승리', '공적 인정', '진전', '자신감'],
      uprightMeaning: '승리, 공적 인정, 자부심, 성공',
      reversedMeaning: '개인적 성취, 인정 부족, 자만, 목표 달성 실패',
      element: '불',
      astrology: '사자자리의 목성',
      numerology: 6,
      imagery: '월계관을 쓰고 말을 탄 승리자',
      advice: '자신의 성취를 자랑스러워하되 겸손을 잃지 마세요',
      questions: [
        '어떤 성공을 축하해야 하나요?',
        '인정받기 위해 무엇을 해야 하나요?']),
    'wands_7': TarotCardInfo(
      id: 29,
      name: '완드의 7 (Seven of Wands)',
      keywords: ['방어', '인내', '도전', '경쟁'],
      uprightMeaning: '자신의 입장 고수, 도전에 맞서기, 인내, 용기',
      reversedMeaning: '압도됨, 포기, 자신감 상실, 타협',
      element: '불',
      astrology: '사자자리의 화성',
      numerology: 7,
      imagery: '언덕 위에서 지팡이로 방어하는 인물',
      advice: '자신의 신념을 지키되 유연성도 가지세요',
      questions: [
        '무엇을 지켜야 하나요?',
        '어떤 도전이 당신을 더 강하게 만들고 있나요?']),
    'wands_8': TarotCardInfo(
      id: 30,
      name: '완드의 8 (Eight of Wands)',
      keywords: ['신속한 행동', '움직임', '빠른 결정', '뉴스'],
      uprightMeaning: '빠른 진전, 좋은 소식, 여행, 급속한 변화',
      reversedMeaning: '지연, 좌절, 인내 필요, 나쁜 타이밍',
      element: '불',
      astrology: '사수자리의 수성',
      numerology: 8,
      imagery: '하늘을 가로질러 날아가는 여덟 개의 지팡이',
      advice: '기회가 왔을 때 빠르게 행동하세요',
      questions: [
        '어떤 일이 빠르게 진행되고 있나요?',
        '기다리던 소식이 무엇인가요?']),
    'wands_9': TarotCardInfo(
      id: 31,
      name: '완드의 9 (Nine of Wands)',
      keywords: ['인내', '용기', '경계', '시험'],
      uprightMeaning: '마지막 도전, 인내, 경계심, 회복력',
      reversedMeaning: '편집증, 방어적, 포기 직전, 고집',
      element: '불',
      astrology: '사수자리의 달',
      numerology: 9,
      imagery: '부상당했지만 경계하며 서 있는 인물',
      advice: '조금만 더 버티면 목표에 도달할 수 있습니다',
      questions: [
        '무엇이 당신을 계속 나아가게 하나요?',
        '어떤 교훈을 배웠나요?']),
    'wands_10': TarotCardInfo(
      id: 32,
      name: '완드의 10 (Ten of Wands)',
      keywords: ['부담', '책임', '노력', '스트레스'],
      uprightMeaning: '과도한 부담, 책임감, 열심히 일함, 스트레스',
      reversedMeaning: '부담 해소, 위임, 포기, 책임 회피',
      element: '불',
      astrology: '사수자리의 토성',
      numerology: 10,
      imagery: '열 개의 지팡이를 힘겹게 운반하는 인물',
      advice: '도움을 요청하고 부담을 나누세요',
      questions: [
        '어떤 부담을 내려놓아야 하나요?',
        '책임을 어떻게 분담할 수 있나요?']),
    'wands_page': TarotCardInfo(
      id: 33,
      name: '완드의 페이지 (Page of Wands)',
      keywords: ['열정', '모험', '자유로운 영혼', '발견'],
      uprightMeaning: '새로운 아이디어, 열정적인 시작, 창의적 메시지, 모험',
      reversedMeaning: '나쁜 소식, 미성숙, 계획 부족, 무모함',
      element: '불',
      astrology: '불의 땅',
      numerology: 11,
      imagery: '지팡이를 들고 사막에 서 있는 젊은이',
      advice: '열정을 가지고 새로운 모험을 시작하세요',
      questions: [
        '어떤 새로운 열정이 당신을 부르고 있나요?',
        '창의적인 에너지를 어디에 쏟을 것인가요?']),
    'wands_knight': TarotCardInfo(
      id: 34,
      name: '완드의 기사 (Knight of Wands)',
      keywords: ['에너지', '열정', '모험', '충동'],
      uprightMeaning: '모험, 에너지, 열정, 충동적 행동, 여행',
      reversedMeaning: '무모함, 조급함, 좌절, 지연, 분노',
      element: '불',
      astrology: '불의 불',
      numerology: 12,
      imagery: '불타는 지팡이를 들고 질주하는 기사',
      advice: '열정은 좋지만 신중함도 필요합니다',
      questions: [
        '어디로 모험을 떠나고 싶나요?',
        '충동을 어떻게 건설적으로 활용할 수 있나요?']),
    'wands_queen': TarotCardInfo(
      id: 35,
      name: '완드의 여왕 (Queen of Wands)',
      keywords: ['자신감', '용기', '결단력', '독립'],
      uprightMeaning: '자신감, 용기, 결단력, 독립적, 카리스마',
      reversedMeaning: '이기심, 질투, 불안정, 악의적, 까다로움',
      element: '불',
      astrology: '불의 물',
      numerology: 13,
      imagery: '해바라기와 검은 고양이가 있는 왕좌의 여왕',
      advice: '자신감을 가지고 리더십을 발휘하세요',
      questions: [
        '어떻게 더 자신감 있게 행동할 수 있나요?',
        '당신의 열정을 어떻게 다른 사람들에게 전달할 수 있나요?']),
    'wands_king': TarotCardInfo(
      id: 36,
      name: '완드의 왕 (King of Wands)',
      keywords: ['리더십', '비전', '기업가 정신', '카리스마'],
      uprightMeaning: '자연스러운 리더, 비전, 기업가 정신, 명예',
      reversedMeaning: '충동적, 무자비함, 높은 기대, 독재적',
      element: '불',
      astrology: '불의 공기',
      numerology: 14,
      imagery: '사자와 도롱뇽이 장식된 왕좌의 왕',
      advice: '비전을 가지고 다른 사람들을 이끄세요',
      questions: [
        '당신의 비전은 무엇인가요?',
        '어떻게 더 나은 리더가 될 수 있나요?']),
  };

  // Cups (물의 원소 - 감정, 직관, 관계)
}
