class FortuneKeyLocalizer {
  const FortuneKeyLocalizer._();

  static String labelFor(String key) {
    final trimmed = key.trim();
    if (trimmed.isEmpty) {
      return '';
    }

    final normalized = normalize(trimmed);
    return _normalizedLabels[normalized] ?? _humanize(trimmed);
  }

  static String normalize(String key) {
    return key
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (match) => '${match.group(1)} ${match.group(2)}',
        )
        .replaceAll('_', ' ')
        .replaceAll('-', ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim()
        .toLowerCase();
  }

  static String _humanize(String key) {
    return key
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (match) => '${match.group(1)} ${match.group(2)}',
        )
        .replaceAll('_', ' ')
        .replaceAll('-', ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  static const Map<String, String> _normalizedLabels = {
    'love': '연애운',
    'money': '재물운',
    'wealth': '재물운',
    'finance': '금전운',
    'health': '건강운',
    'work': '일과운',
    'career': '커리어운',
    'study': '학업운',
    'relationship': '관계운',
    'social': '대화운',
    'family': '가족운',
    'luck': '행운',
    'overall': '종합운',
    'total': '종합운',
    'score': '점수',
    'number': '행운 숫자',
    'color': '행운 색상',
    'color hex': '컬러 코드',
    'time': '행운 시간',
    'direction': '행운 방향',
    'item': '행운 아이템',
    'place': '행운 장소',
    'food': '행운 음식',
    'drink': '행운 음료',
    'music': '행운 음악',
    'animal': '행운 동물',
    'flower': '행운 꽃',
    'emoji': '시그널',
    'lucky number': '행운 숫자',
    'lucky color': '행운 색상',
    'lucky color hex': '컬러 코드',
    'lucky time': '행운 시간',
    'lucky direction': '행운 방향',
    'lucky item': '행운 아이템',
    'lucky place': '행운 장소',
    'lucky items': '행운 아이템',
    'lucky food': '행운 음식',
    'lucky drink': '행운 음료',
    'lucky music': '행운 음악',
    'lucky animal': '행운 동물',
    'lucky flower': '행운 꽃',
    'year element': '연간 오행',
    'dominant element': '주된 오행',
    'weak element': '부족한 오행',
    'wealth element': '재물 오행',
    'balance elements': '균형 오행',
    'elemental advice': '오행 조언',
    'strengthen tips': '보완 팁',
    'compatibility': '궁합',
    'compatibility reason': '궁합 해설',
    'goal fortune': '목표 운세',
    'goal label': '핵심 목표',
    'deep analysis': '깊은 분석',
    'prediction': '예측',
    'best months': '좋은 달',
    'caution months': '조심할 달',
    'action items': '실행 포인트',
    'monthly highlights': '월별 하이라이트',
    'action plan': '실천 계획',
    'saju analysis': '사주 흐름',
    'saju insight': '사주 인사이트',
    'fortune summary': '운세 요약',
    'godlife': '갓생 부스트',
    'immediate': '바로 시작',
    'short term': '1~3개월',
    'long term': '6~12개월',
    'best time': '좋은 시간',
    'worst time': '조심할 시간',
    'time slots': '시간대별 흐름',
    'time specific fortunes': '시간대 운세',
    'personal actions': '실천 액션',
    'calendar advice': '일정 인사이트',
    'calendar events': '일정',
    'day theme': '오늘의 테마',
    'special message': '특별 메시지',
    'special tip': '특별 팁',
    'goal advice': '목표 달성 전략',
    'cashflow insight': '현금 흐름 인사이트',
    'concern resolution': '고민 해결',
    'investment insights': '투자 인사이트',
    'lucky elements': '행운 요소',
    'monthly flow': '월별 흐름',
    'wealth potential': '재물 잠재력',
    'element analysis': '오행 재물 분석',
    'realestate': '부동산',
    'stock': '주식',
    'crypto': '암호화폐',
    'side': '부업',
    'saving': '저축',
    'business': '사업',
    'dimensions': '성격 차원 분석',
    'today trap': '오늘의 함정',
    'mbti description': 'MBTI 설명',
    'cognitive strengths': '인지적 강점',
    'challenges': '도전 과제',
    'time strategy': '시간대 전략',
    'caution activities': '경계 활동',
    'traditional elements': '전통 요소',
    'physical': '신체 리듬',
    'emotional': '감정 리듬',
    'intellectual': '지성 리듬',
    'today recommendation': '오늘의 추천',
    'weekly forecast': '주간 예보',
    'important dates': '중요 날짜',
    'weekly activities': '주간 활동',
    'personal analysis': '개인 분석',
    'lifestyle advice': '라이프스타일 조언',
    'health tips': '건강 팁',
    'recommended names': '추천 이름',
    'ohaeng analysis': '오행 분석',
    'naming tips': '작명 팁',
    'hard truth': '냉정한 진실',
    'their perspective': '상대방의 시선',
    'strategic advice': '전략적 조언',
    'emotional prescription': '감정 처방전',
    'reunion possibility': '재회 가능성',
    'reunion assessment': '재회 분석',
    'reunion cap': '재회 상한',
    'contact status': '연락 상태',
    'relationship depth': '관계 깊이',
    'current state': '현재 상태',
    'comfort message': '위로 메시지',
    'closing message': '마무리 메시지',
    'opening message': '시작 메시지',
    'breakup analysis': '이별 분석',
    'emotional journey': '감정 여정',
    'pets voice': '반려동물 속마음',
    'bonding mission': '유대감 미션',
    'daily condition': '오늘의 컨디션',
    'owner bond': '주인과의 유대감',
    'activity recommendation': '활동 추천',
    'care tips': '케어 팁',
    'health check': '웰니스 체크',
    'weather advice': '날씨 조언',
    'pet info': '반려동물 정보',
    'today story': '오늘의 이야기',
    'breed specific': '품종별 특성',
    'health insight': '건강 인사이트',
    'emotional care': '감정 케어',
    'special tips': '특별 팁',
    'pet content': '반려동물 콘텐츠',
    'pet summary': '반려동물 요약',
    'love profile': '연애 프로필',
    'detailed analysis': '상세 분석',
    'todays advice': '오늘의 조언',
    'predictions': '예측',
    'overall compatibility': '전체 궁합',
    'personality match': '성격 궁합',
    'love match': '연애 궁합',
    'marriage match': '결혼 궁합',
    'communication match': '소통 궁합',
    'strengths': '강점',
    'cautions': '주의점',
    'detailed advice': '상세 조언',
    'zodiac animal': '띠',
    'star sign': '별자리',
    'destiny number': '운명의 숫자',
    'age difference': '나이 차이',
    'love style': '연애 스타일',
    'overall score': '전체 점수',
    'luckycolor': '행운 색상',
    'luckynumber': '행운 숫자',
    'energy level': '에너지 레벨',
    'by zodiac animal': '띠별 흐름',
    'by zodiac sign': '별자리 흐름',
    'by mbti': 'MBTI 흐름',
  };
}
