#!/bin/bash
# Deploy all fortune Edge Functions

echo "🚀 Deploying Supabase Edge Functions..."

# Deploy shared functions first
echo "📦 Deploying shared utilities..."

# Deploy all fortune functions

echo "🔮 Deploying fortune-daily..."
supabase functions deploy fortune-daily
echo "🔮 Deploying fortune-today..."
supabase functions deploy fortune-today
echo "🔮 Deploying fortune-tomorrow..."
supabase functions deploy fortune-tomorrow
echo "🔮 Deploying fortune-weekly..."
supabase functions deploy fortune-weekly
echo "🔮 Deploying fortune-monthly..."
supabase functions deploy fortune-monthly
echo "🔮 Deploying fortune-yearly..."
supabase functions deploy fortune-yearly
echo "🔮 Deploying fortune-hourly..."
supabase functions deploy fortune-hourly
echo "🔮 Deploying fortune-saju..."
supabase functions deploy fortune-saju
echo "🔮 Deploying fortune-traditional-saju..."
supabase functions deploy fortune-traditional-saju
echo "🔮 Deploying fortune-saju-psychology..."
supabase functions deploy fortune-saju-psychology
echo "🔮 Deploying fortune-tojeong..."
supabase functions deploy fortune-tojeong
echo "🔮 Deploying fortune-salpuli..."
supabase functions deploy fortune-salpuli
echo "🔮 Deploying fortune-palmistry..."
supabase functions deploy fortune-palmistry
echo "🔮 Deploying fortune-physiognomy..."
supabase functions deploy fortune-physiognomy
echo "🔮 Deploying fortune-mbti..."
supabase functions deploy fortune-mbti
echo "🔮 Deploying fortune-personality..."
supabase functions deploy fortune-personality
echo "🔮 Deploying fortune-blood-type..."
supabase functions deploy fortune-blood-type
echo "🔮 Deploying fortune-love..."
supabase functions deploy fortune-love
echo "🔮 Deploying fortune-marriage..."
supabase functions deploy fortune-marriage
echo "🔮 Deploying fortune-compatibility..."
supabase functions deploy fortune-compatibility
echo "🔮 Deploying fortune-traditional-compatibility..."
supabase functions deploy fortune-traditional-compatibility
echo "🔮 Deploying fortune-couple-match..."
supabase functions deploy fortune-couple-match
echo "🔮 Deploying fortune-blind-date..."
supabase functions deploy fortune-blind-date
echo "🔮 Deploying fortune-ex-lover..."
supabase functions deploy fortune-ex-lover
echo "🔮 Deploying fortune-celebrity-match..."
supabase functions deploy fortune-celebrity-match
echo "🔮 Deploying fortune-chemistry..."
supabase functions deploy fortune-chemistry
echo "🔮 Deploying fortune-career..."
supabase functions deploy fortune-career
echo "🔮 Deploying fortune-employment..."
supabase functions deploy fortune-employment
echo "🔮 Deploying fortune-business..."
supabase functions deploy fortune-business
echo "🔮 Deploying fortune-startup..."
supabase functions deploy fortune-startup
echo "🔮 Deploying fortune-lucky-job..."
supabase functions deploy fortune-lucky-job
echo "🔮 Deploying fortune-wealth..."
supabase functions deploy fortune-wealth
echo "🔮 Deploying fortune-health..."
supabase functions deploy fortune-health
echo "🔮 Deploying fortune-destiny..."
supabase functions deploy fortune-destiny
echo "🔮 Deploying fortune-past-life..."
supabase functions deploy fortune-past-life
echo "🔮 Deploying fortune-talent..."
supabase functions deploy fortune-talent
echo "🔮 Deploying fortune-network-report..."
supabase functions deploy fortune-network-report
echo "🔮 Deploying fortune-timeline..."
supabase functions deploy fortune-timeline
echo "🔮 Deploying fortune-biorhythm..."
supabase functions deploy fortune-biorhythm
echo "🔮 Deploying fortune-birth-season..."
supabase functions deploy fortune-birth-season
echo "🔮 Deploying fortune-birthdate..."
supabase functions deploy fortune-birthdate
echo "🔮 Deploying fortune-birthstone..."
supabase functions deploy fortune-birthstone
echo "🔮 Deploying fortune-zodiac-animal..."
supabase functions deploy fortune-zodiac-animal
echo "🔮 Deploying fortune-zodiac..."
supabase functions deploy fortune-zodiac
echo "🔮 Deploying fortune-five-blessings..."
supabase functions deploy fortune-five-blessings
echo "🔮 Deploying fortune-wish..."
supabase functions deploy fortune-wish
echo "🔮 Deploying fortune-avoid-people..."
supabase functions deploy fortune-avoid-people
echo "🔮 Deploying fortune-lucky-number..."
supabase functions deploy fortune-lucky-number
echo "🔮 Deploying fortune-lucky-color..."
supabase functions deploy fortune-lucky-color
echo "🔮 Deploying fortune-lucky-items..."
supabase functions deploy fortune-lucky-items
echo "🔮 Deploying fortune-lucky-food..."
supabase functions deploy fortune-lucky-food
echo "🔮 Deploying fortune-lucky-place..."
supabase functions deploy fortune-lucky-place
echo "🔮 Deploying fortune-lucky-outfit..."
supabase functions deploy fortune-lucky-outfit
echo "🔮 Deploying fortune-lucky-series..."
supabase functions deploy fortune-lucky-series
echo "🔮 Deploying fortune-lucky-lottery..."
supabase functions deploy fortune-lucky-lottery
echo "🔮 Deploying fortune-lucky-stock..."
supabase functions deploy fortune-lucky-stock
echo "🔮 Deploying fortune-lucky-crypto..."
supabase functions deploy fortune-lucky-crypto
echo "🔮 Deploying fortune-lucky-investment..."
supabase functions deploy fortune-lucky-investment
echo "🔮 Deploying fortune-lucky-realestate..."
supabase functions deploy fortune-lucky-realestate
echo "🔮 Deploying fortune-lucky-sidejob..."
supabase functions deploy fortune-lucky-sidejob
echo "🔮 Deploying fortune-lucky-baseball..."
supabase functions deploy fortune-lucky-baseball
echo "🔮 Deploying fortune-lucky-golf..."
supabase functions deploy fortune-lucky-golf
echo "🔮 Deploying fortune-lucky-tennis..."
supabase functions deploy fortune-lucky-tennis
echo "🔮 Deploying fortune-lucky-cycling..."
supabase functions deploy fortune-lucky-cycling
echo "🔮 Deploying fortune-lucky-running..."
supabase functions deploy fortune-lucky-running
echo "🔮 Deploying fortune-lucky-hiking..."
supabase functions deploy fortune-lucky-hiking
echo "🔮 Deploying fortune-lucky-fishing..."
supabase functions deploy fortune-lucky-fishing
echo "🔮 Deploying fortune-lucky-swim..."
supabase functions deploy fortune-lucky-swim
echo "🔮 Deploying fortune-lucky-fitness..."
supabase functions deploy fortune-lucky-fitness
echo "🔮 Deploying fortune-lucky-yoga..."
supabase functions deploy fortune-lucky-yoga
echo "🔮 Deploying fortune-lucky-exam..."
supabase functions deploy fortune-lucky-exam
echo "🔮 Deploying fortune-moving..."
supabase functions deploy fortune-moving
echo "🔮 Deploying fortune-moving-date..."
supabase functions deploy fortune-moving-date
echo "🔮 Deploying fortune-new-year..."
supabase functions deploy fortune-new-year
echo "🔮 Deploying fortune-face-reading..."
supabase functions deploy fortune-face-reading
echo "🔮 Deploying fortune-celebrity..."
supabase functions deploy fortune-celebrity
echo "🔮 Deploying fortune-talisman..."
supabase functions deploy fortune-talisman

echo "✅ All functions deployed successfully!"
