-- Sample celebrity data for testing
-- Generated by CelebritySampleData

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'pro_gamer_faker',
  'Faker',
  '1996-05-07',
  'male',
  'pro_gamer',
  NULL,
  '이상혁',
  ARRAY['Faker', '페이커'],
  '한국',
  NULL,
  '12:00',
  2013,
  'T1',
  ARRAY['한국어', '영어'],
  '{"youtube": "https://www.youtube.com/@faker", "instagram": "https://instagram.com/faker"}'::jsonb,
  '{"game_title": "League of Legends", "primary_role": "Mid", "team": "T1", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2023 월드 챔피언십 우승", "2022 월드 챔피언십 우승"], "ign": "Faker", "pro_debut": "2013-02", "retired": false}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'streamer_jokbaltan',
  '족발탄',
  '1990-03-15',
  'male',
  'streamer',
  NULL,
  NULL,
  ARRAY['족발탄'],
  '한국',
  NULL,
  '12:00',
  2018,
  NULL,
  ARRAY['한국어'],
  '{"twitch": "https://twitch.tv/jokbaltan", "youtube": "https://www.youtube.com/@jokbaltan"}'::jsonb,
  '{"main_platform": "twitch", "channel_url": "https://twitch.tv/jokbaltan", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후 2-8시", "first_stream_date": "2018-01", "avg_viewers_bucket": "large"}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'solo_singer_iu',
  '아이유',
  '1993-05-16',
  'female',
  'solo_singer',
  'IU',
  '이지은',
  ARRAY['아이유', 'IU', '이지은'],
  '한국',
  '서울특별시 종로구',
  '14:30',
  2008,
  'EDAM 엔터테인먼트',
  ARRAY['한국어', '영어', '일본어'],
  '{"wikipedia": "https://ko.wikipedia.org/wiki/아이유", "youtube": "https://www.youtube.com/@dlwlrma", "instagram": "https://instagram.com/dlwlrma"}'::jsonb,
  '{"debut_date": "2008-09", "label": "EDAM 엔터테인먼트", "genres": ["발라드", "팝", "R&B"], "fandom_name": "유애나", "vocal_range": "소프라노", "notable_tracks": ["좋은 날", "Through the Night", "Celebrity"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'idol_member_rm',
  'RM',
  '1994-09-12',
  'male',
  'idol_member',
  NULL,
  '김남준',
  ARRAY['RM', '랩몬스터', 'Rap Monster'],
  '한국',
  NULL,
  '12:00',
  2013,
  'HYBE 엔터테인먼트',
  ARRAY['한국어', '영어'],
  '{"instagram": "https://instagram.com/rkive", "youtube": "https://www.youtube.com/@bts"}'::jsonb,
  '{"group_name": "BTS", "position": ["rap", "leader"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["Indigo 앨범", "Right Place, Wrong Person"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'actor_song_kang_ho',
  '송강호',
  '1967-01-17',
  'male',
  'actor',
  NULL,
  NULL,
  ARRAY['송강호'],
  '한국',
  NULL,
  '12:00',
  1996,
  '매니지먼트 숲',
  ARRAY['한국어'],
  '{"wikipedia": "https://ko.wikipedia.org/wiki/송강호", "imdb": "https://www.imdb.com/name/nm0814280/"}'::jsonb,
  '{"acting_debut": "1996", "agency": "매니지먼트 숲", "specialties": ["film", "tv"], "notable_works": ["기생충", "옥자", "살인의 추억", "괴물"], "awards": ["아카데미 작품상", "칸 영화제 남우주연상"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'athlete_son_heung_min',
  '손흥민',
  '1992-07-08',
  'male',
  'athlete',
  NULL,
  NULL,
  ARRAY['손흥민', 'Son Heung-min'],
  '한국',
  NULL,
  '12:00',
  2008,
  NULL,
  ARRAY['한국어', '영어'],
  '{"instagram": "https://instagram.com/hm_son7", "wikipedia": "https://ko.wikipedia.org/wiki/손흥민"}'::jsonb,
  '{"sport": "축구", "position_role": "공격수", "team": "토트넘 홋스퍼", "league": "프리미어리그", "dominant_hand_foot": "both", "pro_debut": "2008", "career_highlights": ["2018 월드컵 16강", "EPL 골든부트"], "records_personal_bests": ["EPL 시즌 최다골 23골"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'politician_lee_jae_myung',
  '이재명',
  '1964-12-22',
  'male',
  'politician',
  NULL,
  NULL,
  ARRAY['이재명'],
  '한국',
  NULL,
  '12:00',
  2006,
  NULL,
  ARRAY['한국어'],
  '{"wikipedia": "https://ko.wikipedia.org/wiki/이재명"}'::jsonb,
  '{"party": "더불어민주당", "current_office": "국회의원", "constituency": "경기 성남시 분당구 을", "term_start": "2020-05-30", "term_end": "2024-05-29", "previous_offices": ["경기도지사", "성남시장"], "ideology_tags": ["진보"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES (
  'business_lee_jae_yong',
  '이재용',
  '1968-06-23',
  'male',
  'business',
  NULL,
  NULL,
  ARRAY['이재용'],
  '한국',
  NULL,
  '12:00',
  1991,
  NULL,
  ARRAY['한국어', '영어'],
  '{"wikipedia": "https://ko.wikipedia.org/wiki/이재용_(기업인)"}'::jsonb,
  '{"company_name": "삼성전자", "title": "회장", "industry": "전자/반도체", "founded_year": "", "board_memberships": ["삼성물산", "삼성SDS"], "notable_ventures": ["삼성 바이오로직스", "삼성전기"]}'::jsonb,
  '샘플 데이터'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

-- Create migration log entry
INSERT INTO public.migration_log (migration_name, status, message, created_at)
VALUES (
    'insert_sample_data',
    'completed',
    'Successfully inserted 8 sample celebrity records for testing',
    NOW()
) ON CONFLICT DO NOTHING;