-- 배우 50명 실제 데이터 삽입
-- Category: actor

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES
('actor_song_kang_ho', '송강호', '1967-01-17', 'male', 'actor', NULL, NULL, ARRAY['송강호'], '한국', NULL, '12:00', 1996, '판시온', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/송강호"}'::jsonb, '{"filmography_highlights": ["기생충", "살인의 추억", "괴물"], "awards": ["칸 영화제 남우주연상"], "genre_speciality": ["드라마", "스릴러"], "debut_work": "너에게 나를 보낸다", "agency": "판시온", "notable_collaborations": ["봉준호", "박찬욱"]}'::jsonb, '실제 데이터'),

('actor_gong_yoo', '공유', '1979-07-10', 'male', 'actor', '공유', '공지철', ARRAY['공유', '공지철'], '한국', NULL, '12:00', 2001, '매니지먼트 숲', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/공유"}'::jsonb, '{"filmography_highlights": ["도깨비", "부산행", "커피프린스 1호점"], "awards": ["백상예술대상 TV부문 남자 최우수연기상"], "genre_speciality": ["로맨스", "판타지", "액션"], "debut_work": "학교 4", "agency": "매니지먼트 숲", "notable_collaborations": ["연상호", "김은숙"]}'::jsonb, '실제 데이터'),

('actor_hyun_bin', '현빈', '1982-09-25', 'male', 'actor', '현빈', '김태평', ARRAY['현빈', '김태평'], '한국', NULL, '12:00', 2003, 'VAST 엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/현빈"}'::jsonb, '{"filmography_highlights": ["사랑의 불시착", "시크릿 가든", "아저씨"], "awards": ["백상예술대상 영화부문 남자 최우수연기상"], "genre_speciality": ["로맨스", "액션", "스릴러"], "debut_work": "보디가드", "agency": "VAST 엔터테인먼트", "notable_collaborations": ["박혜련", "김은숙"]}'::jsonb, '실제 데이터'),

('actor_son_ye_jin', '손예진', '1982-01-11', 'female', 'actor', NULL, NULL, ARRAY['손예진'], '한국', NULL, '12:00', 2000, 'MS 팀 엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/손예진"}'::jsonb, '{"filmography_highlights": ["사랑의 불시착", "클래식", "내 머리 속의 지우개"], "awards": ["청룡영화상 여우주연상"], "genre_speciality": ["로맨스", "멜로", "드라마"], "debut_work": "시크릿 티어즈", "agency": "MS 팀 엔터테인먼트", "notable_collaborations": ["박혜련", "곽재용"]}'::jsonb, '실제 데이터'),

('actor_park_so_dam', '박소담', '1991-09-08', 'female', 'actor', NULL, NULL, ARRAY['박소담'], '한국', NULL, '12:00', 2013, '아티스트 컴퍼니', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박소담"}'::jsonb, '{"filmography_highlights": ["기생충", "청춘시대", "레코드"], "awards": ["SAG 어워드 앙상블 상"], "genre_speciality": ["드라마", "인디", "코미디"], "debut_work": "우아한 거짓말", "agency": "아티스트 컴퍼니", "notable_collaborations": ["봉준호", "정윤철"]}'::jsonb, '실제 데이터'),

('actor_choi_min_sik', '최민식', '1962-01-22', 'male', 'actor', NULL, NULL, ARRAY['최민식'], '한국', NULL, '12:00', 1989, 'C-JeS 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/최민식"}'::jsonb, '{"filmography_highlights": ["올드보이", "신세계", "명량"], "awards": ["칸 영화제 남우주연상"], "genre_speciality": ["액션", "스릴러", "사극"], "debut_work": "강변부인", "agency": "C-JeS 엔터테인먼트", "notable_collaborations": ["박찬욱", "김한민"]}'::jsonb, '실제 데이터'),

('actor_lee_byung_hun', '이병헌', '1970-07-12', 'male', 'actor', NULL, NULL, ARRAY['이병헌'], '한국', NULL, '12:00', 1991, 'BH 엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이병헌"}'::jsonb, '{"filmography_highlights": ["G.I. 조", "좋은 놈, 나쁜 놈, 이상한 놈", "미스터 션샤인"], "awards": ["백상예술대상 대상"], "genre_speciality": ["액션", "웨스턴", "스릴러"], "debut_work": "아스팔트 사나이", "agency": "BH 엔터테인먼트", "notable_collaborations": ["김지운", "이병헌"]}'::jsonb, '실제 데이터'),

('actor_jun_ji_hyun', '전지현', '1981-10-30', 'female', 'actor', NULL, NULL, ARRAY['전지현'], '한국', NULL, '12:00', 1999, '매니지먼트 숲', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/전지현"}'::jsonb, '{"filmography_highlights": ["별에서 온 그대", "엽기적인 그녀", "암살"], "awards": ["백상예술대상 TV부문 여자 최우수연기상"], "genre_speciality": ["로맨스", "액션", "코미디"], "debut_work": "화이트 발렌타인", "agency": "매니지먼트 숲", "notable_collaborations": ["곽재용", "최동훈"]}'::jsonb, '실제 데이터'),

('actor_ha_jung_woo', '하정우', '1978-03-11', 'male', 'actor', '하정우', '김성훈', ARRAY['하정우', '김성훈'], '한국', NULL, '12:00', 2002, '워크하우스컴퍼니', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/하정우"}'::jsonb, '{"filmography_highlights": ["추격자", "황해", "암살"], "awards": ["청룡영화상 남우주연상"], "genre_speciality": ["액션", "스릴러", "범죄"], "debut_work": "시체가 돌아왔다", "agency": "워크하우스컴퍼니", "notable_collaborations": ["나홍진", "최동훈"]}'::jsonb, '실제 데이터'),

('actor_kim_hye_soo', '김혜수', '1970-09-05', 'female', 'actor', NULL, NULL, ARRAY['김혜수'], '한국', NULL, '12:00', 1986, '사람엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김혜수"}'::jsonb, '{"filmography_highlights": ["시그널", "품위있는 그녀", "타짜"], "awards": ["백상예술대상 TV부문 여자 최우수연기상"], "genre_speciality": ["범죄", "느와르", "드라마"], "debut_work": "어린 의뢰인", "agency": "사람엔터테인먼트", "notable_collaborations": ["김은희", "최동훈"]}'::jsonb, '실제 데이터'),

('actor_so_ji_sub', '소지섭', '1977-11-04', 'male', 'actor', NULL, NULL, ARRAY['소지섭'], '한국', NULL, '12:00', 1995, '51K', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/소지섭"}'::jsonb, '{"filmography_highlights": ["회사원", "주군의 태양", "본 투 킬"], "awards": ["KBS 연기대상 대상"], "genre_speciality": ["로맨스", "액션", "스릴러"], "debut_work": "모델", "agency": "51K", "notable_collaborations": ["홍상수", "김은숙"]}'::jsonb, '실제 데이터'),

('actor_park_min_young', '박민영', '1986-03-04', 'female', 'actor', NULL, NULL, ARRAY['박민영'], '한국', NULL, '12:00', 2005, '나무엑터스', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박민영"}'::jsonb, '{"filmography_highlights": ["김비서가 왜 그럴까", "성균관 스캔들", "예쁜 누나"], "awards": ["SBS 연기대상 대상"], "genre_speciality": ["로맨스", "코미디", "사극"], "debut_work": "불멸의 이순신", "agency": "나무엑터스", "notable_collaborations": ["박준화", "노희경"]}'::jsonb, '실제 데이터'),

('actor_lee_min_ho', '이민호', '1987-06-22', 'male', 'actor', NULL, NULL, ARRAY['이민호'], '한국', NULL, '12:00', 2006, 'MYM 엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이민호"}'::jsonb, '{"filmography_highlights": ["꽃보다 남자", "상속자들", "더 킹"], "awards": ["SBS 연기대상 대상"], "genre_speciality": ["로맨스", "드라마", "판타지"], "debut_work": "반올림", "agency": "MYM 엔터테인먼트", "notable_collaborations": ["김은숙", "박혜련"]}'::jsonb, '실제 데이터'),

('actor_song_hye_kyo', '송혜교', '1981-11-22', 'female', 'actor', NULL, NULL, ARRAY['송혜교'], '한국', NULL, '12:00', 1996, 'UAA', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/송혜교"}'::jsonb, '{"filmography_highlights": ["태양의 후예", "가을동화", "디 엠퍼러"], "awards": ["KBS 연기대상 대상"], "genre_speciality": ["로맨스", "멜로", "드라마"], "debut_work": "첫사랑", "agency": "UAA", "notable_collaborations": ["김은숙", "윤제균"]}'::jsonb, '실제 데이터'),

('actor_ryu_jun_yeol', '류준열', '1986-09-25', 'male', 'actor', NULL, NULL, ARRAY['류준열'], '한국', NULL, '12:00', 2015, 'C-JeS 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/류준열"}'::jsonb, '{"filmography_highlights": ["응답하라 1988", "리틀 포레스트", "모가디슈"], "awards": ["백상예술대상 신인상"], "genre_speciality": ["드라마", "로맨스", "액션"], "debut_work": "소셜포비아", "agency": "C-JeS 엔터테인먼트", "notable_collaborations": ["신원호", "류승완"]}'::jsonb, '실제 데이터'),

('actor_kim_so_hyun', '김소현', '1999-06-04', 'female', 'actor', NULL, NULL, ARRAY['김소현'], '한국', NULL, '12:00', 2006, '문화창고', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김소현"}'::jsonb, '{"filmography_highlights": ["러브 알람", "학교 2015", "우리 집에 사는 남자"], "awards": ["MBC 연기대상 여자 신인상"], "genre_speciality": ["로맨스", "학원", "드라마"], "debut_work": "드라마시티", "agency": "문화창고", "notable_collaborations": ["이명우", "김진만"]}'::jsonb, '실제 데이터'),

('actor_park_seo_jun', '박서준', '1988-12-16', 'male', 'actor', NULL, NULL, ARRAY['박서준'], '한국', NULL, '12:00', 2011, '어썸 이엔티', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박서준"}'::jsonb, '{"filmography_highlights": ["김비서가 왜 그럴까", "이태원 클라쓰", "기생충"], "awards": ["KBS 연기대상 최우수상"], "genre_speciality": ["로맨스", "코미디", "드라마"], "debut_work": "드림하이 2", "agency": "어썸 이엔티", "notable_collaborations": ["박준화", "봉준호"]}'::jsonb, '실제 데이터'),

('actor_iu', 'IU', '1993-05-16', 'female', 'actor', 'IU', '이지은', ARRAY['IU', '이지은', '아이유'], '한국', NULL, '12:00', 2011, 'EDAM 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/아이유"}'::jsonb, '{"filmography_highlights": ["나의 아저씨", "달의 연인", "페르소나"], "awards": ["KBS 연기대상 여자 최우수연기상"], "genre_speciality": ["드라마", "로맨스", "인디"], "debut_work": "드림하이", "agency": "EDAM 엔터테인먼트", "notable_collaborations": ["김원석", "이정향"]}'::jsonb, '실제 데이터'),

('actor_yoo_ah_in', '유아인', '1986-10-06', 'male', 'actor', '유아인', '엄홍식', ARRAY['유아인', '엄홍식'], '한국', NULL, '12:00', 2003, 'UAA', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/유아인"}'::jsonb, '{"filmography_highlights": ["버닝", "밀양", "#살아있다"], "awards": ["칸 영화제 신인상"], "genre_speciality": ["드라마", "인디", "스릴러"], "debut_work": "뱀파이어 아이돌", "agency": "UAA", "notable_collaborations": ["이창동", "조일현"]}'::jsonb, '실제 데이터'),

('actor_ma_dong_seok', '마동석', '1971-03-01', 'male', 'actor', NULL, NULL, ARRAY['마동석'], '한국', NULL, '12:00', 2005, '빅펀치엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/마동석"}'::jsonb, '{"filmography_highlights": ["부산행", "범죄도시", "챔피언"], "awards": ["청룡영화상 남우조연상"], "genre_speciality": ["액션", "코미디", "스릴러"], "debut_work": "범죄의 재구성", "agency": "빅펀치엔터테인먼트", "notable_collaborations": ["연상호", "강윤성"]}'::jsonb, '실제 데이터'),

('actor_kim_yoo_jung', '김유정', '1999-09-22', 'female', 'actor', NULL, NULL, ARRAY['김유정'], '한국', NULL, '12:00', 2003, 'SidusHQ', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김유정"}'::jsonb, '{"filmography_highlights": ["구르미 그린 달빛", "일단 뛰어", "백설공주"], "awards": ["KBS 연기대상 여자 최우수연기상"], "genre_speciality": ["로맨스", "사극", "학원"], "debut_work": "DMZ 야생동물 이야기", "agency": "SidusHQ", "notable_collaborations": ["김성윤", "이정향"]}'::jsonb, '실제 데이터'),

('actor_lee_jung_jae', '이정재', '1973-03-15', 'male', 'actor', NULL, NULL, ARRAY['이정재'], '한국', NULL, '12:00', 1993, '아티스트 컴퍼니', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이정재"}'::jsonb, '{"filmography_highlights": ["오징어 게임", "신세계", "관상"], "awards": ["에미상 남우주연상"], "genre_speciality": ["스릴러", "범죄", "드라마"], "debut_work": "공룡 선생", "agency": "아티스트 컴퍼니", "notable_collaborations": ["황동혁", "박훈정"]}'::jsonb, '실제 데이터'),

('actor_bae_doona', '배두나', '1979-10-11', 'female', 'actor', NULL, NULL, ARRAY['배두나'], '한국', NULL, '12:00', 1998, '매니지먼트 숲', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/배두나"}'::jsonb, '{"filmography_highlights": ["킹덤", "센스8", "괴물"], "awards": ["베니스 국제영화제 여우주연상"], "genre_speciality": ["SF", "스릴러", "드라마"], "debut_work": "대학일기", "agency": "매니지먼트 숲", "notable_collaborations": ["워쇼스키 자매", "봉준호"]}'::jsonb, '실제 데이터'),

('actor_zo_in_sung', '조인성', '1981-07-28', 'male', 'actor', NULL, NULL, ARRAY['조인성'], '한국', NULL, '12:00', 2000, 'IOK컴퍼니', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/조인성"}'::jsonb, '{"filmography_highlights": ["그 겨울, 바람이 분다", "괜찮아, 사랑이야", "더 킹"], "awards": ["SBS 연기대상 대상"], "genre_speciality": ["로맨스", "멜로", "스릴러"], "debut_work": "모델", "agency": "IOK컴퍼니", "notable_collaborations": ["노희경", "한재림"]}'::jsonb, '실제 데이터'),

('actor_han_hyo_joo', '한효주', '1987-02-22', 'female', 'actor', NULL, NULL, ARRAY['한효주'], '한국', NULL, '12:00', 2003, 'BH 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/한효주"}'::jsonb, '{"filmography_highlights": ["동이", "싸이보그지만 괜찮아", "해피니스"], "awards": ["MBC 연기대상 대상"], "genre_speciality": ["로맨스", "사극", "스릴러"], "debut_work": "논스톱 5", "agency": "BH 엔터테인먼트", "notable_collaborations": ["박찬욱", "안판석"]}'::jsonb, '실제 데이터'),

('actor_kang_dong_won', '강동원', '1981-01-18', 'male', 'actor', NULL, NULL, ARRAY['강동원'], '한국', NULL, '12:00', 2003, 'YG엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/강동원"}'::jsonb, '{"filmography_highlights": ["부산행", "1987", "늑대소년"], "awards": ["백상예술대상 영화부문 남우조연상"], "genre_speciality": ["액션", "로맨스", "드라마"], "debut_work": "프렌즈", "agency": "YG엔터테인먼트", "notable_collaborations": ["연상호", "장준환"]}'::jsonb, '실제 데이터'),

('actor_han_so_hee', '한소희', '1994-11-18', 'female', 'actor', NULL, NULL, ARRAY['한소희'], '한국', NULL, '12:00', 2017, '9ATO엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/한소희"}'::jsonb, '{"filmography_highlights": ["부부의 세계", "사생활", "마이네임"], "awards": ["APAN 스타 어워즈 신인상"], "genre_speciality": ["스릴러", "로맨스", "액션"], "debut_work": "돈꽃", "agency": "9ATO엔터테인먼트", "notable_collaborations": ["주동민", "김진민"]}'::jsonb, '실제 데이터'),

('actor_kim_woo_bin', '김우빈', '1989-07-16', 'male', 'actor', '김우빈', '김현중', ARRAY['김우빈', '김현중'], '한국', NULL, '12:00', 2008, 'SidusHQ', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김우빈"}'::jsonb, '{"filmography_highlights": ["상속자들", "언니가 간다", "20 세기 소녀"], "awards": ["SBS 연기대상 우수상"], "genre_speciality": ["로맨스", "드라마", "액션"], "debut_work": "하얀거탑", "agency": "SidusHQ", "notable_collaborations": ["김은숙", "방우리"]}'::jsonb, '실제 데이터'),

('actor_suzy', '수지', '1994-10-10', 'female', 'actor', '수지', '배수지', ARRAY['수지', '배수지'], '한국', NULL, '12:00', 2011, '매니지먼트 숲', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/수지"}'::jsonb, '{"filmography_highlights": ["당신이 잠든 사이에", "건축학개론", "스타트업"], "awards": ["KBS 연기대상 우수상"], "genre_speciality": ["로맨스", "드라마", "청춘"], "debut_work": "드림하이", "agency": "매니지먼트 숲", "notable_collaborations": ["박혜련", "이정환"]}'::jsonb, '실제 데이터'),

('actor_nam_joo_hyuk', '남주혁', '1994-02-22', 'male', 'actor', NULL, NULL, ARRAY['남주혁'], '한국', NULL, '12:00', 2013, 'YG엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/남주혁"}'::jsonb, '{"filmography_highlights": ["스타트업", "역도요정 김복주", "스물다섯 스물하나"], "awards": ["MBC 연기대상 남자 우수연기상"], "genre_speciality": ["로맨스", "청춘", "드라마"], "debut_work": "계수나무", "agency": "YG엔터테인먼트", "notable_collaborations": ["오충환", "윤제원"]}'::jsonb, '실제 데이터'),

('actor_kim_seon_ho', '김선호', '1986-05-08', 'male', 'actor', NULL, NULL, ARRAY['김선호'], '한국', NULL, '12:00', 2009, 'SALT엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김선호"}'::jsonb, '{"filmography_highlights": ["갯마을 차차차", "스타트업", "신의 한 수"], "awards": ["백상예술대상 TV부문 남자 인기상"], "genre_speciality": ["로맨스", "코미디", "드라마"], "debut_work": "굿매니저", "agency": "SALT엔터테인먼트", "notable_collaborations": ["윤제원", "정현정"]}'::jsonb, '실제 데이터'),

('actor_shin_min_ah', '신민아', '1984-04-05', 'female', 'actor', NULL, NULL, ARRAY['신민아'], '한국', NULL, '12:00', 2001, 'AM 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/신민아"}'::jsonb, '{"filmography_highlights": ["갯마을 차차차", "디바", "내 여자친구는 구미호"], "awards": ["KBS 연기대상 여자 최우수연기상"], "genre_speciality": ["로맨스", "코미디", "판타지"], "debut_work": "올인", "agency": "AM 엔터테인먼트", "notable_collaborations": ["정현정", "신우철"]}'::jsonb, '실제 데이터'),

('actor_lee_jong_suk', '이종석', '1989-09-14', 'male', 'actor', NULL, NULL, ARRAY['이종석'], '한국', NULL, '12:00', 2005, 'A-MAN 프로젝트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이종석"}'::jsonb, '{"filmography_highlights": ["당신이 잠든 사이에", "W", "닥터 스트레인저"], "awards": ["SBS 연기대상 최우수상"], "genre_speciality": ["로맨스", "판타지", "메디컬"], "debut_work": "비밀의 교정", "agency": "A-MAN 프로젝트", "notable_collaborations": ["박혜련", "김은희"]}'::jsonb, '실제 데이터'),

('actor_park_shin_hye', '박신혜', '1990-02-18', 'female', 'actor', NULL, NULL, ARRAY['박신혜'], '한국', NULL, '12:00', 2003, 'SALT엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박신혜"}'::jsonb, '{"filmography_highlights": ["상속자들", "닥터스", "시지프스"], "awards": ["SBS 연기대상 최우수상"], "genre_speciality": ["로맨스", "메디컬", "SF"], "debut_work": "천국의 계단", "agency": "SALT엔터테인먼트", "notable_collaborations": ["김은숙", "진형욱"]}'::jsonb, '실제 데이터'),

('actor_ji_chang_wook', '지창욱', '1987-07-05', 'male', 'actor', NULL, NULL, ARRAY['지창욱'], '한국', NULL, '12:00', 2006, 'Spring Company', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/지창욱"}'::jsonb, '{"filmography_highlights": ["힐러", "도시남녀의 사랑법", "편의점 샛별이"], "awards": ["KBS 연기대상 남자 최우수연기상"], "genre_speciality": ["액션", "로맨스", "스릴러"], "debut_work": "태왕사신기", "agency": "Spring Company", "notable_collaborations": ["송현욱", "이명한"]}'::jsonb, '실제 데이터'),

('actor_lee_seung_gi', '이승기', '1987-01-13', 'male', 'actor', NULL, NULL, ARRAY['이승기'], '한국', NULL, '12:00', 2004, 'HOOK 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이승기"}'::jsonb, '{"filmography_highlights": ["마우스", "구미호뎐", "베가본드"], "awards": ["SBS 연기대상 대상"], "genre_speciality": ["스릴러", "판타지", "액션"], "debut_work": "논스톱 5", "agency": "HOOK 엔터테인먼트", "notable_collaborations": ["최란", "곽정환"]}'::jsonb, '실제 데이터'),

('actor_song_joong_ki', '송중기', '1985-09-19', 'male', 'actor', NULL, NULL, ARRAY['송중기'], '한국', NULL, '12:00', 2008, '히스토리 D&C', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/송중기"}'::jsonb, '{"filmography_highlights": ["태양의 후예", "성균관 스캔들", "빈센조"], "awards": ["KBS 연기대상 대상"], "genre_speciality": ["로맨스", "액션", "코미디"], "debut_work": "러브레터", "agency": "히스토리 D&C", "notable_collaborations": ["김은숙", "김희원"]}'::jsonb, '실제 데이터'),

('actor_yoona', '윤아', '1990-05-30', 'female', 'actor', '윤아', '임윤아', ARRAY['윤아', '임윤아'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/윤아"}'::jsonb, '{"filmography_highlights": ["엑시트", "사랑비", "공조"], "awards": ["KBS 연기대상 여자 우수연기상"], "genre_speciality": ["액션", "로맨스", "코미디"], "debut_work": "9단의 연인", "agency": "SM엔터테인먼트", "notable_collaborations": ["이상근", "김성훈"]}'::jsonb, '실제 데이터'),

('actor_kim_tae_ri', '김태리', '1990-04-24', 'female', 'actor', NULL, NULL, ARRAY['김태리'], '한국', NULL, '12:00', 2016, '러브스토리엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김태리"}'::jsonb, '{"filmography_highlights": ["아가씨", "미스터 션샤인", "승리호"], "awards": ["백상예술대상 영화부문 여자 신인상"], "genre_speciality": ["드라마", "SF", "사극"], "debut_work": "아가씨", "agency": "러브스토리엔터테인먼트", "notable_collaborations": ["박찬욱", "이병헌"]}'::jsonb, '실제 데이터'),

('actor_yoo_yeon_seok', '유연석', '1984-04-11', 'male', 'actor', NULL, NULL, ARRAY['유연석'], '한국', NULL, '12:00', 2003, '킹콩 by 스타쉽', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/유연석"}'::jsonb, '{"filmography_highlights": ["슬기로운 의사생활", "응답하라 1994", "건축학개론"], "awards": ["tvN10 어워즈 남자 연기상"], "genre_speciality": ["로맨스", "메디컬", "코미디"], "debut_work": "올드보이", "agency": "킹콩 by 스타쉽", "notable_collaborations": ["신원호", "이우정"]}'::jsonb, '실제 데이터'),

('actor_park_bo_gum', '박보검', '1993-06-16', 'male', 'actor', NULL, NULL, ARRAY['박보검'], '한국', NULL, '12:00', 2011, '블러썸엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박보검"}'::jsonb, '{"filmography_highlights": ["구르미 그린 달빛", "청춘기록", "보이후드"], "awards": ["KBS 연기대상 대상"], "genre_speciality": ["로맨스", "사극", "드라마"], "debut_work": "블라인드", "agency": "블러썸엔터테인먼트", "notable_collaborations": ["김성윤", "안판석"]}'::jsonb, '실제 데이터'),

('actor_moon_chae_won', '문채원', '1986-11-13', 'female', 'actor', NULL, NULL, ARRAY['문채원'], '한국', NULL, '12:00', 2007, '나무엑터스', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/문채원"}'::jsonb, '{"filmography_highlights": ["굿 닥터", "공주의 남자", "화정"], "awards": ["KBS 연기대상 여자 최우수연기상"], "genre_speciality": ["메디컬", "사극", "로맨스"], "debut_work": "천국의 계단", "agency": "나무엑터스", "notable_collaborations": ["박재범", "김진만"]}'::jsonb, '실제 데이터'),

('actor_jo_jung_suk', '조정석', '1980-12-26', 'male', 'actor', NULL, NULL, ARRAY['조정석'], '한국', NULL, '12:00', 2004, 'JAM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/조정석"}'::jsonb, '{"filmography_highlights": ["슬기로운 의사생활", "질투의 화신", "엑시트"], "awards": ["tvN10 어워즈 남자 연기상"], "genre_speciality": ["메디컬", "코미디", "액션"], "debut_work": "패밀리", "agency": "JAM엔터테인먼트", "notable_collaborations": ["신원호", "이상근"]}'::jsonb, '실제 데이터'),

('actor_kim_go_eun', '김고은', '1991-07-02', 'female', 'actor', NULL, NULL, ARRAY['김고은'], '한국', NULL, '12:00', 2012, 'BH 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/김고은"}'::jsonb, '{"filmography_highlights": ["도깨비", "치즈인더트랩", "더 킹"], "awards": ["tvN10 어워즈 여자 연기상"], "genre_speciality": ["판타지", "로맨스", "드라마"], "debut_work": "은교", "agency": "BH 엔터테인먼트", "notable_collaborations": ["김은숙", "이병헌"]}'::jsonb, '실제 데이터'),

('actor_jung_hae_in', '정해인', '1988-04-01', 'male', 'actor', NULL, NULL, ARRAY['정해인'], '한국', NULL, '12:00', 2014, 'FNC엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/정해인"}'::jsonb, '{"filmography_highlights": ["밥 잘 사주는 예쁜 누나", "상속자들", "그들이 사는 세상"], "awards": ["JTBC 연기대상 남자 우수연기상"], "genre_speciality": ["로맨스", "드라마", "코미디"], "debut_work": "야구단의 사생활", "agency": "FNC엔터테인먼트", "notable_collaborations": ["안판석", "김은숙"]}'::jsonb, '실제 데이터'),

('actor_lee_dong_wook', '이동욱', '1981-11-06', 'male', 'actor', NULL, NULL, ARRAY['이동욱'], '한국', NULL, '12:00', 1999, '킹콩 by 스타쉽', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이동욱"}'::jsonb, '{"filmography_highlights": ["도깨비", "구미호뎐", "나쁜 녀석들"], "awards": ["tvN10 어워즈 남자 인기상"], "genre_speciality": ["판타지", "액션", "스릴러"], "debut_work": "학교 3", "agency": "킹콩 by 스타쉽", "notable_collaborations": ["김은숙", "한정환"]}'::jsonb, '실제 데이터'),

('actor_han_ga_in', '한가인', '1982-02-02', 'female', 'actor', NULL, NULL, ARRAY['한가인'], '한국', NULL, '12:00', 2002, 'BH 엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/한가인"}'::jsonb, '{"filmography_highlights": ["달의 연인", "황진이", "내 이름은 김삼순"], "awards": ["SBS 연기대상 최우수상"], "genre_speciality": ["로맨스", "사극", "멜로"], "debut_work": "논스톱 4", "agency": "BH 엔터테인먼트", "notable_collaborations": ["김은숙", "장태유"]}'::jsonb, '실제 데이터'),

('actor_won_bin', '원빈', '1977-11-10', 'male', 'actor', NULL, NULL, ARRAY['원빈'], '한국', NULL, '12:00', 1997, '이든나인', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/원빈"}'::jsonb, '{"filmography_highlights": ["아저씨", "가을동화", "태극기 휘날리며"], "awards": ["백상예술대상 영화부문 남우주연상"], "genre_speciality": ["액션", "멜로", "전쟁"], "debut_work": "여명의 눈동자", "agency": "이든나인", "notable_collaborations": ["이정범", "강제규"]}'::jsonb, '실제 데이터'),

('actor_jun_do_yeon', '전도연', '1973-02-11', 'female', 'actor', NULL, NULL, ARRAY['전도연'], '한국', NULL, '12:00', 1991, '매니지먼트 숲', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/전도연"}'::jsonb, '{"filmography_highlights": ["밀양", "너는 내 운명", "더 핸드메이든"], "awards": ["칸 영화제 여우주연상"], "genre_speciality": ["드라마", "멜로", "스릴러"], "debut_work": "젊은이의 양지", "agency": "매니지먼트 숲", "notable_collaborations": ["이창동", "박찬욱"]}'::jsonb, '실제 데이터')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();