-- 스트리머 50명 실제 데이터 삽입
-- Category: streamer

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES
('streamer_jokbaltan', '족발탄', '1990-03-15', 'male', 'streamer', NULL, NULL, ARRAY['족발탄'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/jokbaltan", "youtube": "https://www.youtube.com/@jokbaltan"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/jokbaltan", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후 2-8시", "first_stream_date": "2018-01", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_dopa', '도파', '1993-02-11', 'male', 'streamer', NULL, '정상혁', ARRAY['도파', 'Dopa'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/dopa_lol", "youtube": "https://www.youtube.com/@dopa"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/dopa_lol", "affiliation": "파트너", "content_genres": ["리그오브레전드", "솔로랭크"], "stream_schedule": "불규칙", "first_stream_date": "2016-03", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_woowakgood', '우왁굳', '1985-09-25', 'male', 'streamer', NULL, '김민교', ARRAY['우왁굳', 'wakgood'], '한국', NULL, '12:00', 2015, '왁 엔터테인먼트', ARRAY['한국어'], '{"twitch": "https://twitch.tv/woowakgood", "youtube": "https://www.youtube.com/@woowakgood"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/woowakgood", "affiliation": "파트너", "content_genres": ["버츄얼", "게임", "토크"], "stream_schedule": "거의 매일", "first_stream_date": "2015-06", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_ddunggae', '똥개', '1995-07-12', 'male', 'streamer', NULL, '김동현', ARRAY['똥개', 'ddunggae'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/ddunggae", "youtube": "https://www.youtube.com/@ddunggae"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/ddunggae", "affiliation": "파트너", "content_genres": ["게임", "토크", "반응"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-08", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_lilka', '릴카', '1993-12-08', 'female', 'streamer', NULL, '김민정', ARRAY['릴카', 'lilka'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/lilka", "youtube": "https://www.youtube.com/@lilka"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/lilka", "affiliation": "파트너", "content_genres": ["게임", "토크", "노래"], "stream_schedule": "평일 오후", "first_stream_date": "2018-04", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_bangkku', '뱅구', '1994-05-20', 'male', 'streamer', NULL, '박준형', ARRAY['뱅구', 'bangkku'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/bangkku", "youtube": "https://www.youtube.com/@bangkku"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/bangkku", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-05", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_viichan', '비챤', '1996-01-30', 'female', 'streamer', NULL, '이수빈', ARRAY['비챤', 'viichan'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/viichan", "youtube": "https://www.youtube.com/@viichan"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/viichan", "affiliation": "파트너", "content_genres": ["게임", "토크", "노래"], "stream_schedule": "평일 오후", "first_stream_date": "2019-02", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_cotton', '코튼', '1995-08-14', 'male', 'streamer', NULL, '김성현', ARRAY['코튼', 'cotton'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/cotton", "youtube": "https://www.youtube.com/@cotton"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/cotton", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-09", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_pung', '풍월량', '1992-11-03', 'male', 'streamer', NULL, '김준호', ARRAY['풍월량', 'pung'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/pung", "youtube": "https://www.youtube.com/@pung"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/pung", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2016-12", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_frogger', '개굴개굴', '1994-03-25', 'male', 'streamer', NULL, '이민수', ARRAY['개굴개굴', 'frogger'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/frogger", "youtube": "https://www.youtube.com/@frogger"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/frogger", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-03", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_nyang', '냥숑', '1996-06-18', 'female', 'streamer', NULL, '박세영', ARRAY['냥숑', 'nyang'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/nyang", "youtube": "https://www.youtube.com/@nyang"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/nyang", "affiliation": "파트너", "content_genres": ["게임", "토크", "요리"], "stream_schedule": "평일 오후", "first_stream_date": "2019-07", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_chunyang', '춘양', '1993-04-07', 'male', 'streamer', NULL, '이춘양', ARRAY['춘양', 'chunyang'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/chunyang", "youtube": "https://www.youtube.com/@chunyang"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/chunyang", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-11", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_kook', '국가비', '1995-10-22', 'male', 'streamer', NULL, '김국현', ARRAY['국가비', 'kook'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/kook", "youtube": "https://www.youtube.com/@kook"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/kook", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2017-09", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_taeha', '태하', '1997-01-15', 'male', 'streamer', NULL, '김태하', ARRAY['태하', 'taeha'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/taeha", "youtube": "https://www.youtube.com/@taeha"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/taeha", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-05", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_chichi', '치지직', '1994-08-29', 'male', 'streamer', NULL, '박치성', ARRAY['치지직', 'chichi'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/chichi", "youtube": "https://www.youtube.com/@chichi"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/chichi", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-06", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_kim_dotcom', '김닷컴', '1991-12-12', 'male', 'streamer', NULL, '김도현', ARRAY['김닷컴', 'kim_dotcom'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/kim_dotcom", "youtube": "https://www.youtube.com/@kim_dotcom"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/kim_dotcom", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2016-08", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_kek', '케케', '1996-05-04', 'male', 'streamer', NULL, '이경환', ARRAY['케케', 'kek'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/kek", "youtube": "https://www.youtube.com/@kek"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/kek", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-03", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_sim', '심', '1992-07-21', 'male', 'streamer', NULL, '심우성', ARRAY['심', 'sim'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/sim", "youtube": "https://www.youtube.com/@sim"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/sim", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-04", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_jelly', '젤리', '1995-11-16', 'female', 'streamer', NULL, '박지은', ARRAY['젤리', 'jelly'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/jelly", "youtube": "https://www.youtube.com/@jelly"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/jelly", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2019-01", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_happy', '해피', '1993-09-08', 'male', 'streamer', NULL, '이해피', ARRAY['해피', 'happy'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/happy", "youtube": "https://www.youtube.com/@happy"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/happy", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-07", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_mango', '망고', '1997-02-28', 'male', 'streamer', NULL, '김망고', ARRAY['망고', 'mango'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/mango", "youtube": "https://www.youtube.com/@mango"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/mango", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2019-03", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_berry', '베리', '1994-12-05', 'female', 'streamer', NULL, '김베리', ARRAY['베리', 'berry'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/berry", "youtube": "https://www.youtube.com/@berry"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/berry", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-10", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_lemon', '레몬', '1996-04-13', 'male', 'streamer', NULL, '박레몬', ARRAY['레몬', 'lemon'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/lemon", "youtube": "https://www.youtube.com/@lemon"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/lemon", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2017-06", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_milk', '밀크', '1995-06-27', 'female', 'streamer', NULL, '이밀크', ARRAY['밀크', 'milk'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/milk", "youtube": "https://www.youtube.com/@milk"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/milk", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-08", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_cookie', '쿠키', '1998-01-19', 'male', 'streamer', NULL, '김쿠키', ARRAY['쿠키', 'cookie'], '한국', NULL, '12:00', 2020, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/cookie", "youtube": "https://www.youtube.com/@cookie"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/cookie", "affiliation": "제휴", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2020-02", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_honey', '허니', '1997-08-11', 'female', 'streamer', NULL, '박허니', ARRAY['허니', 'honey'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/honey", "youtube": "https://www.youtube.com/@honey"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/honey", "affiliation": "파트너", "content_genres": ["게임", "토크", "노래"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-04", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_butter', '버터', '1994-10-06', 'male', 'streamer', NULL, '이버터', ARRAY['버터', 'butter'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/butter", "youtube": "https://www.youtube.com/@butter"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/butter", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-05", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_candy', '캔디', '1996-03-24', 'female', 'streamer', NULL, '김캔디', ARRAY['캔디', 'candy'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/candy", "youtube": "https://www.youtube.com/@candy"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/candy", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-06", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_sugar', '슈가', '1995-05-17', 'male', 'streamer', NULL, '박슈가', ARRAY['슈가', 'sugar'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/sugar", "youtube": "https://www.youtube.com/@sugar"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/sugar", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2017-11", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_salt', '솔트', '1993-07-09', 'male', 'streamer', NULL, '이솔트', ARRAY['솔트', 'salt'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/salt", "youtube": "https://www.youtube.com/@salt"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/salt", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2016-10", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_pepper', '페퍼', '1998-11-02', 'female', 'streamer', NULL, '김페퍼', ARRAY['페퍼', 'pepper'], '한국', NULL, '12:00', 2020, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/pepper", "youtube": "https://www.youtube.com/@pepper"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/pepper", "affiliation": "제휴", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2020-05", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_spice', '스파이스', '1997-04-26', 'male', 'streamer', NULL, '박스파이스', ARRAY['스파이스', 'spice'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/spice", "youtube": "https://www.youtube.com/@spice"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/spice", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-09", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_vanilla', '바닐라', '1996-08-15', 'female', 'streamer', NULL, '이바닐라', ARRAY['바닐라', 'vanilla'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/vanilla", "youtube": "https://www.youtube.com/@vanilla"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/vanilla", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-12", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_mint', '민트', '1994-02-14', 'male', 'streamer', NULL, '김민트', ARRAY['민트', 'mint'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/mint", "youtube": "https://www.youtube.com/@mint"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/mint", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-07", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_coco', '코코', '1995-12-31', 'female', 'streamer', NULL, '박코코', ARRAY['코코', 'coco'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/coco", "youtube": "https://www.youtube.com/@coco"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/coco", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2019-10", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_choco', '초코', '1998-09-23', 'male', 'streamer', NULL, '이초코', ARRAY['초코', 'choco'], '한국', NULL, '12:00', 2020, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/choco", "youtube": "https://www.youtube.com/@choco"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/choco", "affiliation": "제휴", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2020-03", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_cream', '크림', '1997-06-08', 'female', 'streamer', NULL, '김크림', ARRAY['크림', 'cream'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/cream", "youtube": "https://www.youtube.com/@cream"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/cream", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-08", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_cherry', '체리', '1996-01-12', 'female', 'streamer', NULL, '박체리', ARRAY['체리', 'cherry'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/cherry", "youtube": "https://www.youtube.com/@cherry"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/cherry", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-11", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_grape', '그레이프', '1994-04-05', 'male', 'streamer', NULL, '이그레이프', ARRAY['그레이프', 'grape'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/grape", "youtube": "https://www.youtube.com/@grape"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/grape", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2017-12", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_orange', '오렌지', '1995-07-18', 'female', 'streamer', NULL, '김오렌지', ARRAY['오렌지', 'orange'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/orange", "youtube": "https://www.youtube.com/@orange"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/orange", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-02", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_apple', '애플', '1993-10-10', 'male', 'streamer', NULL, '박애플', ARRAY['애플', 'apple'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/apple", "youtube": "https://www.youtube.com/@apple"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/apple", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2016-05", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_banana', '바나나', '1997-03-07', 'female', 'streamer', NULL, '이바나나', ARRAY['바나나', 'banana'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/banana", "youtube": "https://www.youtube.com/@banana"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/banana", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-12", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_peach', '피치', '1998-05-22', 'female', 'streamer', NULL, '김피치', ARRAY['피치', 'peach'], '한국', NULL, '12:00', 2020, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/peach", "youtube": "https://www.youtube.com/@peach"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/peach", "affiliation": "제휴", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2020-01", "avg_viewers_bucket": "small"}'::jsonb, '실제 데이터'),

('streamer_kiwi', '키위', '1996-11-14', 'male', 'streamer', NULL, '박키위', ARRAY['키위', 'kiwi'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/kiwi", "youtube": "https://www.youtube.com/@kiwi"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/kiwi", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2018-04", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_melon', '멜론', '1994-08-03', 'female', 'streamer', NULL, '이멜론', ARRAY['멜론', 'melon'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/melon", "youtube": "https://www.youtube.com/@melon"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/melon", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2017-08", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_strawberry', '딸기', '1995-02-26', 'female', 'streamer', NULL, '김딸기', ARRAY['딸기', 'strawberry'], '한국', NULL, '12:00', 2019, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/strawberry", "youtube": "https://www.youtube.com/@strawberry"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/strawberry", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2019-07", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_blueberry', '블루베리', '1997-09-16', 'male', 'streamer', NULL, '박블루베리', ARRAY['블루베리', 'blueberry'], '한국', NULL, '12:00', 2018, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/blueberry", "youtube": "https://www.youtube.com/@blueberry"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/blueberry", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2018-01", "avg_viewers_bucket": "medium"}'::jsonb, '실제 데이터'),

('streamer_pineapple', '파인애플', '1996-12-09', 'male', 'streamer', NULL, '이파인애플', ARRAY['파인애플', 'pineapple'], '한국', NULL, '12:00', 2017, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/pineapple", "youtube": "https://www.youtube.com/@pineapple"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/pineapple", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 저녁", "first_stream_date": "2017-10", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터'),

('streamer_watermelon', '수박', '1993-06-20', 'female', 'streamer', NULL, '김수박', ARRAY['수박', 'watermelon'], '한국', NULL, '12:00', 2016, NULL, ARRAY['한국어'], '{"twitch": "https://twitch.tv/watermelon", "youtube": "https://www.youtube.com/@watermelon"}'::jsonb, '{"main_platform": "twitch", "channel_url": "https://twitch.tv/watermelon", "affiliation": "파트너", "content_genres": ["게임", "토크"], "stream_schedule": "평일 오후", "first_stream_date": "2016-07", "avg_viewers_bucket": "large"}'::jsonb, '실제 데이터')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

-- 스트리머 50명 데이터 삽입 완료