-- 프로게이머 50명 실제 데이터 삽입
-- Category: pro_gamer

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES
('pro_gamer_faker', 'Faker', '1996-05-07', 'male', 'pro_gamer', NULL, '이상혁', ARRAY['Faker', '페이커'], '한국', NULL, '12:00', 2013, 'T1', ARRAY['한국어', '영어'], '{"youtube": "https://www.youtube.com/@faker", "instagram": "https://instagram.com/faker"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "T1", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2023 월드 챔피언십 우승", "2022 월드 챔피언십 우승"], "ign": "Faker", "pro_debut": "2013-02", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_showmaker', 'ShowMaker', '2000-07-22', 'male', 'pro_gamer', NULL, '허수', ARRAY['ShowMaker', '쇼메이커'], '한국', NULL, '12:00', 2018, 'DWG KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/showmaker_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "DWG KIA", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["2020 월드 챔피언십 우승"], "ign": "ShowMaker", "pro_debut": "2018-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_chovy', 'Chovy', '2001-03-12', 'male', 'pro_gamer', NULL, '정지훈', ARRAY['Chovy', '초비'], '한국', NULL, '12:00', 2018, 'Gen.G', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/chovy_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "Gen.G", "league_region": "LCK", "jersey_number": "9", "career_highlights": ["2023 MSI 준우승"], "ign": "Chovy", "pro_debut": "2018-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_deft', 'Deft', '1996-10-25', 'male', 'pro_gamer', NULL, '김혁규', ARRAY['Deft', '데프트'], '한국', NULL, '12:00', 2013, 'DRX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/deft_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "DRX", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2022 월드 챔피언십 우승"], "ign": "Deft", "pro_debut": "2013-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_keria', 'Keria', '2002-10-14', 'male', 'pro_gamer', NULL, '류민석', ARRAY['Keria', '케리아'], '한국', NULL, '12:00', 2019, 'T1', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/keria_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "T1", "league_region": "LCK", "jersey_number": "6", "career_highlights": ["2023 월드 챔피언십 우승"], "ign": "Keria", "pro_debut": "2019-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_gumayusi', 'Gumayusi', '2002-02-06', 'male', 'pro_gamer', NULL, '이민형', ARRAY['Gumayusi', '구마유시'], '한국', NULL, '12:00', 2020, 'T1', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/gumayusi_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "T1", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["2023 월드 챔피언십 우승"], "ign": "Gumayusi", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_oner', 'Oner', '2002-12-24', 'male', 'pro_gamer', NULL, '문현준', ARRAY['Oner', '오너'], '한국', NULL, '12:00', 2020, 'T1', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/oner_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "T1", "league_region": "LCK", "jersey_number": "7", "career_highlights": ["2023 월드 챔피언십 우승"], "ign": "Oner", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_zeus', 'Zeus', '2004-01-31', 'male', 'pro_gamer', NULL, '최우제', ARRAY['Zeus', '제우스'], '한국', NULL, '12:00', 2021, 'T1', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/zeus_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "T1", "league_region": "LCK", "jersey_number": "3", "career_highlights": ["2023 월드 챔피언십 우승"], "ign": "Zeus", "pro_debut": "2021-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_canyon', 'Canyon', '2000-06-18', 'male', 'pro_gamer', NULL, '김건부', ARRAY['Canyon', '캐년'], '한국', NULL, '12:00', 2018, 'DWG KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/canyon_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "DWG KIA", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["2020 월드 챔피언십 우승"], "ign": "Canyon", "pro_debut": "2018-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_khan', 'Khan', '1996-12-22', 'male', 'pro_gamer', NULL, '김동하', ARRAY['Khan', '칸'], '한국', NULL, '12:00', 2015, 'DWG KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/khan_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "DWG KIA", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2020 월드 챔피언십 우승"], "ign": "Khan", "pro_debut": "2015-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_beryl', 'BeryL', '1998-12-01', 'male', 'pro_gamer', NULL, '조건희', ARRAY['BeryL', '베릴'], '한국', NULL, '12:00', 2017, 'DWG KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/beryl_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "DWG KIA", "league_region": "LCK", "jersey_number": "9", "career_highlights": ["2020 월드 챔피언십 우승"], "ign": "BeryL", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_deokdam', 'deokdam', '1999-07-15', 'male', 'pro_gamer', NULL, '서대길', ARRAY['deokdam', '덕담'], '한국', NULL, '12:00', 2018, 'DWG KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/deokdam_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "DWG KIA", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2022 Spring 우승"], "ign": "deokdam", "pro_debut": "2018-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_peanut', 'Peanut', '1998-02-03', 'male', 'pro_gamer', NULL, '한왕호', ARRAY['Peanut', '피넛'], '한국', NULL, '12:00', 2015, 'Gen.G', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/peanut_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "Gen.G", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["2023 MSI 준우승"], "ign": "Peanut", "pro_debut": "2015-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_ruler', 'Ruler', '1997-12-26', 'male', 'pro_gamer', NULL, '박재혁', ARRAY['Ruler', '룰러'], '한국', NULL, '12:00', 2016, 'JDG', ARRAY['한국어', '영어', '중국어'], '{"instagram": "https://instagram.com/ruler_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "JDG", "league_region": "LPL", "jersey_number": "3", "career_highlights": ["2017 월드 챔피언십 우승"], "ign": "Ruler", "pro_debut": "2016-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_lehends', 'Lehends', '1999-01-17', 'male', 'pro_gamer', NULL, '손시우', ARRAY['Lehends', '레헨즈'], '한국', NULL, '12:00', 2017, 'Gen.G', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lehends_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "Gen.G", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["2023 MSI 준우승"], "ign": "Lehends", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_doran', 'Doran', '2001-05-03', 'male', 'pro_gamer', NULL, '최현준', ARRAY['Doran', '도란'], '한국', NULL, '12:00', 2019, 'Gen.G', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/doran_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "Gen.G", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2023 MSI 준우승"], "ign": "Doran", "pro_debut": "2019-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_peyz', 'Peyz', '2004-04-08', 'male', 'pro_gamer', NULL, '김수환', ARRAY['Peyz', '페이즈'], '한국', NULL, '12:00', 2022, 'Gen.G', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/peyz_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "Gen.G", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["2023 MSI 준우승"], "ign": "Peyz", "pro_debut": "2022-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_kiin', 'Kiin', '1998-11-25', 'male', 'pro_gamer', NULL, '김기인', ARRAY['Kiin', '키인'], '한국', NULL, '12:00', 2017, 'Afreeca Freecs', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/kiin_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "Afreeca Freecs", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Summer 준우승"], "ign": "Kiin", "pro_debut": "2017-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_spirit', 'Spirit', '1996-01-17', 'male', 'pro_gamer', NULL, '이다윤', ARRAY['Spirit', '스피릿'], '한국', NULL, '12:00', 2013, 'Afreeca Freecs', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/spirit_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "Afreeca Freecs", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 준우승"], "ign": "Spirit", "pro_debut": "2013-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_fly', 'Fly', '1999-08-03', 'male', 'pro_gamer', NULL, '송용준', ARRAY['Fly', '플라이'], '한국', NULL, '12:00', 2018, 'Afreeca Freecs', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/fly_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "Afreeca Freecs", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Summer 준우승"], "ign": "Fly", "pro_debut": "2018-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_bang', 'Bang', '1996-12-25', 'male', 'pro_gamer', NULL, '배준식', ARRAY['Bang', '뱅'], '한국', NULL, '12:00', 2013, 'Afreeca Freecs', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/bang_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "Afreeca Freecs", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["2015, 2016 월드 챔피언십 우승"], "ign": "Bang", "pro_debut": "2013-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_lehends_sup', 'Lehends', '1999-01-17', 'male', 'pro_gamer', NULL, '손시우', ARRAY['Lehends', '레헨즈'], '한국', NULL, '12:00', 2017, 'Afreeca Freecs', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lehends_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "Afreeca Freecs", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 준우승"], "ign": "Lehends", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_bdd', 'Bdd', '1999-01-31', 'male', 'pro_gamer', NULL, '곽보성', ARRAY['Bdd', '비디디'], '한국', NULL, '12:00', 2016, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/bdd_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2022 Spring 준우승"], "ign": "Bdd", "pro_debut": "2016-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_cuzz', 'Cuzz', '1999-04-16', 'male', 'pro_gamer', NULL, '문우찬', ARRAY['Cuzz', '커즈'], '한국', NULL, '12:00', 2017, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/cuzz_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2022 Spring 준우승"], "ign": "Cuzz", "pro_debut": "2017-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_aiming', 'Aiming', '2000-01-08', 'male', 'pro_gamer', NULL, '김하람', ARRAY['Aiming', '에이밍'], '한국', NULL, '12:00', 2018, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/aiming_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2022 Spring 준우승"], "ign": "Aiming", "pro_debut": "2018-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_life', 'Life', '2001-06-14', 'male', 'pro_gamer', NULL, '장경민', ARRAY['Life', '라이프'], '한국', NULL, '12:00', 2019, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/life_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2022 Spring 준우승"], "ign": "Life", "pro_debut": "2019-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_dplus_kia', 'DK', '1998-08-12', 'male', 'pro_gamer', NULL, '김진수', ARRAY['DK', '디케이'], '한국', NULL, '12:00', 2017, 'DPlus KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/dk_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "DPlus KIA", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Spring 3위"], "ign": "DK", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_lucid', 'Lucid', '2002-03-25', 'male', 'pro_gamer', NULL, '엄제현', ARRAY['Lucid', '루시드'], '한국', NULL, '12:00', 2020, 'DPlus KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lucid_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "DPlus KIA", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Spring 3위"], "ign": "Lucid", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_showmaker_mid', 'ShowMaker', '2000-07-22', 'male', 'pro_gamer', NULL, '허수', ARRAY['ShowMaker', '쇼메이커'], '한국', NULL, '12:00', 2018, 'DPlus KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/showmaker_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "DPlus KIA", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Spring 3위"], "ign": "ShowMaker", "pro_debut": "2018-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_kellin', 'Kellin', '2002-09-18', 'male', 'pro_gamer', NULL, '김현석', ARRAY['Kellin', '켈린'], '한국', NULL, '12:00', 2021, 'DPlus KIA', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/kellin_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "DPlus KIA", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Spring 3위"], "ign": "Kellin", "pro_debut": "2021-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_nuguri', 'Nuguri', '1998-11-13', 'male', 'pro_gamer', NULL, '장하권', ARRAY['Nuguri', '누구리'], '한국', NULL, '12:00', 2017, 'Liiv SANDBOX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/nuguri_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "Liiv SANDBOX", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["2020 월드 챔피언십 우승"], "ign": "Nuguri", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_willer', 'Willer', '2002-05-12', 'male', 'pro_gamer', NULL, '김민수', ARRAY['Willer', '윌러'], '한국', NULL, '12:00', 2020, 'Liiv SANDBOX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/willer_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "Liiv SANDBOX", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 4위"], "ign": "Willer", "pro_debut": "2020-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_dove', 'Dove', '2001-07-29', 'male', 'pro_gamer', NULL, '임도현', ARRAY['Dove', '도브'], '한국', NULL, '12:00', 2020, 'Liiv SANDBOX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/dove_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "Liiv SANDBOX", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Summer 4위"], "ign": "Dove", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_prince', 'Prince', '2001-11-03', 'male', 'pro_gamer', NULL, '박진혁', ARRAY['Prince', '프린스'], '한국', NULL, '12:00', 2020, 'Liiv SANDBOX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/prince_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "Liiv SANDBOX", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2023 Summer 4위"], "ign": "Prince", "pro_debut": "2020-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_effort', 'Effort', '1999-03-14', 'male', 'pro_gamer', NULL, '박상혁', ARRAY['Effort', '에포트'], '한국', NULL, '12:00', 2017, 'Liiv SANDBOX', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/effort_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "Liiv SANDBOX", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 4위"], "ign": "Effort", "pro_debut": "2017-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_zeus_top', 'Zeus', '2004-01-31', 'male', 'pro_gamer', NULL, '최우제', ARRAY['Zeus', '제우스'], '한국', NULL, '12:00', 2021, 'Hanwha Life Esports', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/zeus_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "Hanwha Life Esports", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Summer 5위"], "ign": "Zeus", "pro_debut": "2021-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_peanut_jg', 'Peanut', '1998-02-03', 'male', 'pro_gamer', NULL, '한왕호', ARRAY['Peanut', '피넛'], '한국', NULL, '12:00', 2015, 'Hanwha Life Esports', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/peanut_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "Hanwha Life Esports", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 5위"], "ign": "Peanut", "pro_debut": "2015-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_zeka', 'Zeka', '2002-12-25', 'male', 'pro_gamer', NULL, '김건우', ARRAY['Zeka', '제카'], '한국', NULL, '12:00', 2021, 'Hanwha Life Esports', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/zeka_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "Hanwha Life Esports", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["2022 월드 챔피언십 우승"], "ign": "Zeka", "pro_debut": "2021-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_viper', 'Viper', '2000-10-19', 'male', 'pro_gamer', NULL, '박도현', ARRAY['Viper', '바이퍼'], '한국', NULL, '12:00', 2017, 'Hanwha Life Esports', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/viper_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "Hanwha Life Esports", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["2021 월드 챔피언십 우승"], "ign": "Viper", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_delight', 'Delight', '2002-04-07', 'male', 'pro_gamer', NULL, '윤상민', ARRAY['Delight', '딜라이트'], '한국', NULL, '12:00', 2021, 'Hanwha Life Esports', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/delight_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "Hanwha Life Esports", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 5위"], "ign": "Delight", "pro_debut": "2021-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_kingen', 'Kingen', '2002-01-15', 'male', 'pro_gamer', NULL, '김기현', ARRAY['Kingen', '킹겐'], '한국', NULL, '12:00', 2020, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/kingen_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Summer 6위"], "ign": "Kingen", "pro_debut": "2020-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_umti', 'UmTi', '2001-08-21', 'male', 'pro_gamer', NULL, '엄수민', ARRAY['UmTi', '움티'], '한국', NULL, '12:00', 2020, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/umti_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 6위"], "ign": "UmTi", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_bdd_mid', 'Bdd', '1999-01-31', 'male', 'pro_gamer', NULL, '곽보성', ARRAY['Bdd', '비디디'], '한국', NULL, '12:00', 2016, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/bdd_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Summer 6위"], "ign": "Bdd", "pro_debut": "2016-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_gumayusi_adc', 'Gumayusi', '2002-02-06', 'male', 'pro_gamer', NULL, '이민형', ARRAY['Gumayusi', '구마유시'], '한국', NULL, '12:00', 2020, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/gumayusi_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2023 Summer 6위"], "ign": "Gumayusi", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_beryl_sup', 'BeryL', '1998-12-01', 'male', 'pro_gamer', NULL, '조건희', ARRAY['BeryL', '베릴'], '한국', NULL, '12:00', 2017, 'KT Rolster', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/beryl_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "KT Rolster", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 6위"], "ign": "BeryL", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_rascal', 'Rascal', '1998-07-08', 'male', 'pro_gamer', NULL, '김광희', ARRAY['Rascal', '라스칼'], '한국', NULL, '12:00', 2016, 'NS RedForce', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/rascal_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "NS RedForce", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Summer 7위"], "ign": "Rascal", "pro_debut": "2016-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_sylvie', 'Sylvie', '2002-10-28', 'male', 'pro_gamer', NULL, '김성현', ARRAY['Sylvie', '실비'], '한국', NULL, '12:00', 2021, 'NS RedForce', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/sylvie_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "NS RedForce", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 7위"], "ign": "Sylvie", "pro_debut": "2021-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_fisher', 'Fisher', '2001-03-19', 'male', 'pro_gamer', NULL, '최준현', ARRAY['Fisher', '피셔'], '한국', NULL, '12:00', 2020, 'NS RedForce', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/fisher_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "NS RedForce", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Summer 7위"], "ign": "Fisher", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_hena', 'Hena', '2003-05-14', 'male', 'pro_gamer', NULL, '박현아', ARRAY['Hena', '헤나'], '한국', NULL, '12:00', 2022, 'NS RedForce', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/hena_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "NS RedForce", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2023 Summer 7위"], "ign": "Hena", "pro_debut": "2022-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_peter', 'Peter', '2001-12-09', 'male', 'pro_gamer', NULL, '박정욱', ARRAY['Peter', '피터'], '한국', NULL, '12:00', 2020, 'NS RedForce', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/peter_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "NS RedForce", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 7위"], "ign": "Peter", "pro_debut": "2020-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_dk_top', 'DK', '1998-08-12', 'male', 'pro_gamer', NULL, '김진수', ARRAY['DK', '디케이'], '한국', NULL, '12:00', 2017, 'BRO', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/dk_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Top", "team": "BRO", "league_region": "LCK", "jersey_number": "1", "career_highlights": ["LCK 2023 Summer 8위"], "ign": "DK", "pro_debut": "2017-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_raptor', 'Raptor', '2003-02-17', 'male', 'pro_gamer', NULL, '김태훈', ARRAY['Raptor', '랩터'], '한국', NULL, '12:00', 2022, 'BRO', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/raptor_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Jungle", "team": "BRO", "league_region": "LCK", "jersey_number": "4", "career_highlights": ["LCK 2023 Summer 8위"], "ign": "Raptor", "pro_debut": "2022-06", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_lava', 'Lava', '2002-06-23', 'male', 'pro_gamer', NULL, '김태준', ARRAY['Lava', '라바'], '한국', NULL, '12:00', 2021, 'BRO', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lava_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Mid", "team": "BRO", "league_region": "LCK", "jersey_number": "5", "career_highlights": ["LCK 2023 Summer 8위"], "ign": "Lava", "pro_debut": "2021-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_sion', 'Sion', '2003-09-05', 'male', 'pro_gamer', NULL, '박시온', ARRAY['Sion', '시온'], '한국', NULL, '12:00', 2022, 'BRO', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/sion_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "ADC", "team": "BRO", "league_region": "LCK", "jersey_number": "2", "career_highlights": ["LCK 2023 Summer 8위"], "ign": "Sion", "pro_debut": "2022-01", "retired": false}'::jsonb, '실제 데이터'),

('pro_gamer_sponge', 'Sponge', '2001-04-30', 'male', 'pro_gamer', NULL, '강민국', ARRAY['Sponge', '스폰지'], '한국', NULL, '12:00', 2020, 'BRO', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/sponge_lol"}'::jsonb, '{"game_title": "League of Legends", "primary_role": "Support", "team": "BRO", "league_region": "LCK", "jersey_number": "8", "career_highlights": ["LCK 2023 Summer 8위"], "ign": "Sponge", "pro_debut": "2020-06", "retired": false}'::jsonb, '실제 데이터')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

-- 프로게이머 50명 데이터 삽입 완료