-- 아이돌 멤버 50명 실제 데이터 삽입
-- Category: idol_member

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES
('idol_member_rm', 'RM', '1994-09-12', 'male', 'idol_member', NULL, '김남준', ARRAY['RM', '랩몬스터', 'Rap Monster'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/rkive", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["rap", "leader"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["Indigo 앨범", "Right Place, Wrong Person"]}'::jsonb, '실제 데이터'),

('idol_member_jin', 'Jin', '1992-12-04', 'male', 'idol_member', NULL, '김석진', ARRAY['Jin', '진'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/jin", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["vocal", "visual"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["The Astronaut", "잠시", "Tonight"]}'::jsonb, '실제 데이터'),

('idol_member_suga', 'SUGA', '1993-03-09', 'male', 'idol_member', NULL, '민윤기', ARRAY['SUGA', '슈가', 'Agust D'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/agustd", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["rap", "producer"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["D-DAY", "Agust D", "Haegeum"]}'::jsonb, '실제 데이터'),

('idol_member_j_hope', 'j-hope', '1994-02-18', 'male', 'idol_member', NULL, '정호석', ARRAY['j-hope', '제이홉'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/uarmyhope", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["rap", "dance", "sub_vocal"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["Jack In The Box", "Hope World", "More"]}'::jsonb, '실제 데이터'),

('idol_member_jimin', 'Jimin', '1995-10-13', 'male', 'idol_member', NULL, '박지민', ARRAY['Jimin', '지민'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/j.m", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["vocal", "dance"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["FACE", "Like Crazy", "Set Me Free Pt.2"]}'::jsonb, '실제 데이터'),

('idol_member_v', 'V', '1995-12-30', 'male', 'idol_member', NULL, '김태형', ARRAY['V', '뷔'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/thv", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["vocal", "visual"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["Layover", "Slow Dancing", "Love Me Again"]}'::jsonb, '실제 데이터'),

('idol_member_jungkook', 'Jung Kook', '1997-09-01', 'male', 'idol_member', NULL, '전정국', ARRAY['Jung Kook', '정국'], '한국', NULL, '12:00', 2013, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/jungkook", "youtube": "https://www.youtube.com/@bts"}'::jsonb, '{"group_name": "BTS", "position": ["vocal", "dance", "rapper"], "debut_date": "2013-06-13", "label": "HYBE 엔터테인먼트", "fandom_name": "ARMY", "sub_units": [], "solo_activities": ["GOLDEN", "Seven", "3D"]}'::jsonb, '실제 데이터'),

('idol_member_jennie', 'JENNIE', '1996-01-16', 'female', 'idol_member', NULL, '김제니', ARRAY['JENNIE', '제니'], '한국', NULL, '12:00', 2016, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/jennierubyjane", "youtube": "https://www.youtube.com/@BLACKPINK"}'::jsonb, '{"group_name": "BLACKPINK", "position": ["rap", "vocal"], "debut_date": "2016-08-08", "label": "YG엔터테인먼트", "fandom_name": "BLINK", "sub_units": [], "solo_activities": ["SOLO", "You & Me", "The Idol OST"]}'::jsonb, '실제 데이터'),

('idol_member_jisoo', 'JISOO', '1995-01-03', 'female', 'idol_member', NULL, '김지수', ARRAY['JISOO', '지수'], '한국', NULL, '12:00', 2016, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/sooyaaa__", "youtube": "https://www.youtube.com/@BLACKPINK"}'::jsonb, '{"group_name": "BLACKPINK", "position": ["vocal", "visual"], "debut_date": "2016-08-08", "label": "YG엔터테인먼트", "fandom_name": "BLINK", "sub_units": [], "solo_activities": ["ME", "Flower", "All Eyes On Me"]}'::jsonb, '실제 데이터'),

('idol_member_rose', 'ROSÉ', '1997-02-11', 'female', 'idol_member', NULL, '박채영', ARRAY['ROSÉ', '로제'], '뉴질랜드', NULL, '12:00', 2016, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/roses_are_rosie", "youtube": "https://www.youtube.com/@BLACKPINK"}'::jsonb, '{"group_name": "BLACKPINK", "position": ["vocal", "lead_dance"], "debut_date": "2016-08-08", "label": "YG엔터테인먼트", "fandom_name": "BLINK", "sub_units": [], "solo_activities": ["R", "On The Ground", "Gone"]}'::jsonb, '실제 데이터'),

('idol_member_lisa', 'LISA', '1997-03-27', 'female', 'idol_member', NULL, '라리사 마노반', ARRAY['LISA', '리사'], '태국', NULL, '12:00', 2016, 'YG엔터테인먼트', ARRAY['한국어', '영어', '태국어'], '{"instagram": "https://instagram.com/lalalalisa_m", "youtube": "https://www.youtube.com/@BLACKPINK"}'::jsonb, '{"group_name": "BLACKPINK", "position": ["rap", "dance", "vocal"], "debut_date": "2016-08-08", "label": "YG엔터테인먼트", "fandom_name": "BLINK", "sub_units": [], "solo_activities": ["LALISA", "Money", "SG"]}'::jsonb, '실제 데이터'),

('idol_member_nayeon', 'NAYEON', '1995-09-22', 'female', 'idol_member', NULL, '임나연', ARRAY['NAYEON', '나연'], '한국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/nayeonyny", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "lead_vocal", "center"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": ["IM NAYEON", "POP!", "No Problem"]}'::jsonb, '실제 데이터'),

('idol_member_jeongyeon', 'JEONGYEON', '1996-11-01', 'female', 'idol_member', NULL, '유정연', ARRAY['JEONGYEON', '정연'], '한국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/jeongyeoninie", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "lead_vocal"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_momo', 'MOMO', '1996-11-09', 'female', 'idol_member', NULL, '히라이 모모', ARRAY['MOMO', '모모'], '일본', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/momo", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["dance", "vocal", "rapper"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_sana', 'SANA', '1996-12-29', 'female', 'idol_member', NULL, '미나토자키 사나', ARRAY['SANA', '사나'], '일본', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/sana_minatozaki", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "lead_dance"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_jihyo', 'JIHYO', '1997-02-01', 'female', 'idol_member', NULL, '박지효', ARRAY['JIHYO', '지효'], '한국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/jihyo_twc", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "leader", "main_vocal"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": ["ZONE", "Killin Me Good"]}'::jsonb, '실제 데이터'),

('idol_member_mina', 'MINA', '1997-03-24', 'female', 'idol_member', NULL, '묘이 미나', ARRAY['MINA', '미나'], '미국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/mina_sr_my", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "dance"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_dahyun', 'DAHYUN', '1998-05-28', 'female', 'idol_member', NULL, '김다현', ARRAY['DAHYUN', '다현'], '한국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/dahhyun", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "lead_rapper"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_chaeyoung', 'CHAEYOUNG', '1999-04-23', 'female', 'idol_member', NULL, '손채영', ARRAY['CHAEYOUNG', '채영'], '한국', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/chae_young_", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "main_rapper"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_tzuyu', 'TZUYU', '1999-06-14', 'female', 'idol_member', NULL, '주자위', ARRAY['TZUYU', '쯔위'], '대만', NULL, '12:00', 2015, 'JYP엔터테인먼트', ARRAY['한국어', '영어', '중국어'], '{"instagram": "https://instagram.com/thinkaboutzu", "youtube": "https://www.youtube.com/@TWICE"}'::jsonb, '{"group_name": "TWICE", "position": ["vocal", "lead_dance", "visual", "maknae"], "debut_date": "2015-10-20", "label": "JYP엔터테인먼트", "fandom_name": "ONCE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_irene', 'IRENE', '1991-03-29', 'female', 'idol_member', NULL, '배주현', ARRAY['IRENE', '아이린'], '한국', NULL, '12:00', 2014, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/renebaebae", "youtube": "https://www.youtube.com/@RedVelvet"}'::jsonb, '{"group_name": "Red Velvet", "position": ["vocal", "visual", "leader"], "debut_date": "2014-08-01", "label": "SM엔터테인먼트", "fandom_name": "ReVeluv", "sub_units": ["IRENE & SEULGI"], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_seulgi', 'SEULGI', '1994-02-10', 'female', 'idol_member', NULL, '강슬기', ARRAY['SEULGI', '슬기'], '한국', NULL, '12:00', 2014, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/hi_sseulgi", "youtube": "https://www.youtube.com/@RedVelvet"}'::jsonb, '{"group_name": "Red Velvet", "position": ["vocal", "main_dance"], "debut_date": "2014-08-01", "label": "SM엔터테인먼트", "fandom_name": "ReVeluv", "sub_units": ["IRENE & SEULGI"], "solo_activities": ["28 Reasons"]}'::jsonb, '실제 데이터'),

('idol_member_wendy', 'WENDY', '1994-02-21', 'female', 'idol_member', NULL, '손승완', ARRAY['WENDY', '웬디'], '한국', NULL, '12:00', 2014, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/todayis_wendy", "youtube": "https://www.youtube.com/@RedVelvet"}'::jsonb, '{"group_name": "Red Velvet", "position": ["vocal", "main_vocal"], "debut_date": "2014-08-01", "label": "SM엔터테인먼트", "fandom_name": "ReVeluv", "sub_units": [], "solo_activities": ["Like Water", "When This Rain Stops"]}'::jsonb, '실제 데이터'),

('idol_member_joy', 'JOY', '1996-09-03', 'female', 'idol_member', NULL, '박수영', ARRAY['JOY', '조이'], '한국', NULL, '12:00', 2014, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/_imyour_joy", "youtube": "https://www.youtube.com/@RedVelvet"}'::jsonb, '{"group_name": "Red Velvet", "position": ["vocal", "lead_rapper"], "debut_date": "2014-08-01", "label": "SM엔터테인먼트", "fandom_name": "ReVeluv", "sub_units": [], "solo_activities": ["Hello", "Je T\'aime"]}'::jsonb, '실제 데이터'),

('idol_member_yeri', 'YERI', '1999-03-05', 'female', 'idol_member', NULL, '김예림', ARRAY['YERI', '예리'], '한국', NULL, '12:00', 2015, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/yerimiese", "youtube": "https://www.youtube.com/@RedVelvet"}'::jsonb, '{"group_name": "Red Velvet", "position": ["vocal", "rapper", "maknae"], "debut_date": "2015-03-10", "label": "SM엔터테인먼트", "fandom_name": "ReVeluv", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_taeyeon', 'TAEYEON', '1989-03-09', 'female', 'idol_member', NULL, '김태연', ARRAY['TAEYEON', '태연'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/taeyeon_ss", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "main_vocal", "leader"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": ["TTS"], "solo_activities": ["I", "Why", "INVU"]}'::jsonb, '실제 데이터'),

('idol_member_sunny', 'SUNNY', '1989-05-15', 'female', 'idol_member', NULL, '이순규', ARRAY['SUNNY', '써니'], '미국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/sunnyday515", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_vocal"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": ["TTS"], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_tiffany', 'TIFFANY', '1989-08-01', 'female', 'idol_member', NULL, '티파니 황', ARRAY['TIFFANY', '티파니'], '미국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/tiffanyyoungofficial", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_vocal"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": ["TTS"], "solo_activities": ["I Just Wanna Dance", "Lips On Lips"]}'::jsonb, '실제 데이터'),

('idol_member_hyoyeon', 'HYOYEON', '1989-09-22', 'female', 'idol_member', NULL, '김효연', ARRAY['HYOYEON', '효연'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/hyoyeon_x_x", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["dance", "vocal", "rapper"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": [], "solo_activities": ["Mystery", "Wannabe", "DEEP"]}'::jsonb, '실제 데이터'),

('idol_member_yuri', 'YURI', '1989-12-05', 'female', 'idol_member', NULL, '권유리', ARRAY['YURI', '유리'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/yulyulk", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_dance"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": [], "solo_activities": ["Into You", "Illusion"]}'::jsonb, '실제 데이터'),

('idol_member_sooyoung', 'SOOYOUNG', '1990-02-10', 'female', 'idol_member', NULL, '최수영', ARRAY['SOOYOUNG', '수영'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/hotsootuff", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_dance"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_yoona', 'YOONA', '1990-05-30', 'female', 'idol_member', NULL, '임윤아', ARRAY['YOONA', '윤아'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/yoona__lim", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_dance", "visual", "center"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": [], "solo_activities": ["A Walk to Remember"]}'::jsonb, '실제 데이터'),

('idol_member_seohyun', 'SEOHYUN', '1991-06-28', 'female', 'idol_member', NULL, '서현', ARRAY['SEOHYUN', '서현'], '한국', NULL, '12:00', 2007, 'SM엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/seojuhyun_s", "youtube": "https://www.youtube.com/@SMTOWN"}'::jsonb, '{"group_name": "소녀시대", "position": ["vocal", "lead_vocal", "maknae"], "debut_date": "2007-08-05", "label": "SM엔터테인먼트", "fandom_name": "SONE", "sub_units": ["TTS"], "solo_activities": ["Don\'t Say No", "Bad Love"]}'::jsonb, '실제 데이터'),

('idol_member_minji', 'MINJI', '2004-05-07', 'female', 'idol_member', NULL, '김민지', ARRAY['MINJI', '민지'], '한국', NULL, '12:00', 2022, 'ADOR', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/newjeans_official", "youtube": "https://www.youtube.com/@NewJeans"}'::jsonb, '{"group_name": "NewJeans", "position": ["vocal", "rap", "leader"], "debut_date": "2022-08-01", "label": "ADOR", "fandom_name": "Bunnies", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_hanni', 'HANNI', '2004-10-06', 'female', 'idol_member', NULL, '팜 응옥 한', ARRAY['HANNI', '하니'], '호주', NULL, '12:00', 2022, 'ADOR', ARRAY['한국어', '영어', '베트남어'], '{"instagram": "https://instagram.com/newjeans_official", "youtube": "https://www.youtube.com/@NewJeans"}'::jsonb, '{"group_name": "NewJeans", "position": ["vocal", "sub_vocal"], "debut_date": "2022-08-01", "label": "ADOR", "fandom_name": "Bunnies", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_danielle', 'DANIELLE', '2005-04-11', 'female', 'idol_member', NULL, '다니엘 마시', ARRAY['DANIELLE', '다니엘'], '호주', NULL, '12:00', 2022, 'ADOR', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/newjeans_official", "youtube": "https://www.youtube.com/@NewJeans"}'::jsonb, '{"group_name": "NewJeans", "position": ["vocal", "main_vocal"], "debut_date": "2022-08-01", "label": "ADOR", "fandom_name": "Bunnies", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_haerin', 'HAERIN', '2006-05-15', 'female', 'idol_member', NULL, '강해린', ARRAY['HAERIN', '해린'], '한국', NULL, '12:00', 2022, 'ADOR', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/newjeans_official", "youtube": "https://www.youtube.com/@NewJeans"}'::jsonb, '{"group_name": "NewJeans", "position": ["vocal", "lead_dance"], "debut_date": "2022-08-01", "label": "ADOR", "fandom_name": "Bunnies", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_hyein', 'HYEIN', '2008-04-21', 'female', 'idol_member', NULL, '이혜인', ARRAY['HYEIN', '혜인'], '한국', NULL, '12:00', 2022, 'ADOR', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/newjeans_official", "youtube": "https://www.youtube.com/@NewJeans"}'::jsonb, '{"group_name": "NewJeans", "position": ["vocal", "dance", "maknae"], "debut_date": "2022-08-01", "label": "ADOR", "fandom_name": "Bunnies", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_yeonjun', 'YEONJUN', '1999-09-13', 'male', 'idol_member', NULL, '최연준', ARRAY['YEONJUN', '연준'], '한국', NULL, '12:00', 2019, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/txt_bighit", "youtube": "https://www.youtube.com/@txt_bighit"}'::jsonb, '{"group_name": "TXT", "position": ["vocal", "rap", "dance", "visual"], "debut_date": "2019-03-04", "label": "HYBE 엔터테인먼트", "fandom_name": "MOA", "sub_units": [], "solo_activities": ["GGUM"]}'::jsonb, '실제 데이터'),

('idol_member_soobin', 'SOOBIN', '2000-12-05', 'male', 'idol_member', NULL, '최수빈', ARRAY['SOOBIN', '수빈'], '한국', NULL, '12:00', 2019, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/txt_bighit", "youtube": "https://www.youtube.com/@txt_bighit"}'::jsonb, '{"group_name": "TXT", "position": ["vocal", "rap", "leader"], "debut_date": "2019-03-04", "label": "HYBE 엔터테인먼트", "fandom_name": "MOA", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_beomgyu', 'BEOMGYU', '2001-03-13', 'male', 'idol_member', NULL, '최범규', ARRAY['BEOMGYU', '범규'], '한국', NULL, '12:00', 2019, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/txt_bighit", "youtube": "https://www.youtube.com/@txt_bighit"}'::jsonb, '{"group_name": "TXT", "position": ["vocal", "rap", "visual"], "debut_date": "2019-03-04", "label": "HYBE 엔터테인먼트", "fandom_name": "MOA", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_taehyun', 'TAEHYUN', '2002-02-05', 'male', 'idol_member', NULL, '강태현', ARRAY['TAEHYUN', '태현'], '한국', NULL, '12:00', 2019, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/txt_bighit", "youtube": "https://www.youtube.com/@txt_bighit"}'::jsonb, '{"group_name": "TXT", "position": ["vocal", "main_vocal"], "debut_date": "2019-03-04", "label": "HYBE 엔터테인먼트", "fandom_name": "MOA", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_hueningkai', 'HUENINGKAI', '2002-08-14', 'male', 'idol_member', NULL, '휴닝카이', ARRAY['HUENINGKAI', '휴닝카이'], '미국', NULL, '12:00', 2019, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/txt_bighit", "youtube": "https://www.youtube.com/@txt_bighit"}'::jsonb, '{"group_name": "TXT", "position": ["vocal", "rap", "maknae"], "debut_date": "2019-03-04", "label": "HYBE 엔터테인먼트", "fandom_name": "MOA", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_sakura', 'SAKURA', '1998-03-19', 'female', 'idol_member', NULL, '미야와키 사쿠라', ARRAY['SAKURA', '사쿠라'], '일본', NULL, '12:00', 2022, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/lesserafim", "youtube": "https://www.youtube.com/@lesserafim"}'::jsonb, '{"group_name": "LE SSERAFIM", "position": ["vocal", "visual"], "debut_date": "2022-05-02", "label": "HYBE 엔터테인먼트", "fandom_name": "FEARNOT", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_chaewon', 'CHAEWON', '2000-08-01', 'female', 'idol_member', NULL, '김채원', ARRAY['CHAEWON', '채원'], '한국', NULL, '12:00', 2022, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lesserafim", "youtube": "https://www.youtube.com/@lesserafim"}'::jsonb, '{"group_name": "LE SSERAFIM", "position": ["vocal", "main_vocal", "leader"], "debut_date": "2022-05-02", "label": "HYBE 엔터테인먼트", "fandom_name": "FEARNOT", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_yunjin', 'YUNJIN', '2001-10-08', 'female', 'idol_member', NULL, '허윤진', ARRAY['YUNJIN', '윤진'], '미국', NULL, '12:00', 2022, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lesserafim", "youtube": "https://www.youtube.com/@lesserafim"}'::jsonb, '{"group_name": "LE SSERAFIM", "position": ["vocal", "lead_vocal"], "debut_date": "2022-05-02", "label": "HYBE 엔터테인먼트", "fandom_name": "FEARNOT", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_kazuha', 'KAZUHA', '2003-08-09', 'female', 'idol_member', NULL, '나카무라 카즈하', ARRAY['KAZUHA', '카즈하'], '일본', NULL, '12:00', 2022, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/lesserafim", "youtube": "https://www.youtube.com/@lesserafim"}'::jsonb, '{"group_name": "LE SSERAFIM", "position": ["vocal", "dance"], "debut_date": "2022-05-02", "label": "HYBE 엔터테인먼트", "fandom_name": "FEARNOT", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_eunchae', 'EUNCHAE', '2006-11-10', 'female', 'idol_member', NULL, '홍은채', ARRAY['EUNCHAE', '은채'], '한국', NULL, '12:00', 2022, 'HYBE 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/lesserafim", "youtube": "https://www.youtube.com/@lesserafim"}'::jsonb, '{"group_name": "LE SSERAFIM", "position": ["vocal", "dance", "maknae"], "debut_date": "2022-05-02", "label": "HYBE 엔터테인먼트", "fandom_name": "FEARNOT", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_wonyoung', 'WONYOUNG', '2004-08-31', 'female', 'idol_member', NULL, '장원영', ARRAY['WONYOUNG', '원영'], '한국', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "visual", "center"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_liz', 'LIZ', '2004-11-21', 'female', 'idol_member', NULL, '김지원', ARRAY['LIZ', '리즈'], '한국', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "main_vocal"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_rei', 'REI', '2004-02-03', 'female', 'idol_member', NULL, '나오이 레이', ARRAY['REI', '레이'], '일본', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "rap"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_gaeul', 'GAEUL', '2002-09-24', 'female', 'idol_member', NULL, '김가을', ARRAY['GAEUL', '가을'], '한국', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "rap", "leader"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_yujin', 'YUJIN', '2003-09-01', 'female', 'idol_member', NULL, '안유진', ARRAY['YUJIN', '유진'], '한국', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "dance"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터'),

('idol_member_leeseo', 'LEESEO', '2007-02-21', 'female', 'idol_member', NULL, '이서', ARRAY['LEESEO', '이서'], '한국', NULL, '12:00', 2021, '스타쉽 엔터테인먼트', ARRAY['한국어', '영어'], '{"instagram": "https://instagram.com/ive.official", "youtube": "https://www.youtube.com/@IVE"}'::jsonb, '{"group_name": "IVE", "position": ["vocal", "dance", "maknae"], "debut_date": "2021-12-01", "label": "스타쉽 엔터테인먼트", "fandom_name": "DIVE", "sub_units": [], "solo_activities": []}'::jsonb, '실제 데이터')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

