-- 솔로 가수 50명 실제 데이터 삽입
-- Category: solo_singer

INSERT INTO public.celebrities (
  id, name, birth_date, gender, celebrity_type,
  stage_name, legal_name, aliases, nationality, birth_place, birth_time,
  active_from, agency_management, languages, external_ids, profession_data, notes
) VALUES
('solo_singer_iu', '아이유', '1993-05-16', 'female', 'solo_singer', 'IU', '이지은', ARRAY['아이유', 'IU', '이지은'], '한국', '서울특별시 종로구', '14:30', 2008, 'EDAM 엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/아이유", "youtube": "https://www.youtube.com/@dlwlrma", "instagram": "https://instagram.com/dlwlrma"}'::jsonb, '{"debut_date": "2008-09", "label": "EDAM 엔터테인먼트", "genres": ["발라드", "팝", "R&B"], "fandom_name": "유애나", "vocal_range": "소프라노", "notable_tracks": ["좋은 날", "Through the Night", "Celebrity"]}'::jsonb, '실제 데이터'),

('solo_singer_psy', 'PSY', '1977-12-31', 'male', 'solo_singer', 'PSY', '박재상', ARRAY['PSY', '싸이', '박재상'], '한국', '서울특별시 강남구', '12:00', 2001, 'P NATION', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/싸이", "youtube": "https://www.youtube.com/@officialpsy", "instagram": "https://instagram.com/42psy42"}'::jsonb, '{"debut_date": "2001-01", "label": "P NATION", "genres": ["K-POP", "힙합", "댄스"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["강남스타일", "젠틀맨", "뉴페이스"]}'::jsonb, '실제 데이터'),

('solo_singer_taeyang', '태양', '1988-05-18', 'male', 'solo_singer', '태양', '동영배', ARRAY['태양', 'TAEYANG', '동영배'], '한국', '경기도 의정부시', '12:00', 2008, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/태양", "youtube": "https://www.youtube.com/@TAEYANG", "instagram": "https://instagram.com/__youngbae__"}'::jsonb, '{"debut_date": "2008-05", "label": "YG엔터테인먼트", "genres": ["R&B", "솔", "팝"], "fandom_name": "HOT", "vocal_range": "테너", "notable_tracks": ["Eyes, Nose, Lips", "Wedding Dress", "Only Look At Me"]}'::jsonb, '실제 데이터'),

('solo_singer_gdragon', 'G-Dragon', '1988-08-18', 'male', 'solo_singer', 'G-Dragon', '권지용', ARRAY['G-Dragon', 'GD', '권지용'], '한국', '서울특별시', '12:00', 2009, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/지드래곤", "youtube": "https://www.youtube.com/@GDRAGON", "instagram": "https://instagram.com/xxxibgdrgn"}'::jsonb, '{"debut_date": "2009-08", "label": "YG엔터테인먼트", "genres": ["힙합", "K-POP", "팝"], "fandom_name": "VIP", "vocal_range": "바리톤", "notable_tracks": ["Heartbreaker", "Crooked", "Untitled, 2014"]}'::jsonb, '실제 데이터'),

('solo_singer_hyuna', '현아', '1992-06-06', 'female', 'solo_singer', '현아', '김현아', ARRAY['현아', 'HyunA', '김현아'], '한국', '서울특별시', '12:00', 2010, 'P NATION', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/현아", "youtube": "https://www.youtube.com/@HYUNA", "instagram": "https://instagram.com/hyunah_aa"}'::jsonb, '{"debut_date": "2010-01", "label": "P NATION", "genres": ["댄스", "힙합", "팝"], "fandom_name": "A-ing", "vocal_range": "알토", "notable_tracks": ["Change", "Bubble Pop", "Roll Deep"]}'::jsonb, '실제 데이터'),

('solo_singer_sunmi', '선미', '1992-05-02', 'female', 'solo_singer', '선미', '이선미', ARRAY['선미', 'Sunmi', '이선미'], '한국', '경기도 이천시', '12:00', 2013, 'ABYSS컴퍼니', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/선미", "youtube": "https://www.youtube.com/@SUNMI", "instagram": "https://instagram.com/miyayeah"}'::jsonb, '{"debut_date": "2013-08", "label": "ABYSS컴퍼니", "genres": ["댄스", "팝", "일렉트로닉"], "fandom_name": "Mania", "vocal_range": "메조소프라노", "notable_tracks": ["24시간이 모자라", "Gashina", "Siren"]}'::jsonb, '실제 데이터'),

('solo_singer_chungha', '청하', '1996-02-09', 'female', 'solo_singer', '청하', '김찬미', ARRAY['청하', 'CHUNG HA', '김찬미'], '한국', '서울특별시', '12:00', 2017, 'MNH엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/청하", "youtube": "https://www.youtube.com/@CHUNGHA", "instagram": "https://instagram.com/chungha_official"}'::jsonb, '{"debut_date": "2017-06", "label": "MNH엔터테인먼트", "genres": ["댄스", "팝", "R&B"], "fandom_name": "Byulharang", "vocal_range": "메조소프라노", "notable_tracks": ["Why Don't You Know", "Roller Coaster", "Gotta Go"]}'::jsonb, '실제 데이터'),

('solo_singer_hwasa', '화사', '1995-07-23', 'female', 'solo_singer', '화사', '안혜진', ARRAY['화사', 'Hwasa', '안혜진'], '한국', '전라북도 전주시', '12:00', 2019, 'P NATION', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/화사", "youtube": "https://www.youtube.com/@HWASA", "instagram": "https://instagram.com/ahn_hyejin"}'::jsonb, '{"debut_date": "2019-02", "label": "P NATION", "genres": ["R&B", "힙합", "솔"], "fandom_name": "Twit", "vocal_range": "알토", "notable_tracks": ["Twit", "Maria", "I'm a B"]}'::jsonb, '실제 데이터'),

('solo_singer_rain', 'Rain', '1982-06-25', 'male', 'solo_singer', 'Rain', '정지훈', ARRAY['Rain', '비', '정지훈'], '한국', '서울특별시', '12:00', 2002, 'R.A.I.N. Company', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/비_(가수)", "youtube": "https://www.youtube.com/@RainWorldOfficial", "instagram": "https://instagram.com/rain_oppa"}'::jsonb, '{"debut_date": "2002-05", "label": "R.A.I.N. Company", "genres": ["R&B", "힙합", "댄스"], "fandom_name": "Cloud", "vocal_range": "바리톤", "notable_tracks": ["Bad Guy", "Love Song", "Gang"]}'::jsonb, '실제 데이터'),

('solo_singer_boa', 'BoA', '1986-11-05', 'female', 'solo_singer', 'BoA', '권보아', ARRAY['BoA', '보아', '권보아'], '한국', '경기도 구리시', '12:00', 2000, 'SM엔터테인먼트', ARRAY['한국어', '영어', '일본어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/보아", "youtube": "https://www.youtube.com/@SMTOWN", "instagram": "https://instagram.com/boakwon"}'::jsonb, '{"debut_date": "2000-08", "label": "SM엔터테인먼트", "genres": ["댄스", "팝", "R&B"], "fandom_name": "Jumping BoA", "vocal_range": "메조소프라노", "notable_tracks": ["No.1", "Only One", "Every Heart"]}'::jsonb, '실제 데이터'),

('solo_singer_se7en', 'Se7en', '1984-11-09', 'male', 'solo_singer', 'Se7en', '최동욱', ARRAY['Se7en', '세븐', '최동욱'], '한국', '서울특별시', '12:00', 2003, 'YG엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/세븐", "youtube": "https://www.youtube.com/@SE7ENOFFICIAL", "instagram": "https://instagram.com/se7en7"}'::jsonb, '{"debut_date": "2003-03", "label": "YG엔터테인먼트", "genres": ["R&B", "힙합", "댄스"], "fandom_name": "Lucky", "vocal_range": "테너", "notable_tracks": ["Come Back To Me", "La La La", "Passion"]}'::jsonb, '실제 데이터'),

('solo_singer_lee_hyori', '이효리', '1979-05-10', 'female', 'solo_singer', '이효리', '이효리', ARRAY['이효리', 'Lee Hyori'], '한국', '전라북도 전주시', '12:00', 2003, 'B2M엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이효리", "youtube": "https://www.youtube.com/@LeeHyoriOfficial", "instagram": "https://instagram.com/hyorilee"}'::jsonb, '{"debut_date": "2003-08", "label": "B2M엔터테인먼트", "genres": ["댄스", "팝", "R&B"], "fandom_name": "", "vocal_range": "메조소프라노", "notable_tracks": ["10 Minutes", "U-Go-Girl", "Miss Korea"]}'::jsonb, '실제 데이터'),

('solo_singer_park_jin_young', '박진영', '1971-12-13', 'male', 'solo_singer', '박진영', '박진영', ARRAY['박진영', 'JYP', 'Park Jin Young'], '한국', '서울특별시', '12:00', 1994, 'JYP엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박진영", "youtube": "https://www.youtube.com/@jypentertainment", "instagram": "https://instagram.com/asiansoul_jyp"}'::jsonb, '{"debut_date": "1994-01", "label": "JYP엔터테인먼트", "genres": ["R&B", "힙합", "댄스"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["She Was Pretty", "Fever", "Don't Leave Me"]}'::jsonb, '실제 데이터'),

('solo_singer_eric_nam', 'Eric Nam', '1988-11-17', 'male', 'solo_singer', 'Eric Nam', '남윤도', ARRAY['Eric Nam', '에릭남', '남윤도'], '미국', '애틀랜타', '12:00', 2013, 'DIVE Studios', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/에릭남", "youtube": "https://www.youtube.com/@ericnamofficial", "instagram": "https://instagram.com/ericnam"}'::jsonb, '{"debut_date": "2013-01", "label": "DIVE Studios", "genres": ["팝", "R&B", "인디"], "fandom_name": "", "vocal_range": "테너", "notable_tracks": ["Can't Help Myself", "Love Die Young", "Any Other Way"]}'::jsonb, '실제 데이터'),

('solo_singer_dean', 'DEAN', '1992-11-10', 'male', 'solo_singer', 'DEAN', '권혁', ARRAY['DEAN', '딘', '권혁'], '한국', '서울특별시', '12:00', 2015, 'Universal Music', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/딘_(가수)", "youtube": "https://www.youtube.com/@DEANTRBL", "instagram": "https://instagram.com/deantrbl"}'::jsonb, '{"debut_date": "2015-11", "label": "Universal Music", "genres": ["R&B", "힙합", "얼터너티브"], "fandom_name": "", "vocal_range": "테너", "notable_tracks": ["Instagram", "D (half moon)", "Bonnie & Clyde"]}'::jsonb, '실제 데이터'),

('solo_singer_crush', 'Crush', '1992-05-03', 'male', 'solo_singer', 'Crush', '신효섭', ARRAY['Crush', '크러쉬', '신효섭'], '한국', '서울특별시', '12:00', 2012, 'P NATION', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/크러쉬", "youtube": "https://www.youtube.com/@crushsound", "instagram": "https://instagram.com/crush9244"}'::jsonb, '{"debut_date": "2012-04", "label": "P NATION", "genres": ["R&B", "솔", "힙합"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Sometimes", "Beautiful", "Holo"]}'::jsonb, '실제 데이터'),

('solo_singer_davichi_haeri', '이해리', '1985-04-09', 'female', 'solo_singer', '이해리', '이해리', ARRAY['이해리', 'Lee Haeri'], '한국', '서울특별시', '12:00', 2016, '8D크리에이티브', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이해리", "youtube": "https://www.youtube.com/@LeeHaeri", "instagram": "https://instagram.com/leehaeri_8890"}'::jsonb, '{"debut_date": "2016-10", "label": "8D크리에이티브", "genres": ["발라드", "팝"], "fandom_name": "", "vocal_range": "소프라노", "notable_tracks": ["Hate That I Love You", "My Love", "Pattern"]}'::jsonb, '실제 데이터'),

('solo_singer_davichi_minkyung', '강민경', '1990-08-03', 'female', 'solo_singer', '강민경', '강민경', ARRAY['강민경', 'Kang Minkyung'], '한국', '부산광역시', '12:00', 2015, '8D크리에이티브', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/강민경", "youtube": "https://www.youtube.com/@KangMinKyung", "instagram": "https://instagram.com/minkyung_official"}'::jsonb, '{"debut_date": "2015-07", "label": "8D크리에이티브", "genres": ["발라드", "팝"], "fandom_name": "", "vocal_range": "메조소프라노", "notable_tracks": ["Confession", "Love Actually", "Day & Night"]}'::jsonb, '실제 데이터'),

('solo_singer_park_bom', '박봄', '1984-03-24', 'female', 'solo_singer', '박봄', '박봄', ARRAY['박봄', 'Park Bom'], '한국', '서울특별시', '12:00', 2019, 'D-NATION', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박봄", "youtube": "https://www.youtube.com/@ParkBom", "instagram": "https://instagram.com/haribobom"}'::jsonb, '{"debut_date": "2019-03", "label": "D-NATION", "genres": ["팝", "댄스", "발라드"], "fandom_name": "", "vocal_range": "소프라노", "notable_tracks": ["Spring", "4:44", "Do Re Mi Fa Sol"]}'::jsonb, '실제 데이터'),

('solo_singer_cl', 'CL', '1991-02-26', 'female', 'solo_singer', 'CL', '이채린', ARRAY['CL', '씨엘', '이채린'], '한국', '서울특별시', '12:00', 2013, 'Very Cherry', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/CL", "youtube": "https://www.youtube.com/@CLOFFICIAL", "instagram": "https://instagram.com/chaelincl"}'::jsonb, '{"debut_date": "2013-05", "label": "Very Cherry", "genres": ["힙합", "댄스", "팝"], "fandom_name": "GZB", "vocal_range": "알토", "notable_tracks": ["The Baddest Female", "Hello Bitches", "Lifted"]}'::jsonb, '실제 데이터'),

('solo_singer_zico', 'Zico', '1992-09-14', 'male', 'solo_singer', 'Zico', '우지호', ARRAY['Zico', '지코', '우지호'], '한국', '서울특별시', '12:00', 2014, 'KOZ엔터테인먼트', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/지코", "youtube": "https://www.youtube.com/@ZICO", "instagram": "https://instagram.com/woozico0914"}'::jsonb, '{"debut_date": "2014-07", "label": "KOZ엔터테인먼트", "genres": ["힙합", "R&B", "팝"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Any Song", "Artist", "Summer Hate"]}'::jsonb, '실제 데이터'),

('solo_singer_jay_park', 'Jay Park', '1987-04-25', 'male', 'solo_singer', 'Jay Park', '박재범', ARRAY['Jay Park', '박재범'], '미국', '시애틀', '12:00', 2010, 'More Vision', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/박재범", "youtube": "https://www.youtube.com/@jparkitrighthere", "instagram": "https://instagram.com/moresojuplease"}'::jsonb, '{"debut_date": "2010-01", "label": "More Vision", "genres": ["힙합", "R&B", "팝"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["MOMMAE", "All I Wanna Do", "Soju"]}'::jsonb, '실제 데이터'),

('solo_singer_loco', 'Loco', '1989-12-25', 'male', 'solo_singer', 'Loco', '권혁우', ARRAY['Loco', '로꼬', '권혁우'], '한국', '서울특별시', '12:00', 2012, 'AOMG', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/로꼬", "youtube": "https://www.youtube.com/@locoism", "instagram": "https://instagram.com/loco_aomg"}'::jsonb, '{"debut_date": "2012-08", "label": "AOMG", "genres": ["힙합", "R&B"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Hold Me Tight", "Summer Go Lightly", "You Don't Know"]}'::jsonb, '실제 데이터'),

('solo_singer_gray', 'GRAY', '1986-12-08', 'male', 'solo_singer', 'GRAY', '이성화', ARRAY['GRAY', '그레이', '이성화'], '한국', '서울특별시', '12:00', 2012, 'AOMG', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/그레이", "youtube": "https://www.youtube.com/@grayground", "instagram": "https://instagram.com/callmegray"}'::jsonb, '{"debut_date": "2012-06", "label": "AOMG", "genres": ["힙합", "R&B", "프로듀싱"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Just Do It", "Stay Here", "119 Remix"]}'::jsonb, '실제 데이터'),

('solo_singer_simon_d', 'Simon D', '1984-03-03', 'male', 'solo_singer', 'Simon D', '정기석', ARRAY['Simon D', '사이먼 디', '정기석'], '한국', '부산광역시', '12:00', 2006, 'AOMG', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/사이먼_디", "youtube": "https://www.youtube.com/@SimonDominic", "instagram": "https://instagram.com/callmesimon"}'::jsonb, '{"debut_date": "2006-01", "label": "AOMG", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Simon Dominic", "GOTT", "Won & Only"]}'::jsonb, '실제 데이터'),

('solo_singer_dok2', 'Dok2', '1990-03-28', 'male', 'solo_singer', 'Dok2', '이준경', ARRAY['Dok2', '도끼', '이준경'], '한국', '서울특별시', '12:00', 2007, '일리네어 레코즈', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/도끼_(래퍼)", "youtube": "https://www.youtube.com/@DOK2GONZO", "instagram": "https://instagram.com/dok2gonzo"}'::jsonb, '{"debut_date": "2007-01", "label": "일리네어 레코즈", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["On Top", "Future Flame", "Multimillionaire"]}'::jsonb, '실제 데이터'),

('solo_singer_the_quiett', 'The Quiett', '1985-01-29', 'male', 'solo_singer', 'The Quiett', '신동갑', ARRAY['The Quiett', '더 콰이엇', '신동갑'], '한국', '고양시', '12:00', 2005, '일리네어 레코즈', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/더_콰이엇", "youtube": "https://www.youtube.com/@thequiett", "instagram": "https://instagram.com/q_u_i_e_t_t"}'::jsonb, '{"debut_date": "2005-01", "label": "일리네어 레코즈", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Bentley 2", "1 Life 2 Live", "Microphone Duct Tape"]}'::jsonb, '실제 데이터'),

('solo_singer_beenzino', 'Beenzino', '1987-09-12', 'male', 'solo_singer', 'Beenzino', '임성빈', ARRAY['Beenzino', '빈지노', '임성빈'], '한국', '서울특별시', '12:00', 2009, '일리네어 레코즈', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/빈지노", "youtube": "https://www.youtube.com/@beenzino", "instagram": "https://instagram.com/realisshoman"}'::jsonb, '{"debut_date": "2009-01", "label": "일리네어 레코즈", "genres": ["힙합", "랩", "재즈"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Dali, Van, Picasso", "This Love", "Up All Night"]}'::jsonb, '실제 데이터'),

('solo_singer_epik_high_tablo', 'Tablo', '1980-07-22', 'male', 'solo_singer', 'Tablo', '이선웅', ARRAY['Tablo', '타블로', '이선웅'], '한국', '서울특별시', '12:00', 2011, '하이그라운드', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/타블로", "youtube": "https://www.youtube.com/@TabloOfficial", "instagram": "https://instagram.com/blobyblo"}'::jsonb, '{"debut_date": "2011-11", "label": "하이그라운드", "genres": ["힙합", "얼터너티브"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Airbag", "Bad", "Thank You"]}'::jsonb, '실제 데이터'),

('solo_singer_verbal_jint', 'Verbal Jint', '1980-12-19', 'male', 'solo_singer', 'Verbal Jint', '김진태', ARRAY['Verbal Jint', '버벌진트', '김진태'], '한국', '서울특별시', '12:00', 2005, '브랜뉴뮤직', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/버벌진트", "youtube": "https://www.youtube.com/@VerbalJint", "instagram": "https://instagram.com/verbaljint"}'::jsonb, '{"debut_date": "2005-01", "label": "브랜뉴뮤직", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["You Deserve Better", "Go Easy", "Black Dawn"]}'::jsonb, '실제 데이터'),

('solo_singer_dynamic_duo_gaeko', 'Gaeko', '1981-01-14', 'male', 'solo_singer', 'Gaeko', '김윤성', ARRAY['Gaeko', '개코', '김윤성'], '한국', '서울특별시', '12:00', 2013, '아메바컬쳐', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/개코", "youtube": "https://www.youtube.com/@GaekoOfficial", "instagram": "https://instagram.com/gaeko"}'::jsonb, '{"debut_date": "2013-07", "label": "아메바컬쳐", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Gajah", "Rhythm Is Life", "Rose"]}'::jsonb, '실제 데이터'),

('solo_singer_dynamic_duo_choiza', 'Choiza', '1980-03-17', 'male', 'solo_singer', 'Choiza', '최재호', ARRAY['Choiza', '최자', '최재호'], '한국', '서울특별시', '12:00', 2014, '아메바컬쳐', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/최자", "youtube": "https://www.youtube.com/@ChoizaOfficial", "instagram": "https://instagram.com/choiza_dd"}'::jsonb, '{"debut_date": "2014-11", "label": "아메바컬쳐", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Eat", "VV:D", "She\'s Gone"]}'::jsonb, '실제 데이터'),

('solo_singer_justhis', 'JUSTHIS', '1991-07-07', 'male', 'solo_singer', 'JUSTHIS', '김주헌', ARRAY['JUSTHIS', '저스디스', '김주헌'], '한국', '부산광역시', '12:00', 2012, '인디고뮤직', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/저스디스", "youtube": "https://www.youtube.com/@JUSTHIS", "instagram": "https://instagram.com/realjusthis"}'::jsonb, '{"debut_date": "2012-01", "label": "인디고뮤직", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Life Goes On", "Dingo Freestyle", "4 The Youth"]}'::jsonb, '실제 데이터'),

('solo_singer_kid_milli', 'Kid Milli', '1998-03-08', 'male', 'solo_singer', 'Kid Milli', '김민재', ARRAY['Kid Milli', '키드밀리', '김민재'], '한국', '대구광역시', '12:00', 2017, '인디고뮤직', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/키드밀리", "youtube": "https://www.youtube.com/@kidmilli", "instagram": "https://instagram.com/kidmilli"}'::jsonb, '{"debut_date": "2017-01", "label": "인디고뮤직", "genres": ["힙합", "랩"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Why Do Fuckbois Hang Out on the Net", "YARD", "무언가를 원한다면"]}'::jsonb, '실제 데이터'),

('solo_singer_ph1', 'pH-1', '1989-07-23', 'male', 'solo_singer', 'pH-1', '박준원', ARRAY['pH-1', '피에이치원', '박준원'], '한국', '서울특별시', '12:00', 2016, 'H1ghr Music', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/pH-1", "youtube": "https://www.youtube.com/@pH1official", "instagram": "https://instagram.com/ph1boyyy"}'::jsonb, '{"debut_date": "2016-06", "label": "H1ghr Music", "genres": ["힙합", "R&B"], "fandom_name": "", "vocal_range": "바리톤", "notable_tracks": ["Nerdy Love", "Hate You", "PACKITUP!"]}'::jsonb, '실제 데이터'),

('solo_singer_heize', 'Heize', '1991-08-09', 'female', 'solo_singer', 'Heize', '장다혜', ARRAY['Heize', '헤이즈', '장다혜'], '한국', '대구광역시', '12:00', 2014, 'P NATION', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/헤이즈", "youtube": "https://www.youtube.com/@HEIZE", "instagram": "https://instagram.com/heize_official"}'::jsonb, '{"debut_date": "2014-03", "label": "P NATION", "genres": ["R&B", "힙합", "인디"], "fandom_name": "", "vocal_range": "메조소프라노", "notable_tracks": ["Stay Here", "Jenga", "You, Clouds, Rain"]}'::jsonb, '실제 데이터'),

('solo_singer_ailee', 'Ailee', '1989-05-30', 'female', 'solo_singer', 'Ailee', '에일리', ARRAY['Ailee', '에일리'], '미국', '덴버', '12:00', 2012, 'THE L1VE', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/에일리", "youtube": "https://www.youtube.com/@aileemusic", "instagram": "https://instagram.com/aileeonline"}'::jsonb, '{"debut_date": "2012-02", "label": "THE L1VE", "genres": ["발라드", "R&B", "팝"], "fandom_name": "Aileean", "vocal_range": "소프라노", "notable_tracks": ["U&I", "Don't Touch Me", "I Will Go To You Like The First Snow"]}'::jsonb, '실제 데이터'),

('solo_singer_davichi_lee_hae_ri', '이해리', '1985-04-09', 'female', 'solo_singer', '이해리', '이해리', ARRAY['이해리', 'Lee Hae Ri'], '한국', '서울특별시', '12:00', 2008, '8D크리에이티브', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/이해리", "youtube": "https://www.youtube.com/@LeeHaeri", "instagram": "https://instagram.com/leehaeri_8890"}'::jsonb, '{"debut_date": "2008-02", "label": "8D크리에이티브", "genres": ["발라드", "팝"], "fandom_name": "Davichi", "vocal_range": "소프라노", "notable_tracks": ["8282", "Hot Issue", "We Are The Two"]}'::jsonb, '실제 데이터'),

('solo_singer_mamamoo_solar', 'Solar', '1991-02-21', 'female', 'solo_singer', 'Solar', '김용선', ARRAY['Solar', '솔라', '김용선'], '한국', '서울특별시', '12:00', 2020, 'RBW', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/솔라", "youtube": "https://www.youtube.com/@solarsido", "instagram": "https://instagram.com/solarkeem"}'::jsonb, '{"debut_date": "2020-04", "label": "RBW", "genres": ["팝", "R&B"], "fandom_name": "Solmate", "vocal_range": "메조소프라노", "notable_tracks": ["Spit it out", "Honey", "Big Booty"]}'::jsonb, '실제 데이터'),

('solo_singer_mamamoo_moonbyul', 'Moonbyul', '1992-12-22', 'female', 'solo_singer', 'Moonbyul', '문별이', ARRAY['Moonbyul', '문별', '문별이'], '한국', '부천시', '12:00', 2018, 'RBW', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/문별", "youtube": "https://www.youtube.com/@moonbyul_official", "instagram": "https://instagram.com/mo_onbyul"}'::jsonb, '{"debut_date": "2018-05", "label": "RBW", "genres": ["힙합", "R&B"], "fandom_name": "Byulharang", "vocal_range": "알토", "notable_tracks": ["Selfish", "Eclipse", "LUNATIC"]}'::jsonb, '실제 데이터'),

('solo_singer_mamamoo_wheein', 'Wheein', '1995-04-17', 'female', 'solo_singer', 'Wheein', '정휘인', ARRAY['Wheein', '휘인', '정휘인'], '한국', '전북 전주', '12:00', 2019, 'THE L1VE', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/휘인", "youtube": "https://www.youtube.com/@wheein_official", "instagram": "https://instagram.com/whee_inthemood"}'::jsonb, '{"debut_date": "2019-09", "label": "THE L1VE", "genres": ["R&B", "팝"], "fandom_name": "Wheebyul", "vocal_range": "메조소프라노", "notable_tracks": ["Easy", "water color", "Make Me Happy"]}'::jsonb, '실제 데이터'),

('solo_singer_yuju', 'YUJU', '1997-10-04', 'female', 'solo_singer', 'YUJU', '최유나', ARRAY['YUJU', '유주', '최유나'], '한국', '고양시', '12:00', 2021, 'KONNECT엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/유주", "youtube": "https://www.youtube.com/@YUJU_Official", "instagram": "https://instagram.com/yuuzth"}'::jsonb, '{"debut_date": "2021-10", "label": "KONNECT엔터테인먼트", "genres": ["발라드", "팝"], "fandom_name": "Joyful", "vocal_range": "소프라노", "notable_tracks": ["Play", "COLD", "The Killa"]}'::jsonb, '실제 데이터'),

('solo_singer_yerin', 'YERIN', '1996-08-19', 'female', 'solo_singer', 'YERIN', '정예린', ARRAY['YERIN', '예린', '정예린'], '한국', '인천광역시', '12:00', 2022, '빌리프랩', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/예린", "youtube": "https://www.youtube.com/@YERIN_Official", "instagram": "https://instagram.com/yerini_92"}'::jsonb, '{"debut_date": "2022-05", "label": "빌리프랩", "genres": ["팝", "댄스"], "fandom_name": "BUDDY", "vocal_range": "메조소프라노", "notable_tracks": ["ARIA", "Believer", "Spring Memories"]}'::jsonb, '실제 데이터'),

('solo_singer_eunha', 'EUNHA', '1997-05-30', 'female', 'solo_singer', 'EUNHA', '정은비', ARRAY['EUNHA', '은하', '정은비'], '한국', '서울특별시', '12:00', 2022, 'BPM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/은하", "youtube": "https://www.youtube.com/@EUNHA_Official", "instagram": "https://instagram.com/rlo_ovo"}'::jsonb, '{"debut_date": "2022-07", "label": "BPM엔터테인먼트", "genres": ["팝", "댄스"], "fandom_name": "BUDDY", "vocal_range": "소프라노", "notable_tracks": ["Door", "Pit A Pat", "Me Gustas Tu"]}'::jsonb, '실제 데이터'),

('solo_singer_umji', 'UMJI', '1998-08-19', 'female', 'solo_singer', 'UMJI', '김예원', ARRAY['UMJI', '엄지', '김예원'], '한국', '인천광역시', '12:00', 2022, 'VIVACE', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/엄지", "youtube": "https://www.youtube.com/@UMJI_Official", "instagram": "https://instagram.com/yewonkim_go"}'::jsonb, '{"debut_date": "2022-08", "label": "VIVACE", "genres": ["팝", "인디"], "fandom_name": "BUDDY", "vocal_range": "알토", "notable_tracks": ["Bittersweet", "Young Luv", "Falling Slowly"]}'::jsonb, '실제 데이터'),

('solo_singer_sunmi_real', '선미', '1992-05-02', 'female', 'solo_singer', '선미', '이선미', ARRAY['선미', 'Sunmi', '이선미'], '한국', '경기도 이천시', '12:00', 2013, 'ABYSS컴퍼니', ARRAY['한국어', '영어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/선미", "youtube": "https://www.youtube.com/@SUNMI", "instagram": "https://instagram.com/miyayeah"}'::jsonb, '{"debut_date": "2013-08", "label": "ABYSS컴퍼니", "genres": ["댄스", "팝", "일렉트로닉"], "fandom_name": "Mania", "vocal_range": "메조소프라노", "notable_tracks": ["24시간이 모자라", "Gashina", "Siren"]}'::jsonb, '실제 데이터'),

('solo_singer_choa', 'Choa', '1990-03-06', 'female', 'solo_singer', 'Choa', '박초아', ARRAY['Choa', '초아', '박초아'], '한국', '인천광역시', '12:00', 2017, 'WM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/초아", "youtube": "https://www.youtube.com/@ChoaOfficial", "instagram": "https://instagram.com/park_choa_"}'::jsonb, '{"debut_date": "2017-12", "label": "WM엔터테인먼트", "genres": ["발라드", "팝"], "fandom_name": "Elvis", "vocal_range": "소프라노", "notable_tracks": ["Flame", "Spring Love", "Good Luck"]}'::jsonb, '실제 데이터'),

('solo_singer_seolhyun', '설현', '1995-01-03', 'female', 'solo_singer', '설현', '김설현', ARRAY['설현', 'Seolhyun', '김설현'], '한국', '부산광역시', '12:00', 2020, 'FNC엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/설현", "youtube": "https://www.youtube.com/@SeolhyunOfficial", "instagram": "https://instagram.com/seolhyun_an"}'::jsonb, '{"debut_date": "2020-05", "label": "FNC엔터테인먼트", "genres": ["팝", "댄스"], "fandom_name": "Elvis", "vocal_range": "메조소프라노", "notable_tracks": ["Still Fighting It", "Love Is Only You", "Heart Attack"]}'::jsonb, '실제 데이터'),

('solo_singer_yooa', 'YooA', '1995-09-17', 'female', 'solo_singer', 'YooA', '유시아', ARRAY['YooA', '유아', '유시아'], '한국', '서울특별시', '12:00', 2020, 'WM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/유아", "youtube": "https://www.youtube.com/@YooAOfficial", "instagram": "https://instagram.com/yooa_"}'::jsonb, '{"debut_date": "2020-09", "label": "WM엔터테인먼트", "genres": ["댄스", "팝"], "fandom_name": "Miracle", "vocal_range": "메조소프라노", "notable_tracks": ["Bon Voyage", "Abracadabra", "Secret Garden"]}'::jsonb, '실제 데이터'),

('solo_singer_jiho', 'Jiho', '1994-04-04', 'female', 'solo_singer', 'Jiho', '김지호', ARRAY['Jiho', '지호', '김지호'], '한국', '인천광역시', '12:00', 2021, 'WM엔터테인먼트', ARRAY['한국어'], '{"wikipedia": "https://ko.wikipedia.org/wiki/지호", "youtube": "https://www.youtube.com/@JihoOfficial", "instagram": "https://instagram.com/jiho_0404"}'::jsonb, '{"debut_date": "2021-03", "label": "WM엔터테인먼트", "genres": ["발라드", "팝"], "fandom_name": "Miracle", "vocal_range": "소프라노", "notable_tracks": ["Closer", "Way To Go", "Windy Day"]}'::jsonb, '실제 데이터')

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = NOW();

