const FIGMA_PAGES = [
  {
    key: '00-cover-governance',
    name: '00 Cover & Governance',
    description: 'Official file governance, capture legend, and source-of-truth rules.',
  },
  {
    key: '10-entry-auth-onboarding',
    name: '10 Entry / Auth / Onboarding',
    description: 'Entry surfaces and onboarding states rendered at iPhone 15 Pro size.',
  },
  {
    key: '20-chat-home-character',
    name: '20 Chat Home / Character',
    description: 'Chat-first home, character conversation, and character profiles.',
  },
  {
    key: '30-fortune-hub-interactive',
    name: '30 Fortune Hub / Interactive',
    description: 'Fortune hub plus direct interactive flows and representative seeded result.',
  },
  {
    key: '40-trend',
    name: '40 Trend',
    description: 'Trend hub plus placeholders for backend-content-dependent detail/result flows.',
  },
  {
    key: '50-health-exercise',
    name: '50 Health / Exercise',
    description: 'Health and exercise input states with placeholders for result-only flows.',
  },
  {
    key: '60-history-profile-more',
    name: '60 History / Profile / More',
    description: 'History and More live states plus auth-gated Profile surfaces.',
  },
  {
    key: '70-commerce-settings-support',
    name: '70 Commerce / Settings / Support',
    description: 'Premium, subscription, token purchase, policy, and support screens.',
  },
  {
    key: '75-wellness',
    name: '75 Wellness',
    description: 'Focused wellness landing and meditation flows that live outside the main shell.',
  },
  {
    key: '80-admin-policy-utility',
    name: '80 Admin / Policy / Utility',
    description: 'Admin and utility screens that need dedicated operational tracking.',
  },
  {
    key: '90-components',
    name: '90 Components',
    description: 'Component inventory cards mapped back to source files.',
  },
  {
    key: '99-archive',
    name: '99 Archive',
    description: 'Superseded or runtime-blocked surfaces explicitly excluded from live capture.',
  },
];

const IPHONE_15_PRO = {
  name: 'iPhone 15 Pro',
  width: 393,
  height: 852,
  scale: 3,
};

function buildDreamResultStorage() {
  const today = new Date().toISOString().split('T')[0];
  const resultPayload = {
    fortuneResult: {
      id: 'dream-capture-001',
      fortune_type: 'dream',
      type: 'dream',
      title: '꿈 해몽 결과',
      summary: {
        message: '도약의 시기예요',
        emoji: '🌙',
      },
      fortune_data: {
        dreamType: '길몽',
        relatedSymbols: ['달빛', '비행', '변화'],
        interpretation:
          '하늘을 나는 꿈은 현재 삶에서의 확장과 자신감 상승을 상징합니다. 새로운 기회가 가까이 와 있어요.',
        todayGuidance:
          '오늘은 주저하던 일을 먼저 시작해 보세요. 이동과 연락, 제안에 행운이 따릅니다.',
      },
      data: {
        dreamType: '길몽',
        relatedSymbols: ['달빛', '비행', '변화'],
        interpretation:
          '하늘을 나는 꿈은 현재 삶에서의 확장과 자신감 상승을 상징합니다. 새로운 기회가 가까이 와 있어요.',
        todayGuidance:
          '오늘은 주저하던 일을 먼저 시작해 보세요. 이동과 연락, 제안에 행운이 따릅니다.',
      },
      score: 88,
      created_at: new Date().toISOString(),
      is_percentile_valid: false,
    },
    selectedTopic: {
      id: 'fly',
      emoji: '🌙',
      title: '하늘을 나는 꿈',
      category: 'positive',
      customContent: null,
    },
    savedDate: today,
  };

  return {
    'flutter.character_onboarding_completed': 'true',
    // shared_preferences_web stores strings JSON-encoded.
    'flutter.dreamInterpretationResult': JSON.stringify(
      JSON.stringify(resultPayload)
    ),
  };
}

const SCREENS = [
  {
    id: 'auth__splash__redirected',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'auth__splash__redirected',
    title: 'Splash Redirect',
    routeHash: '#/splash',
    status: 'live',
    note: 'Current build redirects Splash into the first-run chat onboarding experience.',
    waitMs: 8000,
    sources: ['lib/screens/splash_screen.dart'],
  },
  {
    id: 'auth__signup__default',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'auth__signup__default',
    title: 'Signup',
    routeHash: '#/signup',
    status: 'live',
    waitMs: 8000,
    sources: ['lib/screens/auth/signup_screen.dart'],
  },
  {
    id: 'auth__callback__redirected',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'auth__callback__redirected',
    title: 'Auth Callback Redirect',
    routeHash: '#/auth/callback',
    status: 'live',
    note: 'Callback currently resolves to the same first-run chat onboarding surface in test mode.',
    waitMs: 8000,
    sources: ['lib/screens/auth/callback_page.dart'],
  },
  {
    id: 'onboarding__profile__default',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'onboarding__profile__default',
    title: 'Onboarding',
    routeHash: '#/onboarding',
    status: 'live',
    waitMs: 8000,
    sources: ['lib/screens/onboarding/onboarding_page.dart'],
  },
  {
    id: 'onboarding__toss_style__default',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'onboarding__toss_style__default',
    title: 'Toss-style Onboarding',
    routeHash: '#/onboarding/toss-style',
    status: 'live',
    waitMs: 8000,
    sources: ['lib/screens/onboarding/onboarding_page.dart'],
  },
  {
    id: 'chat__onboarding__first_run',
    pageKey: '10-entry-auth-onboarding',
    frameName: 'chat__onboarding__first_run',
    title: 'Chat First-run Onboarding',
    routeHash: '#/chat',
    status: 'live',
    waitMs: 8000,
    sources: [
      'lib/features/character/presentation/pages/swipe_home_shell.dart',
      'lib/features/character/presentation/pages/character_onboarding_page.dart',
    ],
  },
  {
    id: 'chat__home__returning',
    pageKey: '20-chat-home-character',
    frameName: 'chat__home__returning',
    title: 'Chat Home Returning User',
    routeHash: '#/chat',
    status: 'live',
    waitMs: 8000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: [
      'lib/features/character/presentation/pages/swipe_home_shell.dart',
      'lib/features/character/presentation/pages/character_list_panel.dart',
    ],
  },
  {
    id: 'chat__character__luts',
    pageKey: '20-chat-home-character',
    frameName: 'chat__character__luts',
    title: 'Character Chat Overlay',
    routeHash: '#/chat?openCharacterChat=true&characterId=luts',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: [
      'lib/features/character/presentation/pages/swipe_home_shell.dart',
      'lib/features/character/presentation/pages/character_chat_panel.dart',
    ],
  },
  {
    id: 'character__profile__luts',
    pageKey: '20-chat-home-character',
    frameName: 'character__profile__luts',
    title: 'Character Profile Luts',
    routeHash: '#/character/luts',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/character/presentation/pages/character_profile_page.dart'],
  },
  {
    id: 'character__profile__baek_hyunwoo',
    pageKey: '20-chat-home-character',
    frameName: 'character__profile__baek_hyunwoo',
    title: 'Character Profile Baek Hyunwoo',
    routeHash: '#/character/baek_hyunwoo',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/character/presentation/pages/character_profile_page.dart'],
  },
  {
    id: 'chat__result_card__fortune',
    pageKey: '20-chat-home-character',
    frameName: 'chat__result_card__fortune',
    title: 'Chat Fortune Result Card',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker:
      'Needs persisted conversation history and generated fortune-card state in local Hive storage.',
    sources: [
      'lib/features/character/presentation/pages/character_chat_panel.dart',
      'lib/features/character/presentation/widgets/character_message_bubble.dart',
    ],
  },
  {
    id: 'fortune__hub__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'fortune__hub__default',
    title: 'Fortune Hub',
    routeHash: '#/fortune',
    status: 'live',
    waitMs: 8000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/more/presentation/pages/fortune_tab_page.dart'],
  },
  {
    id: 'interactive__hub__list',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive__hub__list',
    title: 'Interactive Hub',
    routeHash: '#/fortune/interactive',
    status: 'live',
    waitMs: 8000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/interactive_list_page.dart'],
  },
  {
    id: 'interactive_dream__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_dream__input__default',
    title: 'Dream Interpretation Input',
    routeHash: '#/fortune/interactive/dream',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/dream_interpretation_page.dart'],
  },
  {
    id: 'interactive_dream__result__seeded',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_dream__result__seeded',
    title: 'Dream Interpretation Result',
    routeHash: '#/fortune/interactive/dream',
    status: 'live',
    waitMs: 10000,
    buildStorage: buildDreamResultStorage,
    sources: ['lib/features/interactive/presentation/pages/dream_interpretation_page.dart'],
  },
  {
    id: 'interactive_psychology__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_psychology__input__default',
    title: 'Psychology Test Input',
    routeHash: '#/fortune/interactive/psychology-test',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/psychology_test_page.dart'],
  },
  {
    id: 'interactive_psychology__result__api',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_psychology__result__api',
    title: 'Psychology Test Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker:
      'Needs token consumption plus successful remote psychology-test generation after completing five-question flow.',
    sources: [
      'lib/features/interactive/presentation/pages/psychology_test_page.dart',
      'lib/features/interactive/presentation/providers/psychology_test_providers.dart',
    ],
  },
  {
    id: 'interactive_tarot__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_tarot__input__default',
    title: 'Tarot Chat',
    routeHash: '#/fortune/interactive/tarot',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/tarot_chat_page.dart'],
  },
  {
    id: 'interactive_tarot__animated_flow__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_tarot__animated_flow__default',
    title: 'Tarot Animated Flow',
    routeHash: '#/fortune/interactive/tarot/animated-flow',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/tarot_animated_flow_page.dart'],
  },
  {
    id: 'interactive_face_reading__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_face_reading__input__default',
    title: 'Face Reading Input',
    routeHash: '#/fortune/interactive/face-reading',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/face_reading_page.dart'],
  },
  {
    id: 'interactive_face_reading__result__analysis',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_face_reading__result__analysis',
    title: 'Face Reading Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker:
      'Requires photo-input flow plus generated analysis payload after runtime permission and edge call.',
    sources: ['lib/features/interactive/presentation/pages/face_reading_page.dart'],
  },
  {
    id: 'interactive_taemong__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_taemong__input__default',
    title: 'Taemong Input',
    routeHash: '#/fortune/interactive/taemong',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/taemong_page.dart'],
  },
  {
    id: 'interactive_taemong__result__analysis',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_taemong__result__analysis',
    title: 'Taemong Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker: 'Requires text submission and taemong analysis completion.',
    sources: ['lib/features/interactive/presentation/pages/taemong_page.dart'],
  },
  {
    id: 'interactive_worry_bead__input__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_worry_bead__input__default',
    title: 'Worry Bead Input',
    routeHash: '#/fortune/interactive/worry-bead',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/worry_bead_page.dart'],
  },
  {
    id: 'interactive_worry_bead__result__analysis',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_worry_bead__result__analysis',
    title: 'Worry Bead Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker: 'Requires worry input and generated reflection result.',
    sources: ['lib/features/interactive/presentation/pages/worry_bead_page.dart'],
  },
  {
    id: 'interactive_dream_journal__default',
    pageKey: '30-fortune-hub-interactive',
    frameName: 'interactive_dream_journal__default',
    title: 'Dream Journal',
    routeHash: '#/fortune/interactive/dream-journal',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/interactive/presentation/pages/dream_page.dart'],
  },
  {
    id: 'trend__hub__empty',
    pageKey: '40-trend',
    frameName: 'trend__hub__empty',
    title: 'Trend Hub Empty State',
    routeHash: '#/trend',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/trend/presentation/pages/trend_page.dart'],
  },
  {
    id: 'trend_psychology__detail__content',
    pageKey: '40-trend',
    frameName: 'trend_psychology__detail__content',
    title: 'Trend Psychology Detail',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker:
      'Backend trend_content table is empty in current dev data, so content detail cannot be opened from /trend.',
    sources: ['lib/features/trend/presentation/pages/trend_psychology_test_page.dart'],
  },
  {
    id: 'trend_psychology__result__summary',
    pageKey: '40-trend',
    frameName: 'trend_psychology__result__summary',
    title: 'Trend Psychology Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker: 'Requires seeded trend content plus completed test answers.',
    sources: ['lib/features/trend/presentation/pages/trend_psychology_test_page.dart'],
  },
  {
    id: 'trend_worldcup__detail__bracket',
    pageKey: '40-trend',
    frameName: 'trend_worldcup__detail__bracket',
    title: 'Trend Ideal Worldcup',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker: 'Requires backend trend content record with worldcup payload.',
    sources: ['lib/features/trend/presentation/pages/trend_ideal_worldcup_page.dart'],
  },
  {
    id: 'trend_worldcup__result__winner',
    pageKey: '40-trend',
    frameName: 'trend_worldcup__result__winner',
    title: 'Trend Worldcup Winner Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker: 'Requires seeded bracket data and completed selection flow.',
    sources: ['lib/features/trend/presentation/pages/trend_ideal_worldcup_page.dart'],
  },
  {
    id: 'trend_balance__detail__play',
    pageKey: '40-trend',
    frameName: 'trend_balance__detail__play',
    title: 'Trend Balance Game',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker: 'Requires backend trend content record with balance-game payload.',
    sources: ['lib/features/trend/presentation/pages/trend_balance_game_page.dart'],
  },
  {
    id: 'trend_balance__result__summary',
    pageKey: '40-trend',
    frameName: 'trend_balance__result__summary',
    title: 'Trend Balance Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_seed_data',
    blocker: 'Requires seeded balance-game content and summary completion.',
    sources: ['lib/features/trend/presentation/pages/trend_balance_game_page.dart'],
  },
  {
    id: 'health__input__default',
    pageKey: '50-health-exercise',
    frameName: 'health__input__default',
    title: 'Health Fortune Input',
    routeHash: '#/health-toss',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: [
      'lib/features/health/presentation/pages/health_fortune_page.dart',
      'lib/features/health/presentation/pages/health_fortune/health_fortune_page.dart',
    ],
  },
  {
    id: 'health__result__analysis',
    pageKey: '50-health-exercise',
    frameName: 'health__result__analysis',
    title: 'Health Fortune Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker: 'Needs successful health fortune generation after completing input flow.',
    sources: ['lib/features/health/presentation/pages/health_fortune/health_fortune_page.dart'],
  },
  {
    id: 'medical_document__result__analysis',
    pageKey: '50-health-exercise',
    frameName: 'medical_document__result__analysis',
    title: 'Medical Document Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_state_extra',
    blocker: 'GoRouter state.extra upload payload is required to render this page.',
    sources: ['lib/features/health/presentation/pages/medical_document_result_page.dart'],
  },
  {
    id: 'exercise__input__default',
    pageKey: '50-health-exercise',
    frameName: 'exercise__input__default',
    title: 'Exercise Fortune Input',
    routeHash: '#/exercise',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/exercise/presentation/pages/exercise_fortune_page.dart'],
  },
  {
    id: 'exercise__result__analysis',
    pageKey: '50-health-exercise',
    frameName: 'exercise__result__analysis',
    title: 'Exercise Fortune Result',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_runtime',
    blocker: 'Needs multi-step selection flow plus successful edge function response.',
    sources: ['lib/features/exercise/presentation/pages/exercise_fortune_page.dart'],
  },
  {
    id: 'sports_game__input__default',
    pageKey: '50-health-exercise',
    frameName: 'sports_game__input__default',
    title: 'Sports Game',
    routeHash: '#/sports-game',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/exercise/presentation/pages/exercise_fortune_page.dart'],
  },
  {
    id: 'history__empty__default',
    pageKey: '60-history-profile-more',
    frameName: 'history__empty__default',
    title: 'History Empty State',
    routeHash: '#/history',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/history/presentation/pages/fortune_history_page.dart'],
  },
  {
    id: 'fortune_history__detail__extra',
    pageKey: '60-history-profile-more',
    frameName: 'fortune_history__detail__extra',
    title: 'History Detail',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_state_extra',
    blocker: 'GoRouter state.extra FortuneHistory payload is required for detail rendering.',
    sources: ['lib/features/history/presentation/pages/fortune_history_detail_page.dart'],
  },
  {
    id: 'more__guest__default',
    pageKey: '60-history-profile-more',
    frameName: 'more__guest__default',
    title: 'More Guest State',
    routeHash: '#/more',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/more/presentation/pages/more_page.dart'],
  },
  {
    id: 'profile__root__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__root__auth_gated',
    title: 'Profile Root',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker:
      'Current test auto-login is blocked by backend user-create failure, so /profile remains auth-gated in live capture.',
    sources: ['lib/screens/profile/profile_screen.dart'],
  },
  {
    id: 'profile__edit__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__edit__auth_gated',
    title: 'Profile Edit',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Requires authenticated user profile data.',
    sources: ['lib/screens/profile/profile_edit_page.dart'],
  },
  {
    id: 'profile__saju__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__saju__auth_gated',
    title: 'Profile Saju',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Requires authenticated user profile data.',
    sources: ['lib/screens/profile/saju_detail_page.dart'],
  },
  {
    id: 'profile__saju_summary__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__saju_summary__auth_gated',
    title: 'Profile Saju Summary',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Requires authenticated user profile data.',
    sources: ['lib/screens/profile/saju_summary_page.dart'],
  },
  {
    id: 'profile__elements__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__elements__auth_gated',
    title: 'Profile Elements',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Requires authenticated user profile data.',
    sources: ['lib/screens/profile/elements_detail_page.dart'],
  },
  {
    id: 'profile__verification__auth_gated',
    pageKey: '60-history-profile-more',
    frameName: 'profile__verification__auth_gated',
    title: 'Profile Verification',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Requires authenticated user profile data.',
    sources: ['lib/screens/profile/profile_verification_page.dart'],
  },
  {
    id: 'premium__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'premium__default',
    title: 'Premium',
    routeHash: '#/premium',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/screens/premium/premium_screen.dart'],
  },
  {
    id: 'subscription__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'subscription__default',
    title: 'Subscription',
    routeHash: '#/subscription',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/screens/subscription/subscription_page.dart'],
  },
  {
    id: 'token_purchase__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'token_purchase__default',
    title: 'Token Purchase',
    routeHash: '#/token-purchase',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/payment/presentation/pages/token_purchase_page.dart'],
  },
  {
    id: 'help__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'help__default',
    title: 'Help',
    routeHash: '#/help',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/support/presentation/pages/help_page.dart'],
  },
  {
    id: 'privacy_policy__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'privacy_policy__default',
    title: 'Privacy Policy',
    routeHash: '#/privacy-policy',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/policy/presentation/pages/privacy_policy_page.dart'],
  },
  {
    id: 'terms_of_service__default',
    pageKey: '70-commerce-settings-support',
    frameName: 'terms_of_service__default',
    title: 'Terms of Service',
    routeHash: '#/terms-of-service',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/policy/presentation/pages/terms_of_service_page.dart'],
  },
  {
    id: 'profile__notifications__auth_gated',
    pageKey: '70-commerce-settings-support',
    frameName: 'profile__notifications__auth_gated',
    title: 'Notification Settings',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Nested under /profile and requires authenticated session.',
    sources: ['lib/features/notification/presentation/pages/notification_settings_page.dart'],
  },
  {
    id: 'profile__font__auth_gated',
    pageKey: '70-commerce-settings-support',
    frameName: 'profile__font__auth_gated',
    title: 'Font Settings',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Nested under /profile and requires authenticated session.',
    sources: ['lib/features/settings/presentation/pages/font_settings_page.dart'],
  },
  {
    id: 'profile__social_accounts__auth_gated',
    pageKey: '70-commerce-settings-support',
    frameName: 'profile__social_accounts__auth_gated',
    title: 'Social Accounts',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Nested under /profile and requires authenticated session.',
    sources: ['lib/screens/settings/social_accounts_screen.dart'],
  },
  {
    id: 'profile__phone_management__auth_gated',
    pageKey: '70-commerce-settings-support',
    frameName: 'profile__phone_management__auth_gated',
    title: 'Phone Management',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Nested under /profile and requires authenticated session.',
    sources: ['lib/screens/settings/phone_management_screen.dart'],
  },
  {
    id: 'profile__account_deletion__auth_gated',
    pageKey: '70-commerce-settings-support',
    frameName: 'profile__account_deletion__auth_gated',
    title: 'Account Deletion',
    routeHash: null,
    status: 'placeholder',
    triage: 'capture_next_auth',
    blocker: 'Nested under /profile and requires authenticated session.',
    sources: ['lib/screens/profile/account_deletion_page.dart'],
  },
  {
    id: 'wellness__landing__default',
    pageKey: '75-wellness',
    frameName: 'wellness__landing__default',
    title: 'Wellness Landing',
    routeHash: '#/wellness',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/wellness/presentation/pages/wellness_page.dart'],
  },
  {
    id: 'wellness__meditation__default',
    pageKey: '75-wellness',
    frameName: 'wellness__meditation__default',
    title: 'Meditation',
    routeHash: '#/wellness/meditation',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/wellness/presentation/pages/meditation_page.dart'],
  },
  {
    id: 'admin__celebrity_crawling__error',
    pageKey: '80-admin-policy-utility',
    frameName: 'admin__celebrity_crawling__error',
    title: 'Admin Celebrity Crawling',
    routeHash: '#/admin/celebrity-crawling',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    note: 'Current dev schema renders an operational error banner for the stats query.',
    sources: ['lib/features/admin/pages/celebrity_crawling_page.dart'],
  },
  {
    id: 'manseryeok__default',
    pageKey: '80-admin-policy-utility',
    frameName: 'manseryeok__default',
    title: 'Manseryeok',
    routeHash: '#/manseryeok',
    status: 'live',
    waitMs: 10000,
    buildStorage: () => ({
      'flutter.character_onboarding_completed': 'true',
    }),
    sources: ['lib/features/fortune/presentation/pages/manseryeok_page.dart'],
  },
];

const COMPONENT_CARDS = [
  {
    title: 'App Shell and Headers',
    sources: [
      'lib/shared/layouts/main_shell.dart',
      'lib/shared/components/app_header.dart',
      'lib/shared/components/profile_header_icon.dart',
    ],
  },
  {
    title: 'Cards, Buttons, Inputs',
    sources: [
      'lib/core/design_system/components/ds_card.dart',
      'lib/core/design_system/components/ds_button.dart',
      'lib/core/design_system/components/ds_text_field.dart',
      'lib/core/widgets/unified_button.dart',
    ],
  },
  {
    title: 'Settings and Commerce Rows',
    sources: [
      'lib/shared/components/settings_list_tile.dart',
      'lib/shared/components/premium_membership_card.dart',
      'lib/shared/components/token_balance_widget.dart',
      'lib/shared/components/token_insufficient_modal.dart',
    ],
  },
  {
    title: 'Fortune and Result Blocks',
    sources: [
      'lib/shared/components/section_header.dart',
      'lib/shared/components/loading_states.dart',
      'lib/features/character/presentation/widgets/character_message_bubble.dart',
      'lib/features/chat/presentation/widgets/chat_saju_result_card.dart',
    ],
  },
  {
    title: 'Wellness Focus Blocks',
    sources: [
      'lib/features/wellness/presentation/pages/wellness_page.dart',
      'lib/features/wellness/presentation/pages/meditation_page.dart',
      'lib/features/wellness/presentation/widgets/breathing_timer_widget.dart',
      'lib/features/wellness/presentation/widgets/meditation_completion_sheet.dart',
    ],
  },
];

function getScreensByPage() {
  return FIGMA_PAGES.map((page) => ({
    ...page,
    screens: SCREENS.filter((screen) => screen.pageKey === page.key),
  }));
}

function getStatusCounts() {
  return SCREENS.reduce(
    (acc, screen) => {
      acc[screen.status] = (acc[screen.status] || 0) + 1;
      return acc;
    },
    {}
  );
}

function getPlaceholderTriageCounts() {
  return SCREENS.filter((screen) => screen.status === 'placeholder').reduce(
    (acc, screen) => {
      const triageKey = screen.triage || 'unclassified';
      acc[triageKey] = (acc[triageKey] || 0) + 1;
      return acc;
    },
    {}
  );
}

module.exports = {
  COMPONENT_CARDS,
  FIGMA_PAGES,
  IPHONE_15_PRO,
  SCREENS,
  getPlaceholderTriageCounts,
  getScreensByPage,
  getStatusCounts,
};
